// Actual public deployment check. No auth key or private workspace is used.
const fs=require('node:fs');const {chromium}=require(process.env.DAYBOARD_PLAYWRIGHT);
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const url='https://dayboard-501.onrender.com';let ready=false;
try{for(let attempt=0;attempt<12;attempt++){await page.goto(url+'/?verify='+process.env.GITHUB_SHA,{waitUntil:'networkidle',timeout:30000});if(await page.evaluate(()=>window.dayboardVersion==='2.0.0')){ready=true;break;}await page.waitForTimeout(5000);}if(!ready)throw new Error('Production did not serve v2 within deployment wait');
await page.locator('[data-action=demo]').click();await page.locator('.dashboard-grid').waitFor();if(await page.locator('.timeline').count())throw new Error('Timeline must be opt-in');if(await page.locator('.dash-panel').count()!==4)throw new Error('Expected four dashboard panels');
fs.mkdirSync('dayboard-test-output/v2',{recursive:true});await page.screenshot({path:'dayboard-test-output/v2/live-PC.png',fullPage:true});
await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile document overflow');await page.screenshot({path:'dayboard-test-output/v2/live-mobile.png',fullPage:true});
await page.locator('[data-action=timeline-detail]').click();await page.locator('.timeline').waitFor();await page.locator('[data-action=timeline-list]').click();await page.locator('.dash-agenda-list').waitFor();if(errors.length)throw new Error(errors.join('\n'));
fs.writeFileSync('dayboard-test-output/v2/live.json',JSON.stringify({passed:4,failed:0,url,version:'2.0.0',commit:process.env.GITHUB_SHA,checks:['Actual deployment reports version 2.0.0','Four dashboard panels and list-first schedule','390px mobile no overflow','Timeline toggle works; no JS errors'],data:'Built-in sample only; no owner schedule accessed'},null,2));console.log('LIVE v2: 4 checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
