import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {LEVELS,EXPECTED,STARTERS,SOURCE_REV,validateStoredPack,courses,parsePack,writingChars} from '../src/catalog.js';import {fresh,createClass,validateState,current,submit,next,unresolved} from '../src/course-engine.js';
const loaded=[];for(const l of LEVELS){try{loaded.push(validateStoredPack(JSON.parse(await readFile(new URL(`../data/${l}.json`,import.meta.url),'utf8'))));}catch{}}
const available=loaded.length===5;
test('full source packs present for all N1-N5 levels',()=>assert.equal(available,true));
test('all 8334 raw source rows preserved through merge + editorial additions',()=>{assert.equal(loaded.reduce((n,p)=>n+p.sourceRows,0),8334);assert.equal(loaded.reduce((n,p)=>n+p.words.length,0),8451);for(const p of loaded){assert.equal(p.words.length,p.sourceRows-p.merged+p.supplemental);assert.equal(p.sourceRevision,SOURCE_REV);assert.equal(p.complete,true);}});
test('every installed word belongs to exactly one lesson in its level',()=>{for(const p of loaded){const list=courses(p.words,p.level);const ids=list.flatMap(c=>c.wordIds);assert.equal(ids.length,p.words.length);assert.equal(new Set(ids).size,p.words.length);assert.ok(list.every(c=>c.wordIds.length>=1&&c.wordIds.length<=5));}});
test('full pack installation preserves original starter lesson IDs and word order',()=>{for(const p of loaded){const a=courses(STARTERS,p.level),b=courses(p.words,p.level);for(let i=0;i<a.length;i++)assert.deepEqual(b[i],a[i]);}});
test('every source word has a writing target; all quiz options are meaningful',()=>{const words=loaded.flatMap(p=>p.words);for(const w of words){assert.ok(w.meaning.trim());assert.ok(writingChars(w).length>0);assert.ok(['ko','en'].includes(w.language));}for(const p of loaded){const list=courses(words,p.level);for(const c of [list[0],list[Math.floor(list.length/2)],list.at(-1)]){const s=createClass(fresh(),c,words);assert.equal(s.originalQuiz,c.wordIds.length*3);for(const t of s.queue.filter(t=>t.phase==='quiz'&&t.skill!=='writing')){assert.ok(t.options.length>=2);assert.equal(t.options.length,new Set(t.options).size);}}}});
test('duplicate canonical source rows merge senses without silently losing words',()=>{const rows=[{word:'水',reading:'みず',meanings:['water'],level:'N5'},{word:'水',reading:'みず',meanings:['fluid'],level:'N5'},{word:'山',reading:'やま',meanings:['mountain'],level:'N5'},{word:'火',reading:'ひ',meanings:['fire'],level:'N5'}];const p=parsePack(rows,'N5',{strict:false});assert.equal(p.merged,1);assert.equal(p.sourceRows,4);assert.equal(p.quarantine.length,0);assert.equal(p.complete,false);assert.deepEqual(p.words.find(w=>w.word==='水').sourceMeanings,['water','fluid']);});
test('import cannot turn a training activity into a final exam question',()=>{const s=fresh();s.session=createClass(s,courses(STARTERS,'N5')[0],STARTERS);s.session.queue[0].phase='quiz';assert.throws(()=>validateState(s));});
test('missing class metadata rejected instead of crashing at finish',()=>{const s=fresh();s.session=createClass(s,courses(STARTERS,'N5')[0],STARTERS);s.session.course=null;assert.throws(()=>validateState(s));});
test('recognition method survives session restore',()=>{const s=fresh();s.session=createClass(s,courses(STARTERS,'N5')[0],STARTERS);s.session.ink={characters:[[[[.1,.2],[.3,.4]]]],results:[true],active:0,method:'mlkit'};assert.equal(validateState(s).session.ink.method,'mlkit');});
