import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {fresh,createClass,classifySurvey,current,submit,next,validateState} from '../src/course-engine.js';
import {courses,writingChars} from '../src/catalog.js';
import {ALL_KANA,kanaLessons,freshKana,startKana,kanaCurrent,advanceKana,validateKana} from '../src/kana-engine.js';
import {matchStroke,matchNextStroke,validPrefix} from '../src/stroke-match.js';
import {reminderSchedule} from '../src/reminders.js';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const words=['N5','N4','N3','N2','N1'].flatMap(l=>JSON.parse(read(`../data/${l}.json`)).words),bank=JSON.parse(read('../data/strokes.json')).characters;
function oneUnknown(name,setting){const s=fresh(),w=words.find(w=>w.level==='N5'&&w.word===name),c=courses(words,'N5').find(c=>c.wordIds.includes(w.id));s.settings.kanjiOnlyPractice=setting;s.session=createClass(s,c,words);while(current(s.session)?.phase==='survey'){const t=current(s.session);classifySurvey(s,t.id,t.wordId!==w.id,words);}return {s,w};}
test('kana course has 46 basic and 81 total letters per script, with all stroke data',()=>{assert.equal(ALL_KANA.length,162);assert.equal(new Set(ALL_KANA.map(c=>c.id)).size,162);for(const script of ['h','k']){assert.equal(kanaLessons(script).filter(l=>l.basic).flatMap(l=>l.letters).length,46);assert.equal(kanaLessons(script).flatMap(l=>l.letters).length,81);}for(const l of ALL_KANA)assert.ok(bank[l.char]?.length,l.char);});
test('kana sessions require two guided practices and unassisted recall',()=>{const k=freshKana();startKana(k,'h-r');const p=bank['ら'];assert.equal(kanaCurrent(k).char,'ら');assert.equal(advanceKana(k,p.length),false);for(let i=0;i<2;i++){k.session.strokes=p;advanceKana(k,p.length);assert.equal(k.progress['KANA-h3089'],undefined);}assert.equal(k.session.stage,2);k.session.hinted=true;k.session.strokes=p;advanceKana(k,p.length);assert.equal(k.session.stage,2);assert.equal(k.session.strokes.length,0);assert.equal(k.progress['KANA-h3089'],undefined);k.session.strokes=p;advanceKana(k,p.length,1000);assert.equal(k.progress['KANA-h3089'].passes,1);assert.equal(k.progress['KANA-h3089'].due,86401000);assert.equal(kanaCurrent(k).char,'り');});
test('kanji-only training skips kana trace but retains meaning/listening/writing exams',()=>{for(const name of ['おまわりさん','テレビ']){const {s,w}=oneUnknown(name,true);assert.equal(s.session.queue.filter(t=>t.wordId===w.id&&t.skill==='trace').length,0);assert.deepEqual(s.session.queue.filter(t=>t.wordId===w.id&&t.phase==='quiz').map(t=>t.skill).sort(),['listening','meaning','writing']);}});
test('kanji words keep three training repetitions, and kana keeps them when option off',()=>{for(const [name,setting]of [['山',true],['おまわりさん',false]]){const {s,w}=oneUnknown(name,setting);assert.equal(s.session.queue.filter(t=>t.wordId===w.id&&t.skill==='trace').length,3);}});
test('kana-only writing exam is an actual required skill, not auto-passed',()=>{const {s,w}=oneUnknown('テレビ',true);s.session.index=s.session.queue.findIndex(t=>t.skill==='writing');assert.equal(s.session.passed[w.id+':writing'],undefined);submit(s,current(s.session).id,{correct:false,method:'stroke-snap'});assert.notEqual(s.session.passed[w.id+':writing'],true);});
test('kana progress, active lesson route and settings survive state validation',()=>{const {s}=oneUnknown('山',true);s.uiRoute='lesson';startKana(s.kana,'k-a');s.kana.session.strokes=[bank['ア'][0]];s.settings.audioEngine='device';s.settings.reviewNotifications=false;const r=validateState(JSON.parse(JSON.stringify(s)));assert.equal(r.uiRoute,'lesson');assert.equal(r.settings.kanjiOnlyPractice,true);assert.equal(r.settings.audioEngine,'device');assert.equal(r.settings.reviewNotifications,false);assert.equal(r.kana.session.strokes.length,1);assert.ok(r.session);});
test('old default slow audio migrates once, but explicit 0.7 speed is preserved',()=>{const s=fresh();delete s.settings.audioRevision;s.settings.rate=.85;assert.equal(validateState(s).settings.rate,1);s.settings.rate=.7;assert.equal(validateState(s).settings.rate,.7);s.settings.audioRevision=2;s.settings.rate=.85;assert.equal(validateState(s).settings.rate,.85);});
test('ら first stroke accepts a short diagonal line and survives restore',()=>{const p=[[.33,.14],[.39,.175],[.49,.215]],strokes=bank['ら'];assert.equal(matchNextStroke(p,strokes,0,{character:'ら'}).accepted,true);assert.equal(validPrefix([p],strokes,{character:'ら'}).length,1);assert.equal(matchNextStroke([...p].reverse(),strokes,0,{character:'ら'}).accepted,false);assert.equal(matchNextStroke([[.5,.5],[.5,.5]],strokes,0,{character:'ら'}).accepted,false);});
test('more forgiving matcher still rejects blank, backwards, taps, loops and whole-character scribble',()=>{const t=bank['山'];for(const path of [[],[[.5,.5]],[[NaN,0],[.5,.7]],t.flat(),[...t[0]].reverse(),Array.from({length:300},(_,i)=>[.5+.3*Math.cos(i),.5+.3*Math.sin(i)])])assert.equal(matchNextStroke(path,t,0).accepted,false);});
test('reminder payload includes all levels and kana but no text or purchase data',()=>{const s=fresh();s.memory={a:{due:300},b:{due:100},c:{due:100},d:{due:NaN}};s.kana.progress={x:{due:200}};assert.deepEqual(reminderSchedule(s),{enabled:true,dueTimes:[100,200,300]});s.settings.reviewNotifications=false;assert.equal(reminderSchedule(s).enabled,false);});
test('original examples cover all 300 starter slots, with Japanese, Korean and readings',()=>{const pack=JSON.parse(read('../data/examples.json')),targets=new Set(pack.entries.flatMap(e=>e.targets));assert.equal(pack.entries.length,164);assert.equal(new Set(pack.entries.map(e=>e.ja)).size,164);for(const e of pack.entries){assert.match(e.ja,/[\u3040-\u30ff]/);assert.match(e.ko,/[가-힣]/);assert.ok(e.reading);assert.match(e.source,/original/);}for(const l of ['N5','N4','N3','N2','N1'])for(const w of JSON.parse(read(`../data/${l}.json`)).words.slice(0,60))assert.ok(targets.has(w.word),w.word);});
test('native rotation handles configuration changes and restores valid internal routes',()=>{const m=read('../../kotoba-android/app/src/main/AndroidManifest.xml'),a=read('../../kotoba-android/app/src/main/java/com/studio501/kotoba/MainActivity.java');assert.match(m,/configChanges="[^"]*orientation\|screenSize/);assert.match(a,/onConfigurationChanged/);assert.match(a,/web\.invalidate\(\)/);assert.match(a,/out\.putString\("kotoba-url"/);assert.match(a,/web\.loadUrl\(restored\)/);assert.doesNotMatch(a,/web\.loadUrl\(START\)/);});
test('system TTS filters network and missing voices; notifications use no exact alarm privilege',()=>{const a=read('../../kotoba-android/app/src/main/java/com/studio501/kotoba/JapaneseSpeech.java'),m=read('../../kotoba-android/app/src/main/AndroidManifest.xml');assert.match(a,/isNetworkConnectionRequired/);assert.match(a,/KEY_FEATURE_NOT_INSTALLED/);assert.match(a,/onDone/);assert.match(m,/POST_NOTIFICATIONS/);assert.match(m,/BOOT_COMPLETED/);assert.doesNotMatch(m,/SCHEDULE_EXACT_ALARM|USE_EXACT_ALARM|RECORD_AUDIO/);});

import {execFileSync} from 'node:child_process';
test('standard source build validates device-only audio and complete learning assets',()=>{
 const output=execFileSync(process.execPath,['scripts/verify-bundled-assets.mjs'],{cwd:new URL('../',import.meta.url),encoding:'utf8'});
 const report=JSON.parse(output.trim());assert.equal(report.valid,true);assert.equal(report.audio,0);assert.equal(report.audioMode,'device-only');assert.equal(report.kana,162);assert.equal(report.networkFetches,0);
});
