const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=path.resolve('dayboard'),out=path.resolve('dayboard-test-output/chronicle');fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],logs=[];let server,browser,page,c,j,d,content,snapshot;
async function test(name,fn){try{await fn();checks.push({name,passed:true});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.stack||String(e)});throw e;}}
async function wait(fn){for(let n=0;n<100;n++){if(await fn())return;await new Promise(r=>setTimeout(r,50));}throw new Error('Expected saved state did not settle');}
const shot=async name=>{await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});};
(async()=>{try{
 c=await import(pathToFileURL(path.join(root,'core.js')).href);j=await import(pathToFileURL(path.join(root,'journey-domain.js')).href);d=await import(pathToFileURL(path.join(root,'chronicle-domain.js')).href);content=await import(pathToFileURL(path.join(root,'chronicle-content.js')).href);
 const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webp':'image/webp','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
 server=http.createServer((req,res)=>{let target=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(target===root)target=path.join(root,'index.html');if(!target.startsWith(root+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'text/plain'});fs.createReadStream(target).pipe(res);});await new Promise(r=>server.listen(4182,'127.0.0.1',r));
 const {chromium}=require(process.env.DAYBOARD_PLAYWRIGHT||'playwright');browser=await chromium.launch({headless:true});
 const at=new Date().toISOString();let state={items:Array.from({length:200},(_,n)=>c.newItem({title:'Synthetic task '+n,status:'done',progress:100,completedAt:at,estimatedMinutes:300,category:'검증'})),blocks:[],settings:{...c.DEFAULTS}};state=c.applyLocal(state,[]);
 snapshot={workspaceId:c.uid(),name:'Synthetic Chronicle QA',revision:0,state,proposals:[],history:[],updatedAt:at};const key='7'.repeat(64);
 async function context(viewport={width:1440,height:1000}){const ctx=await browser.newContext({viewport,timezoneId:'Asia/Seoul',locale:'ko-KR'});await ctx.addInitScript(key=>localStorage.setItem('dayboard.key',key),key);await ctx.route('https://mahmzgdseyamqcffxwyd.supabase.co/rest/v1/rpc/**',async r=>{const body=r.request().postDataJSON(),method=r.request().url().split('/').pop();if(body.p_key!==key)return r.fulfill({status:401,json:{message:'UNAUTHORIZED'}});if(method==='dayboard_apply'){if(body.p_base_revision!==snapshot.revision)return r.fulfill({status:409,json:{message:'VERSION_CONFLICT'}});try{snapshot.state=c.applyLocal(snapshot.state,body.p_operations);snapshot.revision++;snapshot.updatedAt=new Date().toISOString();}catch(e){return r.fulfill({status:400,json:{message:e.message}});}}return r.fulfill({json:snapshot});});return ctx;}
 const ctx=await context();page=await ctx.newPage();page.on('pageerror',e=>errors.push(String(e.stack||e)));page.on('console',m=>{if(m.type()==='error')logs.push(m.text());});page.on('dialog',q=>q.accept());
 async function nav(tab){const locator=page.locator(`.cr-tabs [data-action][data-id="${tab}"]`);await locator.click();}
 await test('Chronicle renders in Adventure without replacing the task dashboard',async()=>{await page.goto('http://127.0.0.1:4182/',{waitUntil:'networkidle'});await page.locator('.dashboard-grid').waitFor();assert.equal(await page.locator('.cr-shell').count(),0);await page.locator('.sidebar [data-id=adventure]').click();await page.locator('.cr-shell').waitFor();assert.equal(await page.title(),'Dayboard · 나의 일정');assert.equal(await page.locator('.cr-shell').getAttribute('data-chronicle-version'),'4.0.0');await wait(()=>page.locator('.j-traveler').evaluate(e=>e.complete&&e.naturalWidth>0));assert((await page.locator('.cr-hours').innerText()).includes('1,000'));await shot('chronicle-desktop');});
 await test('Read three scenes and save a story choice; task data and currency stay unchanged',async()=>{const items=JSON.stringify(snapshot.state.items),balance=j.economy(snapshot.state).balance;await page.locator('[data-action=cr-read][data-id=harbor-1]').first().click();await page.locator('.cr-prose').waitFor();await page.locator('.cr-reader-controls [data-id="1"]').click();await page.locator('.cr-reader-controls [data-id="2"]').click();await page.locator('[data-action=cr-choose][data-id="harbor-1|a"]').click();await wait(()=>d.chronicleState(snapshot.state).chapters.length===1);await page.locator('.cr-outcome').waitFor();assert((await page.locator('.cr-outcome').innerText()).includes('발자국을 따라'));assert.equal(JSON.stringify(snapshot.state.items),items);assert.equal(j.economy(snapshot.state).balance,balance);await shot('story-choice-desktop');});
 await test('Reload preserves the chosen outcome and replay has no duplicate write',async()=>{const count=d.chronicleState(snapshot.state).chapters.length;await page.reload({waitUntil:'networkidle'});await page.locator('.sidebar [data-id=adventure]').click();await nav('story');await page.locator('.cr-chapter-list [data-id=harbor-1]').click();await page.locator('.cr-reader-controls [data-id="1"]').click();await page.locator('.cr-reader-controls [data-id="2"]').click();await page.locator('.cr-outcome').waitFor();assert.equal(await page.locator('[data-action=cr-choose]').count(),0);assert.equal(d.chronicleState(snapshot.state).chapters.length,count);});
 await test('Future region shows its conditions without exposing unread story prose',async()=>{await nav('atlas');assert.equal(await page.locator('.cr-atlas-grid .cr-region').count(),12);await page.locator('.cr-atlas-grid [data-id=dawn]').first().click();await page.locator('.cr-realm-detail [data-id=dawn-1]').click();await page.locator('.cr-locked-story').waitFor();assert.equal(await page.locator('.cr-prose').count(),0);assert.equal(await page.locator('[data-action=cr-choose]').count(),0);});
 await test('Shop filters 84 actual catalog items; preview never spends stars',async()=>{await nav('shop');assert.equal(await page.locator('.cr-product').count(),18);const before=j.economy(snapshot.state).balance;await page.locator('#cr-shop-realm').selectOption('harbor');assert.equal(await page.locator('.cr-product').count(),6);await page.locator('[data-action=cr-preview][data-id=chron-harbor-relic]').click();assert((await page.locator('.cr-stage-foot').innerText()).includes('미리보기'));assert.equal(j.economy(snapshot.state).balance,before);await page.locator('[data-action=cr-preview-clear]').click();});
 await test('Expanded relic can be purchased once and remains equipped after refresh',async()=>{const before=j.economy(snapshot.state).balance;await page.locator('[data-action=v3-buy][data-id=chron-harbor-relic]').click();await wait(()=>j.gameState(snapshot.state).purchases.some(x=>x.id==='chron-harbor-relic'));assert.equal(j.economy(snapshot.state).balance,before-100);assert.equal(j.gameState(snapshot.state).relic,'chron-harbor');await wait(()=>page.locator('[data-action=v3-equip][data-id=chron-harbor-relic]').isDisabled());await shot('continental-shop-desktop');});
 await test('Free 1,000-hour title saves a unique unlock and changes hero title',async()=>{await nav('titles');await page.locator('[data-action=cr-title-filter][data-id=ready]').click();const title=page.locator('[data-action=cr-title][data-id=hours-1000]');await title.click();await wait(()=>d.chronicleState(snapshot.state).equippedTitle==='hours-1000');await wait(()=>page.locator('.cr-equipped-title').innerText().then(t=>t.includes('천 시간의 여행자')));assert.equal(d.chronicleState(snapshot.state).titles.filter(x=>x.id==='hours-1000').length,1);});
 await test('A region mission awards a codex memory once without issuing fake stars',async()=>{const before=j.economy(snapshot.state).balance;await nav('quests');await page.locator('.cr-mission-region[open] [data-action=cr-mission][data-id=harbor-survey]').click();await wait(()=>d.chronicleState(snapshot.state).missions.some(x=>x.id==='harbor-survey'));assert.equal(j.economy(snapshot.state).balance,before);await nav('codex');await page.locator('#cr-codex-realm').selectOption('harbor');assert.equal(await page.locator('.cr-codex-grid article.owned').count(),1);});
 await test('Role switch saves; talent purchase remains disabled without earned points',async()=>{await nav('mastery');await page.locator('[data-action=cr-role][data-id=scribe]').click();await wait(()=>d.chronicleState(snapshot.state).role==='scribe');assert(await page.locator('[data-action=cr-talent][data-id=scribe-1]').isDisabled());assert.equal(await page.locator('.cr-talent-grid article').count(),18);});
 await test('Second browser reads chapter, title and purchased relic from the same mock workspace',async()=>{const second=await context({width:390,height:844}),mp=await second.newPage();await mp.goto('http://127.0.0.1:4182/');await mp.locator('.mobile-nav [data-action=v3-more]').click();await mp.locator('#modal [data-action=v3-open-view][data-id=adventure]').click();await mp.locator('.cr-shell').waitFor();assert((await mp.locator('.cr-equipped-title').innerText()).includes('천 시간의 여행자'));assert((await mp.locator('.cr-next-head').innerText()).includes('1 / 96'));await mp.screenshot({path:path.join(out,'chronicle-mobile.png'),fullPage:true});await second.close();});
 await test('Endgame fixture unlocks all regions, story endings and talent points',async()=>{for(const ch of content.CHAPTERS.slice(d.chronicleState(snapshot.state).chapters.length))snapshot.state=c.applyLocal(snapshot.state,d.chronicleOperation(snapshot.state,'chapter',ch.id,'b'));snapshot.revision++;await page.locator('[data-action=refresh]').first().click();await nav('atlas');assert.equal(await page.locator('.cr-atlas-grid .cr-region.unlocked').count(),12);await page.locator('.cr-atlas-grid [data-id=dawn]').first().click();await page.locator('[data-action=cr-camp][data-id=dawn]').click();await wait(()=>d.chronicleState(snapshot.state).camp==='dawn');await nav('mastery');await page.locator('[data-action=cr-talent][data-id=scribe-1]').click();await wait(()=>d.chronicleState(snapshot.state).talents.includes('scribe-1'));assert((await page.locator('.cr-counter').innerText()).includes('23 / 24'));});
 await test('Desktop/tablet/mobile views have no horizontal page overflow or missing artwork',async()=>{for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:900});for(const tab of ['journey','atlas','story','shop','titles','codex','mastery']){await nav(tab);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}/${tab}`);}if(width===390){await nav('story');await shot('story-mobile');await nav('shop');await shot('shop-mobile');}}});
 await test('Reduced motion disables animated traveler and code emits no runtime errors',async()=>{await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.j-traveler-walk').evaluate(e=>getComputedStyle(e).animationName),'none');assert.deepEqual(errors,[]);assert.deepEqual(logs.filter(x=>!x.includes('ERR_ABORTED')),[]);});
 if(process.env.VERIFY_LIVE==='1')await test('Production route serves 4.0.0 and real interactive Chronicle without account data',async()=>{const live=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Seoul'}),p=await live.newPage();let ok=false;for(let n=0;n<12;n++){await p.goto(process.env.DAYBOARD_LIVE_URL||'https://dayboard-501.onrender.com',{waitUntil:'networkidle'});if(await p.evaluate(()=>window.dayboardVersion==='4.0.0')){ok=true;break;}await p.waitForTimeout(5000);}assert(ok);await p.locator('[data-action=demo]').click();await p.locator('.sidebar [data-id=adventure]').click();await p.locator('.cr-shell').waitFor();await p.screenshot({path:path.join(out,'live-chronicle-desktop.png'),fullPage:true});await p.locator('.cr-next-story [data-action=cr-read]').click();await p.locator('.cr-prose').waitFor();await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,'live-story-mobile.png'),fullPage:true});await live.close();});
 }catch(e){console.error(e.stack||e);if(page)try{await shot('failure');fs.writeFileSync(path.join(out,'failure-dom.txt'),await page.locator('body').innerText());}catch{}process.exitCode=1;}finally{if(browser)await browser.close();if(server)server.close();fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify({checks,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,errors,logs,environment:'Browser plugin not available. GitHub Actions Playwright/Chromium; synthetic workspace and mocked RPC. Separate PostgreSQL tests required. Live route is sample-only. No actual Google OAuth/calendar writes.'},null,2));console.log('Chronicle browser:',checks.filter(x=>x.passed).length,'passed');}})();
