// Real browser interactions; synthetic workspace only. No owner key or live calendar write.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=path.resolve('dayboard'),out=path.resolve('dayboard-test-output/v3');fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],consoleErrors=[];let browser,server,page,snapshot,c,j;
async function test(name,fn){try{await fn();checks.push({name,passed:true});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:String(e.stack||e)});throw e;}}
async function wait(check,message){for(let n=0;n<100;n++){if(await check())return;await new Promise(r=>setTimeout(r,40));}throw new Error(message||'State did not settle');}
async function shot(name){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function run(){
 c=await import(pathToFileURL(path.join(root,'core.js')).href);j=await import(pathToFileURL(path.join(root,'journey-domain.js')).href);
 const today=c.dateKey(),all=[0,1,2,3,4,5,6],fresh=()=>({items:[],blocks:[],settings:{...c.DEFAULTS}});
 await test('Daily N counts, goal limit, undo and no completion-toggle reward farming',()=>{let s=fresh(),i=c.newItem({title:'daily',repeatRule:{mode:'daily',target:2,days:all,start:today}});s.items=[i];s=c.applyLocal(s,j.repeatOperations(s,i.id,today));assert.equal(j.repeatStatus(s.items[0],today).count,1);s=c.applyLocal(s,j.repeatOperations(s,i.id,today));assert.equal(j.repeatStatus(s.items[0],today).count,2);const xp=j.economy(s).xp;assert.throws(()=>j.repeatOperations(s,i.id,today));s=c.applyLocal(s,j.repeatOperations(s,i.id,today,true));assert(j.economy(s).xp<xp);s=c.applyLocal(s,j.repeatOperations(s,i.id,today));assert.equal(j.economy(s).xp,xp);assert.equal(s.items.length,1);});
 await test('Weekly periods reset Monday and selected weekdays/future dates are enforced',()=>{const i=c.newItem({title:'weekly',repeatRule:{mode:'weekly',target:3,days:[1,3,5],start:'2026-01-01'}}),s={...fresh(),items:[i]};assert.equal(j.periodOf(j.spec(i),'2026-09-06'),'W:2026-08-31');assert.equal(j.periodOf(j.spec(i),'2026-09-07'),'W:2026-09-07');assert.throws(()=>j.repeatOperations(s,i.id,'2026-09-06'));assert.throws(()=>j.repeatOperations(s,i.id,c.addDays(today,100)));i.routinePaused=true;assert(!j.repeatStatus(i,today).canCheck);});
 await test('Routines are scheduled for remaining occurrences without duplicate reservations',()=>{let s=fresh();const d=c.addDays(today,2),i=c.newItem({title:'routine slot',estimatedMinutes:30,repeatRule:{mode:'daily',target:2,days:all,start:d}});s.items=[i];const plan=c.schedulePlan(s,d,1);assert.equal(plan.operations.filter(o=>o.collection==='blocks').length,2);s=c.applyLocal(s,plan.operations);assert.equal(c.schedulePlan(s,d,1).operations.length,0);});
 await test('Statistics retain deleted completion history and remove undone activity',()=>{let s=fresh(),i=c.newItem({title:'one',estimatedMinutes:45,deadline:today});s.items=[i];s=c.applyLocal(s,c.completeOps(s,i.id));assert.equal(j.statistics(s,7).events.length,1);assert.equal(j.statistics(s,7).minutes,45);const deleted=c.applyLocal(s,[{collection:'items',action:'delete',id:i.id}]);assert.equal(j.statistics(deleted,7).events.length,1);s=c.applyLocal(s,c.completeOps(s,i.id));assert.equal(j.statistics(s,7).events.length,0);});
 await test('Color inheritance and parent/leaf statistics avoid double counting',()=>{const p=c.newItem({kind:'project',title:'P',color:'teal'}),i=c.newItem({title:'T',parentId:p.id});let s={...fresh(),items:[p,i]};assert.equal(j.colorOf(i,s.items),'teal');s=c.applyLocal(s,c.completeOps(s,i.id));assert.equal(j.activity(s).length,1);assert.equal(j.rewardSummary(s).projects,1);});
 await test('Shop enforces balance, ownership and one-time purchase before UI calls',()=>{const s=fresh();assert.throws(()=>j.gameOperation(s,'buy','outfit-ranger'));assert.throws(()=>j.gameOperation(s,'equip','pet-cat'));});
 const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webp':'image/webp','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
 server=http.createServer((req,res)=>{let target=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(target===root)target=path.join(target,'index.html');if(!target.startsWith(root+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'text/plain'});fs.createReadStream(target).pipe(res);});
 await new Promise(r=>server.listen(4173,'127.0.0.1',r));
 const {chromium}=require(process.env.DAYBOARD_PLAYWRIGHT||'playwright');browser=await chromium.launch({headless:true});
 snapshot=c.demoSnapshot();snapshot.state=j.enrichDemo(snapshot.state);snapshot.state.settings.adventure={...j.DEFAULT_GAME,name:'검증용 여행자'};snapshot.workspaceId=c.uid();snapshot.name='QA synthetic board';
 const key='d'.repeat(64);
 async function makeContext(viewport={width:1440,height:1000}){const context=await browser.newContext({viewport,timezoneId:'Asia/Seoul',locale:'ko-KR',acceptDownloads:true});await context.addInitScript(k=>localStorage.setItem('dayboard.key',k),key);await context.route('https://mahmzgdseyamqcffxwyd.supabase.co/rest/v1/rpc/**',async route=>{const body=route.request().postDataJSON(),method=route.request().url().split('/').pop();if(body.p_key!==key)return route.fulfill({status:401,json:{message:'UNAUTHORIZED'}});if(method==='dayboard_apply'){if(body.p_base_revision!==snapshot.revision)return route.fulfill({status:409,json:{message:'VERSION_CONFLICT'}});snapshot.state=c.applyLocal(snapshot.state,body.p_operations);snapshot.revision++;snapshot.updatedAt=new Date().toISOString();}else if(method==='dayboard_propose'){const p={id:c.uid(),title:body.p_title,operations:body.p_operations,base_revision:body.p_base_revision,status:'pending',expires_at:new Date(Date.now()+86400000).toISOString()};snapshot.proposals.unshift(p);return route.fulfill({json:{proposalId:p.id}});}else if(method==='dayboard_decide'){const p=snapshot.proposals.find(p=>p.id===body.p_proposal_id);if(body.p_approved){if(p.base_revision!==snapshot.revision)return route.fulfill({status:409,json:{message:'VERSION_CONFLICT'}});snapshot.state=c.applyLocal(snapshot.state,p.operations);snapshot.revision++;}p.status=body.p_approved?'applied':'rejected';}return route.fulfill({json:snapshot});});return context;}
 const ctx=await makeContext();page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.stack||e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.accept());
 const nav=async v=>{await page.locator(`.sidebar [data-action="nav"][data-id="${v}"]`).click();};
 const modal=page.locator('#modal'),byTitle=t=>snapshot.state.items.find(i=>i.title===t),done=(id)=>snapshot.state.items.find(i=>i.id===id).status==='done';
 async function save(){await modal.locator('button[type=submit]').click();await modal.waitFor({state:'hidden'});}
 async function check(id,within='#app'){await page.locator(`${within} [data-action="complete"][data-id="${id}"]:visible`).first().click();}
 await test('App v3 loads real four-area dashboard and preserves existing connection',async()=>{await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});await page.locator('.dashboard-grid').waitFor();assert.equal(await page.evaluate(()=>window.dayboardVersion),c.VERSION);assert.equal(await page.locator('.dashboard-grid>.panel').count(),4);assert.deepEqual(errors,[]);await shot('dashboard-desktop');});
 let taskId;
 await test('Create task with color and all repeat controls visible',async()=>{await page.locator('.topbar [data-action=add-item]').click();await modal.locator('#title').fill('QA 모든 화면 완료');await modal.locator('#deadline').fill(today);await modal.locator('#estimatedMinutes').fill('45');await modal.locator('.j-color-choices label[title="청록"]').click();assert.equal(await modal.locator('#repeatMode').count(),1);await save();taskId=byTitle('QA 모든 화면 완료').id;assert.equal(byTitle('QA 모든 화면 완료').color,'teal');});
 await test('Today completes and undoes the task without deleting it',async()=>{await check(taskId);await wait(()=>done(taskId));await page.locator('.j-completed-strip summary').click();await check(taskId,'.j-completed-strip');await wait(()=>!done(taskId));});
 await test('Week completes and undoes the same task',async()=>{await nav('week');await check(taskId);await wait(()=>done(taskId));await check(taskId);await wait(()=>!done(taskId));await shot('week-desktop');});
 await test('Month date detail completes and undoes the same task',async()=>{await nav('month');await page.locator(`.month-date[data-id="${today}"]`).click();await check(taskId,'#modal');await wait(()=>done(taskId));await check(taskId,'#modal');await wait(()=>!done(taskId));await modal.locator('[data-action=close]').first().click();});
 await test('Kanban completes and undoes the same task',async()=>{await nav('board');await check(taskId);await wait(()=>done(taskId));await check(taskId);await wait(()=>!done(taskId));});
 let routineId;
 await test('Create daily two routine with weekday controls and color',async()=>{await page.locator('.topbar [data-action=add-item]').click();await modal.locator('#title').fill('QA 매일 두 번');await modal.locator('#repeatMode').selectOption('daily');await modal.locator('#repeatTarget').fill('2');await modal.locator('#repeatStart').fill(today);assert.equal(await modal.locator('[name=repeatDay]').count(),7);await modal.locator('.j-color-choices label[title="보라"]').click();await shot('repeat-editor');await save();routineId=byTitle('QA 매일 두 번').id;assert.equal(j.spec(byTitle('QA 매일 두 번')).target,2);});
 async function countRoutine(id,date,undo=false,within='#app'){const action=undo?'undo':'add';await page.locator(`${within} [data-action=v3-check][data-id="${id}|${date}|${action}"]:visible`).first().click();}
 await test('Daily count is shared by week, month and board; full goal can be undone',async()=>{await nav('week');await countRoutine(routineId,today);await wait(()=>byTitle('QA 매일 두 번').checkins.length===1);await nav('month');await page.locator(`.month-date[data-id="${today}"]`).click();await countRoutine(routineId,today,false,'#modal');await wait(()=>byTitle('QA 매일 두 번').checkins.length===2);await countRoutine(routineId,today,true,'#modal');await wait(()=>byTitle('QA 매일 두 번').checkins.length===1);await modal.locator('[data-action=close]').first().click();await nav('board');await countRoutine(routineId,today);await wait(()=>byTitle('QA 매일 두 번').checkins.length===2);assert.equal(byTitle('QA 매일 두 번').status,'todo');assert.equal(snapshot.state.items.filter(i=>i.title==='QA 매일 두 번').length,1);});
 await test('Weekly target and selected Mon/Wed/Fri persist through edit/reload',async()=>{await page.locator('.topbar [data-action=add-item]').click();await modal.locator('#title').fill('QA 매주 세 번');await modal.locator('#repeatMode').selectOption('weekly');await modal.locator('#repeatTarget').fill('3');for(const n of [0,2,4,6])await modal.locator(`.j-day-choice:has(input[value="${n}"])`).click();await save();assert.deepEqual(j.spec(byTitle('QA 매주 세 번')).days,[1,3,5]);});
 await test('Pausing a routine suppresses check-in controls, not history',async()=>{await nav('board');await page.locator(`[data-action=edit-item][data-id="${routineId}"]`).first().click();await modal.locator('[name=routinePaused]').check();await save();assert(byTitle('QA 매일 두 번').routinePaused);assert.equal(byTitle('QA 매일 두 번').checkins.length,2);});
 await test('Statistics show real derived counts and honest time labels',async()=>{await nav('stats');await page.locator('.j-stats').waitFor();const count=j.statistics(snapshot.state,30).events.length;assert((await page.locator('.j-kpi').first().innerText()).includes(String(count)));assert(await page.getByText('실측 집중시간이 아닙니다.',{exact:true}).count());await shot('statistics-desktop');await page.locator('[data-action=v3-range][data-id="7"]').click();assert((await page.locator('.j-stat-period').innerText()).includes(c.addDays(today,-6)));});
 await test('Reflection drafts survive refresh; saved reflection persists',async()=>{await page.locator('#reflection-form [name=win]').fill('작은 업무부터 끝냈다');await page.locator('#reflection-form [name=friction]').fill('할 일이 커서 시작이 늦었다');await page.locator('#reflection-form [name=next]').fill('내일 첫 행동은 20분으로');await page.locator('[data-action=refresh]').first().click();assert.equal(await page.locator('#reflection-form [name=win]').inputValue(),'작은 업무부터 끝냈다');await page.locator('#reflection-form [name=energy]').selectOption('4');await page.locator('#reflection-form button[type=submit]').click();await wait(()=>snapshot.state.settings.reflections?.[today]?.energy===4);await nav('today');await nav('stats');assert.equal(await page.locator('#reflection-form [name=next]').inputValue(),'내일 첫 행동은 20분으로');});
 await test('Statistics export contains selected period and no connection key',async()=>{const dl=page.waitForEvent('download');await page.locator('[data-action=v3-export-stats]').click();const file=await dl,tmp=path.join(out,'export-test.json');await file.saveAs(tmp);const text=fs.readFileSync(tmp,'utf8');assert(!text.includes(key));const data=JSON.parse(text);assert.equal(data.period.end,today);assert(data.meaning.includes('실측'));fs.unlinkSync(tmp);});
 await test('Adventure shows real artwork, 6 regions, working motion toggle',async()=>{await nav('adventure');await page.locator('.j-stage').waitFor();await wait(()=>page.locator('.j-traveler').evaluate(el=>el.complete&&el.naturalWidth>0));assert.equal(await page.locator('.j-zone').count(),6);assert.notEqual(await page.locator('.j-traveler-walk').evaluate(el=>getComputedStyle(el).animationName),'none');await page.locator('[data-action=v3-motion]').click();await page.locator('.j-stage.motion-off').waitFor();assert.equal(await page.locator('.j-traveler-walk').evaluate(el=>getComputedStyle(el).animationName),'none');await page.locator('[data-action=v3-motion]').click();await shot('adventure-desktop');});
 await test('Shop deducts earned stars once, equips outfit and blocks a second purchase',async()=>{await page.locator('[data-action=v3-adventure-tab][data-id=shop]').click();const before=j.economy(snapshot.state).balance;await page.locator('[data-action=v3-buy][data-id=outfit-mage]').click();await wait(()=>j.gameState(snapshot.state).purchases.some(p=>p.id==='outfit-mage'));assert.equal(j.economy(snapshot.state).balance,before-100);assert.equal(j.gameState(snapshot.state).outfit,'mage');assert.equal(await page.locator('[data-action=v3-buy][data-id=outfit-mage]').count(),0);await wait(()=>page.locator('.j-traveler').getAttribute('src').then(s=>s.startsWith('data:image/png')));await shot('shop-desktop');});
 await test('Wardrobe and custom personal reward persist',async()=>{await page.locator('[data-action=v3-adventure-tab][data-id=wardrobe]').click();await page.locator('[name=characterName]').fill('별빛 여행자');await page.locator('#character-form button[type=submit]').click();await wait(()=>j.gameState(snapshot.state).name==='별빛 여행자');await page.locator('[data-action=v3-adventure-tab][data-id=rewards]').click();await page.locator('[name=rewardTitle]').fill('게임 30분');await page.locator('[name=rewardCost]').fill('15');await page.locator('#reward-form button[type=submit]').click();await wait(()=>j.gameState(snapshot.state).customRewards.length===1);const balance=j.economy(snapshot.state).balance;await page.locator('[data-action=v3-redeem]').click();await wait(()=>j.gameState(snapshot.state).redemptions.length===1);assert.equal(j.economy(snapshot.state).balance,balance-15);});
 await test('Quest rewards can be claimed once and exploration updates selected area',async()=>{await page.locator('[data-action=v3-adventure-tab][data-id=quests]').click();const btn=page.locator('[data-action=v3-claim]:not([disabled])').first();assert(await btn.count());const id=await btn.getAttribute('data-id');await btn.click();await wait(()=>j.gameState(snapshot.state).claims.some(c=>c.id===id));await wait(()=>page.locator(`[data-action=v3-claim][data-id="${id}"]`).isDisabled());await page.locator('[data-action=v3-adventure-tab][data-id=journey]').click();await page.locator('[data-action=v3-visit][data-id=grove]').click();await wait(()=>j.gameState(snapshot.state).zone==='grove');});
 await test('Second device reads persisted task completion, costume and reflection (mock storage)',async()=>{await nav('board');await check(taskId);await wait(()=>done(taskId));const second=await makeContext({width:390,height:844}),p=await second.newPage();await p.goto('http://127.0.0.1:4173/');await p.locator('.mobile-nav [data-id=board]').click();assert(await p.locator(`[data-action=complete][data-id="${taskId}"]`).first().getAttribute('aria-label').then(t=>t.includes('취소')));await p.locator('.mobile-nav [data-action=v3-more]').click();await p.locator('#modal [data-action=v3-open-view][data-id=adventure]').click();assert((await p.locator('.j-game-bar').innerText()).includes('별빛 여행자'));await p.screenshot({path:path.join(out,'adventure-mobile.png'),fullPage:true});await second.close();});
 await test('All views fit 1440, 1024, 768, 390 and 320px without horizontal page overflow',async()=>{for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:900});for(const view of ['today','week','month','board','stats','adventure']){if(await page.locator('.sidebar').isVisible())await nav(view);else if(view==='adventure'){await page.locator('.mobile-nav [data-action=v3-more]').click();await page.locator('#modal [data-action=v3-open-view][data-id=adventure]').click();}else await page.locator(`.mobile-nav [data-action=nav][data-id="${view}"]`).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}/${view}`);if(width===390&&['today','stats','month'].includes(view))await shot(view+'-mobile');}}});
 await test('Reduced-motion accessibility stops avatar animations',async()=>{await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.j-traveler-walk').evaluate(e=>getComputedStyle(e).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});});
 await test('No uncaught runtime errors or failed local artwork',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors.filter(e=>!e.includes('net::ERR_ABORTED')),[]);});
 if(process.env.VERIFY_LIVE==='1')await test('Actual Render v3 serves updated modules and interactive desktop/mobile sample',async()=>{const liveCtx=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Seoul'}),p=await liveCtx.newPage();let ready=false;for(let n=0;n<12;n++){await p.goto(process.env.DAYBOARD_LIVE_URL,{waitUntil:'networkidle'});if(await p.evaluate(version=>window.dayboardVersion===version,c.VERSION)){ready=true;break;}await p.waitForTimeout(5000);}assert(ready,'Render has not deployed v3');await p.getByRole('button',{name:'샘플 둘러보기'}).click();await p.locator('.sidebar [data-id=stats]').click();await p.locator('.j-stats').waitFor();await p.screenshot({path:path.join(out,'live-statistics-desktop.png'),fullPage:true});await p.locator('.sidebar [data-id=adventure]').click();await wait(()=>p.locator('.j-traveler').evaluate(e=>e.complete&&e.naturalWidth>0));await p.screenshot({path:path.join(out,'live-adventure-desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,'live-adventure-mobile.png'),fullPage:true});await liveCtx.close();});
}
run().catch(async e=>{console.error(e.stack||e);if(page)try{await shot('failure');fs.writeFileSync(path.join(out,'failure-dom.txt'),await page.locator('body').innerText());fs.writeFileSync(path.join(out,'module-probes.json'),JSON.stringify(await page.evaluate(async()=>{const result={};for(const f of ['core','journey-shell','journey-actions','app'])try{await import('/'+f+'.js');result[f]='loaded';}catch(e){result[f]=e.stack||e.message;}return result;}),null,2));}catch{}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();const report={testedAt:new Date().toISOString(),commit:process.env.GITHUB_SHA,checks,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length,errors,consoleErrors,environment:'GitHub Actions Playwright/Chromium. Browser plugin unavailable; local browser navigation blocked by administrator. Routine/stat/shop UI uses a synthetic mock workspace. Actual Google OAuth/calendar writes are not tested. Live site uses sample mode only.'};fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2));console.log('RESULT',report.passed,'passed,',report.failed,'failed');});
