/* TokTension UI — no analytics, remote APIs, cookies, localStorage or IndexedDB. */
(()=>{'use strict';
const E=window.TokEngine,$=id=>document.getElementById(id);let parsed=null,result=null,shared=null,replySets=null,cardBlob=null,timer=null,toastTimer=null,epoch=0;
const sample=`--------------- 2026년 9월 18일 금요일 ---------------
[나] [오후 6:10] 오늘 드디어 금요일이다 ㅋㅋ 뭐 하고 있어?
[상대] [오후 6:11] 방금 끝났어! 너는?
[나] [오후 6:12] 나도 이제 집 가는 중!
[나] [오후 6:12] 이번 주 진짜 길었어 ㅋㅋㅋ
[상대] [오후 6:14] 맞아 ㅋㅋ 오늘 고생했어
[상대] [오후 6:14] 주말에 뭐 할 거야?
[나] [오후 6:16] 아직 계획 없어! 너는?
[상대] [오후 6:18] 새로 생긴 카페 가보고 싶어
[나] [오후 6:19] 오 어디야? 사진 있어?
[상대] [오후 6:20] 역 앞에 있는 곳! 디저트 맛있대 ㅎㅎ
[나] [오후 6:21] 나 디저트 엄청 좋아하잖아 ㅋㅋㅋ
[나] [오후 6:21] 특히 치즈케이크 있으면 꼭 먹어야 해
[상대] [오후 6:23] 그럼 같이 갈래? 토요일 어때?
[나] [오후 6:24] 좋아! 몇 시가 편해?
[상대] [오후 6:26] 2시쯤 괜찮아?
[나] [오후 6:27] 완전 좋지 ㅋㅋ
[나] [오후 6:27] 내가 먼저 가면 자리 잡아둘게
[상대] [오후 6:28] 고마워 ㅎㅎ 그럼 내일 보자!
[나] [오후 6:29] 응 내일 봐! 오늘 푹 쉬어
[상대] [오후 6:30] 너도! 내일 커피 뭐 마실지 골라놔 ㅋㅋ`;
function text(id,v){$(id).textContent=v;}
function toast(message){clearTimeout(toastTimer);text('toast',message);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function error(message){text('error',message);$('error').hidden=!message;}
function clearInput(){clearTimeout(timer);$('chat').value='';$('fileInput').value='';$('me').replaceChildren();$('other').replaceChildren();$('selectors').hidden=true;$('detected').hidden=true;text('charCount','0 / 500,000자');parsed=null;if(result){result.lastOther='';result.mine.name='나';result.theirs.name='상대';}}
function reset(focus=true){epoch++;clearInput();result=null;shared=null;replySets=null;cardBlob=null;$('entry').hidden=false;$('results').hidden=true;$('analyzeBtn').disabled=false;text('analyzeBtn','우리 대화 분석하기 →');error('');try{history.replaceState(null,'',location.pathname+location.search);}catch{}if(focus){$('chat').focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});}}
function fillSelect(id,names,selected){const options=names.map(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o;});$(id).replaceChildren(...options);if(names.includes(selected))$(id).value=selected;}
function prepare(){
 const oldMe=$('me').value,oldOther=$('other').value;error('');text('charCount',$('chat').value.length.toLocaleString('ko-KR')+' / 500,000자');
 try{parsed=E.parse($('chat').value);const names=parsed.names;if(names.length>200){throw Error('발신자가 200명 넘게 인식됐어요. 내보내기 형식을 확인하거나 대화 기간을 줄여주세요.');}
 $('selectors').hidden=names.length<2;$('detected').hidden=!names.length;
 if(names.length){text('detected',names.length+'명 · '+parsed.messages.length.toLocaleString('ko-KR')+'개 메시지 인식. 내 이름과 상대방을 확인해 주세요.');const me=names.includes(oldMe)?oldMe:(names.find(n=>/^(나|본인|me)$/i.test(n))||names[0]);fillSelect('me',names,me);const other=names.includes(oldOther)&&oldOther!==me?oldOther:names.find(n=>n!==me);fillSelect('other',names,other);}
 return parsed;
 }catch(e){parsed=null;error(e.message);$('selectors').hidden=true;$('detected').hidden=true;return null;}
}
function updateOther(){if($('me').value===$('other').value&&parsed){const next=parsed.names.find(n=>n!==$('me').value);if(next)$('other').value=next;}}
const mood=t=>t>=80?'말풍선에 에너지가 가득해요!':t>=60?'기분 좋은 핑퐁이 오가네요.':t>=40?'우리만의 편안한 속도예요.':'느긋하게 이야기를 이어가요.';
function paintCard(s){const type=E.TYPES[s.k];text('tensionScore',s.t);text('mood',mood(s.t));text('typeEmoji',type.emoji);text('typeName',type.name);text('typeDesc',type.desc);text('signalScore',s.s+' / 100');text('questionScore',s.q+'%');text('activeScore',s.a+' / 100');text('paceScore',s.p===null?'정보 없음':s.p+' / 100');for(const [id,value]of[['signalBar',s.s],['questionBar',s.q],['activeBar',s.a],['paceBar',s.p]])$(id).style.width=(value??0)+'%';}
function renderReplies(tone='light'){if(!replySets)return;document.querySelectorAll('[data-tone]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tone===tone)));const rows=replySets[tone].map(reply=>{const row=document.createElement('div');row.className='reply';const p=document.createElement('p');p.textContent=reply;const b=document.createElement('button');b.type='button';b.textContent='복사';b.setAttribute('aria-label','추천 답장 복사: '+reply);b.addEventListener('click',()=>copy(reply,'답장을 복사했어요.'));row.append(p,b);return row;});$('replies').replaceChildren(...rows);}
function renderReport(r){text('mineLabel','나 · '+r.mine.n+'개');text('otherLabel','상대방 · '+r.theirs.n+'개');$('mineSpeech').style.width=r.share+'%';$('otherSpeech').style.width=(100-r.share)+'%';text('mineSpeech',r.share+'%');text('otherSpeech',(100-r.share)+'%');text('charStats','나 '+r.mine.chars.toLocaleString('ko-KR')+'자 / 상대 '+r.theirs.chars.toLocaleString('ko-KR')+'자');text('gapValue',E.gapText(r.theirGap));$('gapValue').style.fontSize=r.theirGap===null?'18px':'24px';text('gapCount',r.theirGapCount?'유효한 답장 '+r.theirGapCount+'회 기준':'시간이 있는 연속 메시지가 필요해요');text('qValue',r.question+'%');text('qCount',(r.mine.questions+r.theirs.questions)+' / '+r.n+'개 메시지에 물음표');$('warnings').replaceChildren(...r.warnings.map(w=>{const p=document.createElement('p');p.textContent=w;return p;}));$('warnings').hidden=!r.warnings.length;$('extraContent').hidden=true;$('extraContent').replaceChildren();$('extraBtn').setAttribute('aria-expanded','false');text('extraBtn','추가 분석 열기');renderReplies();}
function show(s,r=null){shared=s;cardBlob=null;paintCard(s);$('entry').hidden=true;$('results').hidden=false;$('sharedNotice').hidden=!!r;$('privateReport').hidden=!r;$('tryOwnBtn').hidden=!!r;$('resultLayout').className=r?'result-layout':'shared-layout';text('resultHeading',r?'우리 대화의 발견':'친구가 공유한 대화 카드');text('resultSubtitle',r?r.n.toLocaleString('ko-KR')+'개 메시지를 이 브라우저에서 계산했어요.':'이름 없이, 대화 원문 없이. 결과만 가볍게 즐겨요.');text('resetBtn',r?'원문 지우고 새로 하기':'내 대화 분석하기');$('shareCaption').hidden=!r;for(const b of document.querySelectorAll('.share-buttons'))b.hidden=!r;if(r)renderReport(r);$('results').focus({preventScroll:true});$('results').scrollIntoView({behavior:'smooth',block:'start'});const ticket=epoch;makeCard(s).then(blob=>{if(epoch===ticket&&shared===s)cardBlob=blob;}).catch(()=>toast('카드 생성에 실패했어요. 결과 링크로 공유할 수 있어요.'));}
async function analyze(){clearTimeout(timer);const p=prepare();if(!p)return;if(p.names.length<2){error('두 사람의 이름을 인식하지 못했어요. “나: 내용”, “상대: 내용”처럼 입력해 주세요.');return;}const me=$('me').value,other=$('other').value,ticket=++epoch;$('analyzeBtn').disabled=true;text('analyzeBtn','이 브라우저에서 계산 중…');await new Promise(resolve=>requestAnimationFrame(resolve));try{if(ticket!==epoch)return;result=E.analyze(p,me,other);replySets={light:E.replies(result,'light'),warm:E.replies(result,'warm'),plan:E.replies(result,'plan')};show(E.summary(result),result);}catch(e){error(e.message);}finally{if(ticket===epoch){$('analyzeBtn').disabled=false;text('analyzeBtn','우리 대화 분석하기 →');}}}
function openExtra(){if(!result)return;const opened=$('extraContent').hidden;if(!opened){$('extraContent').hidden=true;$('extraBtn').setAttribute('aria-expanded','false');text('extraBtn','추가 분석 열기');return;}const r=result,mAvg=(r.mine.chars/r.mine.n).toFixed(1),oAvg=(r.theirs.chars/r.theirs.n).toFixed(1);const findings=[`말풍선 길이 — 나는 한 메시지에 평균 ${mAvg}자, 상대방은 ${oAvg}자예요. 메시지 수뿐 아니라 글자 수도 함께 보세요.`, `웃음 표현 — 나는 ${r.mine.laughs}개, 상대방은 ${r.theirs.laughs}개 메시지에서 웃음 표현을 사용했어요. ‘ㅋㅋ’, ‘ㅎㅎ’, 일부 웃음 이모지 등을 세며, 비꼼이나 맥락은 구별하지 못해요.`, `질문 습관 — 나는 ${r.mine.questions}개, 상대방은 ${r.theirs.questions}개 메시지에 물음표를 썼어요. 물음표 없는 질문은 집계되지 않아요.`, `서로의 템포 — 내 답장 간격 중앙값은 ${E.gapText(r.myGap)}, 상대방은 ${E.gapText(r.theirGap)}이에요. 유효 표본은 각각 ${r.myGapCount}회, ${r.theirGapCount}회입니다.`,r.share>60?'다음 대화 팁 — 이번 대화에서는 내 말풍선이 더 많았어요. 상대가 생각을 이어갈 시간을 주거나 “너는 어떻게 생각해?”처럼 열린 질문을 해보세요.':r.share<40?'다음 대화 팁 — 이번 대화에서는 상대방 말풍선이 더 많았어요. 대화를 더 이어가고 싶다면 내 경험 한 가지를 덧붙여도 좋아요. 적은 말수가 곧 무관심은 아니에요.':'다음 대화 팁 — 메시지 개수가 비교적 고르게 오갔어요. 점수를 높이려 애쓰기보다 둘 다 편한 주제와 속도를 찾아보세요.'];$('extraContent').replaceChildren(...findings.map(s=>{const p=document.createElement('p');p.textContent=s;return p;}));$('extraContent').hidden=false;$('extraBtn').setAttribute('aria-expanded','true');text('extraBtn','접어두기');}
function resultURL(){if(!shared)throw Error('먼저 대화를 분석해 주세요.');const u=new URL(location.href);u.search='';u.hash='r='+encodeURIComponent(btoa(JSON.stringify(shared)));return u.href;}
async function copy(value,message='복사했어요.'){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(value);else{const a=document.createElement('textarea');a.value=value;a.style.position='fixed';a.style.opacity='0';document.body.append(a);a.focus();a.select();const ok=document.execCommand('copy');a.remove();if(!ok)throw Error('clipboard');}toast(message);}catch{openInfo('복사할 내용',value+'\n\n이 브라우저에서 자동 복사가 제한돼 있어요. 위 내용을 직접 선택해 복사해 주세요.');}}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function wrapText(ctx,value,x,y,width,lineHeight,maxLines=3){let line='',lines=0;for(const char of Array.from(value)){if(ctx.measureText(line+char).width>width&&line){ctx.fillText(line,x,y);y+=lineHeight;line='';if(++lines>=maxLines)return y;}line+=char;}if(line)ctx.fillText(line,x,y);return y+lineHeight;}
async function makeCard(s){if(document.fonts?.ready)await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d');if(!c)throw Error('canvas');const font='"Apple SD Gothic Neo", "Malgun Gothic", "Noto Sans CJK KR", "Noto Sans KR", sans-serif';c.fillStyle='#ffffff';c.fillRect(0,0,1080,1350);c.fillStyle='#d9f77c';rounded(c,24,24,1032,1302,45);c.fillStyle='#212924';c.font='800 38px '+font;c.fillText('톡텐션',80,107);c.font='600 20px '+font;c.textAlign='right';c.fillText('JUST FOR FUN.',998,103);c.textAlign='left';c.font='500 29px '+font;c.fillText('우리 대화의 텐션',80,178);c.font='850 196px '+font;c.fillText(String(s.t),71,363);const numberWidth=c.measureText(String(s.t)).width;c.font='600 45px '+font;c.fillText('/ 100',91+numberWidth,359);c.font='700 31px '+font;c.fillText(mood(s.t),83,414);c.strokeStyle='#acc959';c.lineWidth=2;c.beginPath();c.moveTo(80,452);c.lineTo(998,452);c.stroke();const type=E.TYPES[s.k];c.font='52px '+font;c.fillText(type.emoji,78,535);c.font='800 57px '+font;c.fillText(type.name,158,533);c.fillStyle='#415b31';c.font='400 26px '+font;wrapText(c,type.desc,82,594,906,39,3);const metrics=[['관심 신호 · 놀이 지수',s.s,' / 100'],['상대방 질문 메시지',s.q,'%'],['상대방 대화 적극성',s.a,' / 100'],['상대방 답장 리듬',s.p,' / 100']];metrics.forEach(([label,value,unit],i)=>{const y=737+i*100;c.fillStyle='#212924';c.font='500 26px '+font;c.fillText(label,82,y);c.font='750 27px '+font;c.textAlign='right';c.fillText(value===null?'정보 없음':value+unit,996,y);c.textAlign='left';c.fillStyle='#bdd772';rounded(c,82,y+18,914,12,6);if(value){c.fillStyle='#212924';rounded(c,82,y+18,Math.max(12,914*value/100),12,6);}});c.strokeStyle='#acc959';c.beginPath();c.moveTo(80,1125);c.lineTo(998,1125);c.stroke();c.fillStyle='#405730';c.font='400 23px '+font;c.fillText('재미로 보는 대화 놀이 · 실제 호감이나 심리 상태를 뜻하지 않아요.',82,1175);c.fillText('이름·대화 원문은 이 카드에 포함되지 않아요.',82,1217);c.font='600 21px '+font;c.fillText(location.hostname==='localhost'||location.hostname==='127.0.0.1'?'톡텐션 by 501 Studio':location.hostname,82,1271);return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('png')),'image/png'));}
async function saveImage(){if(!shared)return;const s=shared,ticket=epoch;try{const blob=cardBlob||await makeCard(s);if(ticket!==epoch)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='toktension-result.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('PNG 저장을 요청했어요. 브라우저의 다운로드 항목을 확인해 주세요.');}catch{toast('이미지 저장이 제한돼 있어요. 결과 링크를 복사해 주세요.');}}
async function shareResult(){if(!shared)return;const url=resultURL(),title='내 대화 유형은 '+E.TYPES[shared.k].name+'!';try{if(cardBlob&&navigator.canShare){const file=new File([cardBlob],'toktension-result.png',{type:'image/png'});if(navigator.canShare({files:[file]})){await navigator.share({files:[file],title,text:title+' · 톡텐션 '+shared.t+'점\n'+url});return;}}if(navigator.share){await navigator.share({title,text:'톡텐션 '+shared.t+'점 · 재미로 보는 대화 놀이',url});return;}await copy(url,'이 기기는 공유 메뉴를 지원하지 않아 결과 링크를 복사했어요.');}catch(e){if(e.name!=='AbortError')await copy(url,'이미지 공유 대신 결과 링크를 복사했어요.');}}
function openInfo(title,body){text('dialogTitle',title);const p=document.createElement('p');p.textContent=body;$('dialogBody').replaceChildren(p);$('infoDialog').showModal();}
function restoreShared(){if(!location.hash.startsWith('#r='))return false;try{const token=location.hash.slice(3);if(token.length>1000)throw Error('length');const s=E.readSummary(JSON.parse(atob(decodeURIComponent(token))));if(!s)throw Error('schema');epoch++;clearInput();result=null;replySets=null;show(s);return true;}catch{toast('공유 링크가 올바르지 않아요. 새로 대화를 분석해 주세요.');return false;}}
$('chat').addEventListener('input',()=>{epoch++;clearTimeout(timer);text('charCount',$('chat').value.length.toLocaleString('ko-KR')+' / 500,000자');timer=setTimeout(prepare,250);});
$('sampleBtn').addEventListener('click',()=>{epoch++;$('chat').value=sample;prepare();toast('실제 대화가 아닌, 체험용 예시를 넣었어요.');});
$('me').addEventListener('change',updateOther);$('analyzeBtn').addEventListener('click',analyze);$('uploadBtn').addEventListener('click',()=>$('fileInput').click());
$('fileInput').addEventListener('change',async()=>{const file=$('fileInput').files?.[0];if(!file)return;const ticket=++epoch;try{if(!/\.txt$/i.test(file.name))throw Error('.txt 파일을 선택해 주세요.');if(file.size>2000000)throw Error('2 MB 이하의 텍스트 파일을 사용해 주세요.');const bytes=await file.arrayBuffer();if(ticket!==epoch)return;const head=new Uint8Array(bytes);let value;if(head[0]===255&&head[1]===254)value=new TextDecoder('utf-16le',{fatal:true}).decode(bytes);else if(head[0]===254&&head[1]===255)value=new TextDecoder('utf-16be',{fatal:true}).decode(bytes);else{try{value=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{value=new TextDecoder('euc-kr',{fatal:true}).decode(bytes);}}if(value.length>E.MAX_CHARS)throw Error('50만 자 이하의 대화를 사용해 주세요.');$('chat').value=value;prepare();toast('기기에서 파일을 읽었어요. 이름과 메시지 수를 확인해 주세요.');}catch(e){error(e instanceof TypeError?'텍스트 인코딩을 읽지 못했어요. UTF-8 .txt로 저장하거나 복사해서 붙여 넣어주세요.':e.message);}finally{$('fileInput').value='';}});
$('resetBtn').addEventListener('click',()=>reset());$('tryOwnBtn').addEventListener('click',()=>reset());$('clearBtn').addEventListener('click',()=>{reset();toast('대화 입력과 분석 상태를 지웠어요. 이미 저장·공유한 결과는 삭제되지 않아요.');});
$('extraBtn').addEventListener('click',openExtra);document.querySelectorAll('[data-tone]').forEach(b=>b.addEventListener('click',()=>renderReplies(b.dataset.tone)));
$('saveBtn').addEventListener('click',saveImage);$('shareBtn').addEventListener('click',shareResult);$('linkBtn').addEventListener('click',()=>{if(shared)copy(resultURL(),'이름·원문 없는 결과 링크를 복사했어요.');});$('xBtn').addEventListener('click',()=>{if(!shared)return;const url=new URL('https://twitter.com/intent/tweet');url.searchParams.set('text','내 대화 유형은 '+E.TYPES[shared.k].name+'! 톡텐션 '+shared.t+'점 🎈 #톡텐션\n재미로 보는 대화 놀이');url.searchParams.set('url',resultURL());window.open(url.href,'_blank','noopener,noreferrer');});
$('privacyBtn').addEventListener('click',()=>openInfo('개인정보 안내','현재 버전: 1.0.0 · 2026년 9월 18일\n\n1. 입력한 대화·발신자명·시간은 브라우저 메모리에서만 처리합니다. 별도 서버, 외부 AI, 쿠키, 로컬 저장소 또는 데이터베이스로 전송·저장하지 않습니다.\n\n2. 웹사이트 파일을 제공하는 호스팅 업체(Render)는 접속 과정에서 IP 주소, 브라우저 정보 등 통상적인 접속 기록을 처리할 수 있습니다. 대화 입력이나 결과 링크의 해시 부분을 분석 API로 보내지 않습니다.\n\n3. 공유 이미지와 링크에는 임의의 놀이 점수와 대화 유형만 담깁니다. 사용자가 공유 버튼을 눌러 외부 앱으로 전달한 결과는 그 앱의 정책에 따라 처리됩니다. 이미 공유한 결과는 이 사이트에서 회수할 수 없습니다.\n\n4. 현재 광고·분석 추적 스크립트는 사용하지 않습니다. 실제 광고 도입 시에는 개인정보 안내, 동의 방식과 기술적 분리 정책을 먼저 갱신해야 합니다.\n\n5. 원문 지우기 버튼 또는 새로고침으로 앱의 입력을 초기화할 수 있습니다. 브라우저 확장 프로그램·기기의 클립보드·내보낸 파일·직접 저장한 이미지까지 삭제하지는 않습니다. 참여자의 동의를 받고, 실명·연락처와 민감한 정보는 사용 전에 제거해 주세요.'));
$('termsBtn').addEventListener('click',()=>openInfo('이용 안내','톡텐션은 대화의 표면적 통계를 이용한 엔터테인먼트 도구입니다. 실제 호감도, 성격, 정신건강, 관계 가능성 또는 상대방의 의도를 판단할 수 없습니다.\n\n분석한 대화는 전체 관계의 일부일 뿐입니다. 출력에 근거해 상대를 비난·차별하거나 중요한 결정을 내리지 마세요. 입력한 자료를 사용할 권한과 참여자의 동의를 확인해 주세요.\n\n추천 답장은 키워드에 맞춘 미리 작성된 문장입니다. 상대방의 상황과 말투에 맞게 검토하고 수정하세요.\n\n현재 모든 기능은 무료이며 실제 광고 송출과 광고 수익 정산은 연결되지 않았습니다. 카카오의 공식 서비스가 아니며 카카오와 제휴되어 있지 않습니다.'));
$('closeDialog').addEventListener('click',()=>$('infoDialog').close());$('infoDialog').addEventListener('click',e=>{if(e.target===$('infoDialog')){const r=$('infoDialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('infoDialog').close();}});
window.addEventListener('hashchange',()=>{if(!restoreShared()&&!location.hash)reset(false);});
window.addEventListener('pagehide',()=>{epoch++;clearInput();});restoreShared();
})();
