import {readFile} from 'node:fs/promises';
const failures=[];const read=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),'utf8'));
try{const c=await read('../data/coverage.json');if(!c.allPacksComplete)failures.push('Vocabulary coverage incomplete');for(const [l,v]of Object.entries(c.levels))if(v.english!==0)failures.push(l+': English meanings remain');}catch{failures.push('Vocabulary evidence missing');}
try{const a=await read('../editorial/audit.json');if(!a.semanticReviewComplete)failures.push(`Semantic review incomplete: ${a.remainingSemanticReview}/${a.total} still pending`);}catch{failures.push('Editorial audit missing');}
// Device TTS availability/quality is covered by the mandatory physicalDeviceAudio approval below.
const required=['physicalDeviceInk','physicalDeviceAudio','offlineRestore','accessibility','contentEditorialReview','privacyAndDataSafety','contentRating','storeListing','signedBundle','playAppSigning','closedTesting','legalDocsPublished','billingSandbox','consentAndAdFree','rtdnAndRefunds','accountDeletion'];
try{const a=await read('../../release-approval.json');for(const k of required)if(a[k]!==true)failures.push('Unapproved: '+k);}catch{failures.push('Release approval not recorded');}
try{const l=await read('../release/legal.json');for(const k of ['developerLegalName','supportEmail','publicPrivacyUrl','publicDataDeletionUrl','targetAudience'])if(!l[k]||String(l[k]).includes('REQUIRED'))failures.push('Legal field not confirmed: '+k);}catch{failures.push('Actual legal metadata not supplied');}
try{const ads=await read('../release/admob-production.json');for(const [env,key]of [['ADMOB_APP_ID','appId'],['ADMOB_BANNER_ID','bannerId'],['ADMOB_INTERSTITIAL_ID','interstitialId']]){const id=process.env[env]||ads[key];if(!id||id.includes('3940256099942544'))failures.push('Production configuration missing: '+env);}if(ads.accountReviewStatus!=='approved')failures.push('AdMob account/app approval pending');}catch{failures.push('Production AdMob configuration missing');}
for(const k of ['KOTOBA_VERIFICATION_URL','KOTOBA_ENTITLEMENT_PUBLIC_KEY','GOOGLE_OAUTH_CLIENT_ID','PLAY_INTEGRITY_CLOUD_PROJECT_NUMBER'])if(!process.env[k])failures.push('Production configuration missing: '+k);
if(failures.length){console.error('RELEASE BLOCKED\n'+failures.map(f=>' - '+f).join('\n'));process.exitCode=1;}else console.log('Recorded gates passed; account declarations still require owner review.');
