import {activity,economy,day,gameState,CATALOG} from './journey-domain.js';
import {REALMS,CHAPTERS,TITLES,MISSIONS,TALENTS,ROLES,ENDINGS,CHRONICLE_CATALOG} from './chronicle-content.js';
export const DEFAULT_CHRONICLE=Object.freeze({version:1,chapters:[],missions:[],titles:[],talents:[],role:'seeker',camp:'harbor',equippedTitle:'none'});
export function chronicleState(state){const c=state.settings?.chronicle;return {...DEFAULT_CHRONICLE,...c,chapters:c?.chapters||[],missions:c?.missions||[],titles:c?.titles||[],talents:c?.talents||[]};}
export function journeyProgress(state){const events=activity(state),c=chronicleState(state),minutes=events.reduce((n,e)=>n+Math.max(0,Number(e.minutes)||0),0),reflections=Object.entries(state.settings?.reflections||{}).filter(([d,r])=>d<=day()&&String((r.win||'')+(r.friction||'')+(r.next||'')).trim()).length;
 const axes={courage:0,insight:0,bond:0};for(const record of c.chapters){const choice=CHAPTERS.find(x=>x.id===record.id)?.choices.find(x=>x.id===record.choice);if(choice)axes[choice.axis]++;}
 const dominant=Object.keys(axes).reduce((best,key)=>axes[key]>axes[best]?key:best,'insight'),chapterCount=c.chapters.length,next=CHAPTERS[chapterCount]||null;
 return {c,events,minutes,hours:minutes/60,completed:events.length,routine:events.filter(e=>e.kind==='routine').length,days:new Set(events.map(e=>e.day)).size,reflections,collection:gameState(state).purchases.length,chapterCount,next,axes,dominant,ending:ENDINGS[dominant],points:Math.floor(chapterCount/4),spentPoints:c.talents.length};
}
export function realmAccess(state,realm,p=journeyProgress(state)){const n=REALMS.findIndex(r=>r.id===(typeof realm==='string'?realm:realm.id));if(n<0)return false;return p.hours>=REALMS[n].hour&&p.chapterCount>=n*8;}
export function chapterAccess(state,chapter,p=journeyProgress(state)){return !!chapter&&p.hours>=chapter.hours&&p.chapterCount>=chapter.index-1;}
export function missionStatus(state,m,p=journeyProgress(state)){return {claimed:p.c.missions.some(x=>x.id===m.id),ready:p.hours>=m.hours&&p.chapterCount>=m.chapter&&p[m.metric]>=m.target,count:p[m.metric]||0,target:m.target};}
export function titleStatus(state,t,p=journeyProgress(state)){const count=t.kind==='chapter'?p.chapterCount:t.kind==='missions'?p.c.missions.filter(x=>x.id.startsWith(t.realm+'-')).length:p[t.kind]||0;return {count,target:t.target,ready:count>=t.target,owned:p.c.titles.some(x=>x.id===t.id),equipped:p.c.equippedTitle===t.id};}
export function titleLabel(state,p=journeyProgress(state)){return TITLES.find(t=>t.id===p.c.equippedTitle)?.name||CATALOG.find(i=>i.slot==='title'&&i.value===gameState(state).title)?.name||'한 걸음씩, 나만의 속도로';}
export function shopStatus(state,i,p=journeyProgress(state),e=economy(state)){const owned=e.game.purchases.some(x=>x.id===i.id),equipped=e.game[i.slot]===i.value;const unlocked=e.level>=i.level&&(!i.realm||p.hours>=i.hours&&p.chapterCount>=i.chapter);return {owned,equipped,unlocked,affordable:e.balance>=i.price,reason:!unlocked?(i.realm&&p.chapterCount<i.chapter?`이전 대륙 이야기 ${i.chapter}장 완료 필요`:i.realm&&p.hours<i.hours?`누적 예상 ${i.hours}시간 필요`:`Lv. ${i.level} 필요`):e.balance<i.price?'별조각 부족':''};}
export function mementos(state,p=journeyProgress(state)){return [...REALMS.map((r,n)=>({id:'memory-'+r.id,realm:r.id,title:r.relic,body:r.ending,owned:p.chapterCount>=(n+1)*8,kind:'지역 결말'})),...MISSIONS.map(m=>({id:m.id,realm:m.realm,title:m.memento,body:`${m.name}을 통해 남긴 기록. ${REALMS.find(r=>r.id===m.realm).theme}을 다시 살펴봅니다.`,owned:p.c.missions.some(x=>x.id===m.id),kind:'지역 의뢰'}))];}
export function chapterEnding(chapter,choiceId,state){const choice=chapter.choices.find(x=>x.id===choiceId);if(!choice)throw new Error('선택지를 확인하세요.');const p=journeyProgress(state),realm=REALMS.find(r=>r.id===chapter.realm);return {choice,text:choice.outcome,regional:chapter.local===8?realm.ending:null,final:chapter.index===CHAPTERS.length?p.ending:null};}
export function chronicleOperation(state,action,id,value){const p=journeyProgress(state),c=structuredClone(p.c),at=new Date().toISOString();
 if(action==='chapter'){const ch=CHAPTERS.find(x=>x.id===id);if(!ch||!ch.choices.some(x=>x.id===value))throw new Error('이야기 또는 선택지를 찾을 수 없습니다.');const existing=c.chapters.find(x=>x.id===id);if(existing){if(existing.choice===value)return [];throw new Error('이미 남긴 선택은 보존됩니다. 다시 읽기에서는 기록을 바꾸지 않습니다.');}if(ch.index!==c.chapters.length+1||!chapterAccess(state,ch,p))throw new Error('앞의 이야기와 누적 예상시간 조건을 먼저 채워 주세요.');c.chapters.push({id,choice:value,at});}
 else if(action==='mission'){const m=MISSIONS.find(x=>x.id===id);if(!m)throw new Error('의뢰가 없습니다.');const s=missionStatus(state,m,p);if(s.claimed)return [];if(!s.ready)throw new Error('이야기 진행과 실행 기록 조건이 아직 부족합니다.');c.missions.push({id,at});}
 else if(action==='title'){if(id==='none')c.equippedTitle='none';else{const t=TITLES.find(x=>x.id===id);if(!t)throw new Error('칭호가 없습니다.');const s=titleStatus(state,t,p);if(!s.owned&&!s.ready)throw new Error('칭호 조건을 아직 달성하지 않았습니다.');if(!s.owned)c.titles.push({id,at});c.equippedTitle=id;}}
 else if(action==='talent'){const t=TALENTS.find(x=>x.id===id);if(!t)throw new Error('성장 노드가 없습니다.');if(c.talents.includes(id))return [];if(c.talents.length>=p.points)throw new Error('이야기 4장마다 얻는 숙련 포인트가 필요합니다.');if(t.tier>1&&!c.talents.includes(`${t.role}-${t.tier-1}`))throw new Error('앞 단계부터 습득하세요.');c.talents.push(id);}
 else if(action==='role'){if(!ROLES.some(x=>x.id===id))throw new Error('역할을 확인하세요.');c.role=id;}
 else if(action==='camp'){if(!realmAccess(state,id,p))throw new Error('아직 도착할 수 없는 지역입니다.');c.camp=id;}
 else throw new Error('지원하지 않는 모험 동작입니다.');
 return [{collection:'settings',action:'merge',data:{chronicle:c}}];
}
// Used by local/demo writes and unit tests. PostgreSQL independently enforces persistence rules.
export function assertChronicleTransition(before,after){const c=chronicleState(after),old=chronicleState(before),p=journeyProgress(after);if(c.version!==1)throw new Error('CHRONICLE_VERSION');for(const [field,max] of [['chapters',96],['missions',36],['titles',60]]){if(!Array.isArray(c[field])||c[field].length>max||new Set(c[field].map(x=>x.id)).size!==c[field].length)throw new Error('CHRONICLE_RECORDS');for(const record of old[field])if(!c[field].some(x=>JSON.stringify(x)===JSON.stringify(record)))throw new Error('CHRONICLE_HISTORY_IMMUTABLE');for(const record of c[field])if(!record?.id||!Number.isFinite(Date.parse(record.at))||Date.parse(record.at)>Date.now()+60000)throw new Error('CHRONICLE_TIME');}
 for(let n=0;n<c.chapters.length;n++){const r=c.chapters[n],ch=CHAPTERS[n];if(ch.id!==r.id||!['a','b'].includes(r.choice))throw new Error('CHRONICLE_ORDER');if(n>=old.chapters.length&&p.hours<ch.hours)throw new Error('CHRONICLE_LOCKED');}
 for(const r of c.missions){const m=MISSIONS.find(x=>x.id===r.id);if(!m||!old.missions.some(x=>x.id===r.id)&&!missionStatus(after,m,p).ready)throw new Error('CHRONICLE_MISSION_LOCKED');}
 for(const r of c.titles){const t=TITLES.find(x=>x.id===r.id);if(!t||!old.titles.some(x=>x.id===r.id)&&!titleStatus(after,t,p).ready)throw new Error('CHRONICLE_TITLE_LOCKED');}
 if(c.equippedTitle!=='none'&&!c.titles.some(x=>x.id===c.equippedTitle))throw new Error('CHRONICLE_TITLE_OWNERSHIP');
 if(!ROLES.some(x=>x.id===c.role))throw new Error('CHRONICLE_ROLE');if(!REALMS.some(x=>x.id===c.camp)||c.camp!==old.camp&&!realmAccess(after,c.camp,p))throw new Error('CHRONICLE_CAMP_LOCKED');
 if(!Array.isArray(c.talents)||c.talents.length>18||new Set(c.talents).size!==c.talents.length||c.talents.length>Math.floor(c.chapters.length/4)||old.talents.some(x=>!c.talents.includes(x)))throw new Error('CHRONICLE_TALENT_POINTS');
 for(const id of c.talents){const t=TALENTS.find(x=>x.id===id);if(!t||t.tier>1&&!c.talents.includes(`${t.role}-${t.tier-1}`))throw new Error('CHRONICLE_TALENT_ORDER');}
 for(const item of CHRONICLE_CATALOG){if(gameState(after).purchases.some(x=>x.id===item.id)&&!gameState(before).purchases.some(x=>x.id===item.id)&&(p.hours<item.hours||p.chapterCount<item.chapter))throw new Error('CHRONICLE_SHOP_LOCKED');}
 return true;
}
