import { esc, dateKey, timeKey, at, addDays, duration, deadlineText, leaves, overlaps } from './core.js';
import { dashboardTasks, projectSummary, deadlineRisks, remainingMinutes } from './dashboard-domain.js';
import { hasGPTOrder } from './task-order.js';
const mono = value => `<span class="dash-number">${value}</span>`;
const compactTime = n => n >= 60 ? `${Math.floor(n / 60)}h${n % 60 ? ` ${n % 60}m` : ''}` : `${n}m`;
function miniButton(action, label, symbol, id, extra = '') {
  return `<button type="button" class="iconbutton dash-icon" data-action="${action}" data-id="${esc(id)}" aria-label="${esc(label)}" title="${esc(label)}" ${extra}>${symbol}</button>`;
}
function pinIcon() { return '<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M8 3h8l-1 7 4 4v2H5v-2l4-4-1-7Zm4 13v6"/></svg>'; }
function projectRows(ctx, ui) {
  const { state, date, dashboard } = ctx, { btn, progress, icon } = ui;
  const projects = state.items.filter(i => i.kind === 'project' && i.status !== 'done').sort((a,b) => (a.deadline || '9999').localeCompare(b.deadline || '9999') || a.title.localeCompare(b.title));
  return `<section class="panel dash-panel dash-projects" aria-labelledby="dash-projects-title"><div class="panel-head"><div><h2 id="dash-projects-title">진행 프로젝트 ${mono(projects.length)}</h2><p class="dash-subtitle">목표에서 다음 행동까지</p></div>${btn('add-project','추가',{ico:'plus',cls:'ghost'})}</div><div class="dash-project-list">${projects.slice(0,dashboard.allProjects ? projects.length : 5).map(p => {
    const s = projectSummary(p,state,date);
    return `<article class="dash-project"><div class="dash-project-top"><button class="title-button" data-action="edit-item" data-id="${esc(p.id)}">${esc(p.title)}</button><span class="dash-due-date">${esc(deadlineText(p.deadline))}</span></div><div class="dash-progress-line">${progress(s.progress)}<span>${s.progress}%</span></div><div class="dash-next"><span>다음</span>${s.next ? `<button data-action="edit-item" data-id="${esc(s.next.id)}">${esc(s.next.title)}</button>` : `<button data-action="add-task-to-project" data-id="${esc(p.id)}">${s.total ? '모든 업무 완료' : '첫 업무 추가하기'}</button>`}</div><div class="dash-project-foot">남은 실행 업무 ${s.remaining}개${s.remaining ? ` · ${duration(s.minutes)}` : ''}</div></article>`;
  }).join('') || `<div class="dash-empty">${icon('folder')}<strong>목표를 프로젝트로 묶어 보세요.</strong><p>진행률과 다음 할 일을 함께 보여드립니다.</p>${btn('add-project','프로젝트 만들기')}</div>`}</div><div class="dash-panel-foot">${projects.length > 5 ? btn('toggle-projects',dashboard.allProjects ? '5개만 보기' : `프로젝트 ${projects.length}개 모두 보기`,{cls:'ghost'}) : btn('nav','프로젝트 상세',{id:'projects',cls:'ghost'})}</div></section>`;
}
function deadlinesPanel(ctx, ui) {
  const { state, date, dashboard } = ctx, { btn, icon } = ui;
  const deadlines = deadlineRisks(state,date);
  return `<section class="panel dash-panel dash-deadlines" aria-labelledby="dash-deadlines-title"><div class="panel-head"><div><h2 id="dash-deadlines-title">이번 주 마감 ${mono(deadlines.length)}</h2><p class="dash-subtitle">위험한 마감 먼저 · 지난 마감 포함</p></div>${btn('nav','월간',{id:'month',ico:'calendar',cls:'ghost'})}</div><div class="dash-deadline-list">${deadlines.slice(0,dashboard.allDeadlines ? deadlines.length : 5).map(r => `<div class="dash-deadline"><div class="dash-deadline-date"><strong>${+r.item.deadline.slice(5,7)}.${+r.item.deadline.slice(8)}</strong><span>${esc(deadlineText(r.item.deadline))}</span></div><div class="grow"><button class="title-button" data-action="edit-item" data-id="${esc(r.item.id)}">${esc(r.item.title)}</button><div class="meta">${r.unknown ? '하위 업무량 미정' : `${duration(r.remaining)} 남음`}${r.item.kind === 'project' ? ' · 프로젝트' : ''}</div></div><span class="risk-indicator ${r.level}" title="해당 마감까지 전체 업무 ${duration(r.demand)} 필요 / 가용 ${duration(r.capacity)}. 예상시간과 근무시간에 따른 추정입니다."><span></span>${r.unknown && !r.overdue ? '확인' : r.label}</span></div>`).join('') || `<div class="dash-empty">${icon('calendar')}<strong>이번 주에 등록된 마감이 없습니다.</strong><p>업무에 마감일을 지정하면 여기에 표시됩니다.</p></div>`}</div><div class="dash-panel-foot"><p class="dash-footnote">업무량·가용시간 기준 추정입니다. 전체 업무를 합산해 판단하며, 상위·하위 업무 시간은 중복 합산하지 않습니다.</p>${deadlines.length > 5 ? btn('toggle-deadlines',dashboard.allDeadlines ? '5개만 보기' : `마감 ${deadlines.length}개 모두 보기`,{cls:'ghost'}) : ''}</div></section>`;
}
function taskPanel(ctx, ui) {
  const { state, date, dashboard } = ctx, { btn, check, icon } = ui;
  const list = dashboardTasks(state,date,dashboard.taskFilter), visible = list.slice(0,dashboard.allTasks ? list.length : 8);
  const hasManual = Array.isArray(state.settings.taskOrder) && state.settings.taskOrder.length > 0;
  const orderLabel = hasManual ? '내 순서' : list.some(i => hasGPTOrder(i)) ? '저장된 GPT 추천' : '기본 추천';
  return `<section class="panel dash-panel dash-tasks" aria-labelledby="dash-tasks-title"><div class="panel-head"><div><h2 id="dash-tasks-title">오늘 · 미배치 업무 ${mono(list.length)}</h2><p class="dash-subtitle">${orderLabel} · 핀은 업무 순서만 고정</p></div>${btn('plan','시간 배치',{ico:'clock',cls:'ghost'})}</div><div class="dash-task-toolbar"><div class="dash-filters" aria-label="업무 필터">${[['all','전체'],['today','오늘'],['unplaced','미배치']].map(([id,label]) => `<button type="button" data-action="task-filter" data-id="${id}" aria-pressed="${dashboard.taskFilter === id}" class="${dashboard.taskFilter === id ? 'selected' : ''}">${label}</button>`).join('')}</div><details class="dash-order-menu"><summary>정렬 ${icon('chevron')}</summary><div>${btn('restore-order','추천순 복원')}${btn('gpt-order','GPT로 순서 추천')}</div></details></div><ol class="dash-task-list">${visible.map((i,n) => `<li class="dash-task ${i.pinned ? 'is-pinned' : ''}" draggable="${!i.pinned}" data-drag-type="item" data-order-id="${esc(i.id)}" data-id="${esc(i.id)}"><span class="dash-task-rank" title="드래그로 순서 이동">${String(n+1).padStart(2,'0')}</span>${check(i)}<div class="grow"><button class="title-button" data-action="edit-item" data-id="${esc(i.id)}">${esc(i.title)}</button><div class="meta"><span>${duration(remainingMinutes(i))}${i.progress ? ' 남음' : ''}</span>${i.deadline ? `<span>${esc(deadlineText(i.deadline))}</span>` : '<span>마감 미정</span>'}${i.pinned ? '<span class="pin-label">고정</span>' : ''}</div></div><div class="dash-task-actions">${miniButton('pin-task',i.pinned ? '순서 고정 해제' : '이 순서에 핀 고정',pinIcon(),i.id,`aria-pressed="${!!i.pinned}"`)}${miniButton('task-tools','업무 이동 메뉴',icon('more'),i.id,`aria-expanded="${dashboard.taskTools === i.id}"`)}</div>${dashboard.taskTools === i.id ? `<div class="dash-task-tools">${btn('task-up','위로',{id:i.id,ico:'up'})}${btn('task-down','아래로',{id:i.id,ico:'down'})}${btn('schedule-item','시간 지정',{id:i.id,ico:'clock'})}</div>` : ''}</li>`).join('') || `<li class="dash-empty">${icon('check')}<strong>${dashboard.taskFilter === 'unplaced' ? '시간 미정 업무가 없습니다.' : '표시할 업무가 없습니다.'}</strong><p>제목만 입력해 첫 업무를 추가하세요.</p></li>`}</ol><div class="dash-panel-foot">${list.length > 8 ? btn('toggle-tasks',dashboard.allTasks ? '8개만 보기' : `업무 ${list.length}개 모두 보기`,{cls:'ghost'}) : btn('nav','전체 업무 보드',{id:'board',cls:'ghost'})}<span class="dash-footnote">PC 드래그 · 모바일 이동 메뉴</span></div></section>`;
}
function agendaPanel(ctx, ui, renderTimeline) {
  const { state, date, dashboard } = ctx, { btn, icon } = ui;
  if (dashboard.timeline === 'detail') return `<div class="dash-agenda dash-agenda-detail">${renderTimeline(ctx)}</div>`;
  const from = +at(date), end = +at(addDays(date,1));
  const list = state.blocks.filter(b => +new Date(b.start) < end && +new Date(b.end) > from).sort((a,b) => Number(!!b.allDay)-Number(!!a.allDay) || +new Date(a.start)-+new Date(b.start));
  const total = list.filter(b => !b.allDay).reduce((n,b) => n + Math.max(0,Math.round((Math.min(end,+new Date(b.end))-Math.max(from,+new Date(b.start)))/60000)),0);
  return `<section class="panel dash-panel dash-agenda" aria-labelledby="dash-agenda-title"><div class="panel-head"><div><h2 id="dash-agenda-title">오늘 시간표 ${mono(list.length)}</h2><p class="dash-subtitle">${duration(total)} 배치 · 모든 일정 표시</p></div>${btn('new-block','추가',{ico:'plus',cls:'ghost'})}</div><div class="dash-agenda-list">${list.map(b => {
    const current = +new Date(b.start) <= Date.now() && +new Date(b.end) > Date.now(), done = state.items.find(i=>i.id===b.taskId)?.status === 'done';
    const conflict = list.some(other => other.id !== b.id && overlaps(b,other));
    return `<button class="dash-event ${current ? 'is-current' : ''} ${done ? 'is-finished' : ''}" draggable="${!b.locked}" data-drag-type="block" data-action="edit-block" data-id="${esc(b.id)}"><span class="dash-event-time">${b.allDay ? '<strong>종일</strong>' : `<strong>${dateKey(b.start)<date ? '이전 날' : timeKey(b.start)}</strong><span>${dateKey(b.end)>date ? '다음 날' : timeKey(b.end)}</span>`}</span><span class="dash-event-mark ${b.source==='google'?'external':''}"></span><span class="grow"><span class="dash-event-title">${esc(b.title)}</span><span class="meta">${b.source === 'google' ? 'Google Calendar' : b.allDay ? '종일 일정' : compactTime(Math.round((Math.min(end,+new Date(b.end))-Math.max(from,+new Date(b.start)))/60000))}${b.locked ? ' · 시간 고정' : ''}${conflict ? ' · 겹침' : ''}${done ? ' · 완료' : ''}</span></span>${current ? '<span class="now-tag">지금</span>' : icon('chevron')}</button>`;
  }).join('') || `<div class="dash-empty">${icon('clock')}<strong>아직 정해진 일정이 없습니다.</strong><p>할 일을 시간에 배치하거나 약속을 추가하세요.</p>${btn('new-block','일정 추가')}</div>`}</div><div class="dash-panel-foot">${btn('timeline-detail','시간표 자세히 보기',{ico:'week',cls:'ghost'})}${btn('replan','밀린 일정 재배치',{ico:'refresh',cls:'ghost'})}</div></section>`;
}
function quickInput(ctx, ui) {
  const { btn, icon } = ui;
  const projects = ctx.state.items.filter(i=>i.kind === 'project' && i.status !== 'done');
  return `<section class="dash-quick" aria-label="빠른 업무 입력"><form id="quick-form" class="quick-input"><div class="input-row"><input name="title" placeholder="할 일 추가 · 제목만 적어도 충분해요" maxlength="200" required aria-label="빠른 할 일 추가"><button class="iconbutton" type="submit" aria-label="할 일 저장">${icon('plus')}</button></div><details id="quick-options"><summary>마감 · 시간 · 프로젝트 선택</summary><div class="quick-fields"><label>마감일<input type="date" name="deadline" aria-label="빠른 업무 마감일"></label><label>예상시간 · 분<input type="number" name="estimatedMinutes" value="30" min="5" max="4800" step="5" aria-label="빠른 업무 예상시간"></label><label>프로젝트<select name="parentId" aria-label="빠른 업무 프로젝트"><option value="">독립 업무</option>${projects.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join('')}</select></label><label>중요도<select name="importance" aria-label="빠른 업무 중요도"><option value="1">낮음</option><option value="2" selected>보통</option><option value="3">높음</option></select></label></div></details></form><div class="dash-quick-actions">${btn('natural-input','자연어로 추가',{ico:'plus',cls:'ghost'})}${btn('gpt-plan','ChatGPT로 계획',{ico:'link',cls:'ghost'})}</div></section>`;
}
export function dashboardView(ctx, ui, renderTimeline) {
  return `${quickInput(ctx,ui)}<div class="dashboard-grid">${agendaPanel(ctx,ui,renderTimeline)}${taskPanel(ctx,ui)}${projectRows(ctx,ui)}${deadlinesPanel(ctx,ui)}</div>`;
}
