// Google Identity Services token model: no client secret or refresh token in the browser.
// Direct Google access requires the owner's OAuth client ID and explicit consent.
import {uid,at,dateKey,addDays,upsert,remove} from './core.js';
let accessToken='',expiresAt=0;
export const googleReady=()=>!!accessToken&&Date.now()<expiresAt;
export const googleDisconnect=()=>{if(accessToken&&window.google?.accounts?.oauth2)window.google.accounts.oauth2.revoke(accessToken,()=>{});accessToken='';expiresAt=0;};
export async function authorizeGoogle(clientId){if(!/^\d+-[\w-]+\.apps\.googleusercontent\.com$/.test(clientId||''))throw new Error('설정에서 Google OAuth 웹 클라이언트 ID를 먼저 입력하세요.');if(!window.google?.accounts?.oauth2){await new Promise((resolve,reject)=>{const old=document.querySelector('script[data-google-gis]');if(old)old.remove();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.dataset.googleGis='true';s.onload=resolve;s.onerror=()=>reject(new Error('Google 인증 스크립트를 불러오지 못했습니다.'));document.head.append(s);});}return new Promise((resolve,reject)=>{const client=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.calendarlist.readonly',callback:r=>{if(r.error)return reject(new Error(r.error_description||r.error));accessToken=r.access_token;expiresAt=Date.now()+(Number(r.expires_in)-60)*1000;resolve();},error_callback:e=>reject(new Error(e.type==='popup_closed'?'Google 연결 창을 닫았습니다.':'팝업을 허용한 뒤 다시 연결하세요.'))});client.requestAccessToken({prompt:'consent'});});}
async function request(path,{method='GET',body,etag}={}){if(!googleReady())throw new Error('Google 인증이 필요합니다. 연결·설정에서 Google에 다시 연결하세요.');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(`https://www.googleapis.com/calendar/v3/${path}`,{method,headers:{Authorization:`Bearer ${accessToken}`,...(body?{'Content-Type':'application/json'}:{}),...(etag?{'If-Match':etag}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});if(r.status===204)return null;const data=await r.json();if(!r.ok){if(r.status===401){accessToken='';throw new Error('Google 인증이 만료되었습니다. 다시 연결하세요.');}if(r.status===412)throw new Error('Google에서 이 일정이 변경되었습니다. 먼저 동기화한 뒤 다시 수정하세요.');throw new Error(data.error?.message||`Google 오류 ${r.status}`);}return data;}finally{clearTimeout(timeout);}}
export async function calendars(){const list=[];let pageToken;do{const q=new URLSearchParams({maxResults:'100',...(pageToken?{pageToken}:{})});const r=await request(`users/me/calendarList?${q}`);list.push(...(r.items||[]));pageToken=r.nextPageToken;}while(pageToken);return list;}
export async function importGoogle(state,calendarId,from,to){const entries=[];let pageToken;do{const q=new URLSearchParams({timeMin:at(from).toISOString(),timeMax:at(to).toISOString(),singleEvents:'true',maxResults:'2500',showDeleted:'false',...(pageToken?{pageToken}:{})});const r=await request(`calendars/${encodeURIComponent(calendarId)}/events?${q}`);entries.push(...(r.items||[]));pageToken=r.nextPageToken;if(entries.length>4000)throw new Error('일정이 너무 많습니다. 동기화 기간을 줄여주세요.');}while(pageToken);const operations=[];for(const e of entries){if(!e.start||!e.end||e.status==='cancelled')continue;const existing=state.blocks.find(b=>b.googleCalendarId===calendarId&&b.googleEventId===e.id);const start=e.start.dateTime||at(e.start.date).toISOString();const end=e.end.dateTime||at(e.end.date).toISOString();if(!Number.isFinite(+new Date(start))||+new Date(end)<=+new Date(start))continue;const data={...existing,id:existing?.id||uid(),title:(e.summary||'(제목 없는 일정)').slice(0,200),start,end,taskId:existing?.taskId||null,source:'google',locked:existing?.locked??true,allDay:!!e.start.date,googleCalendarId:calendarId,googleEventId:e.id,googleEtag:e.etag,googleRecurring:!!e.recurringEventId,notes:(e.description||'').slice(0,20000)};if(!existing||existing.googleEtag!==e.etag)operations.push(upsert('blocks',data));}for(const old of state.blocks.filter(b=>b.googleCalendarId===calendarId&&+new Date(b.end)>+at(from)&&+new Date(b.start)<+at(to))){if(!entries.some(e=>e.id===old.googleEventId))operations.push(remove('blocks',old.id));}if(operations.length>500)throw new Error('한 번에 500건을 초과합니다. 기간을 줄여주세요.');return operations;}
export async function writeGoogle(block,calendarId){const cid=block.googleCalendarId||calendarId;if(!cid)throw new Error('저장할 Google 캘린더를 선택하세요.');const resource={summary:block.title,...(block.allDay?{start:{date:dateKey(block.start)},end:{date:dateKey(block.end)}}:{start:{dateTime:new Date(block.start).toISOString(),timeZone:'Asia/Seoul'},end:{dateTime:new Date(block.end).toISOString(),timeZone:'Asia/Seoul'}})};let event;if(block.googleEventId)event=await request(`calendars/${encodeURIComponent(cid)}/events/${encodeURIComponent(block.googleEventId)}?sendUpdates=none`,{method:'PATCH',body:resource,etag:block.googleEtag});else event=await request(`calendars/${encodeURIComponent(cid)}/events?sendUpdates=none`,{method:'POST',body:{...resource,id:block.id.replaceAll('-','')}});return {...block,source:'google',googleCalendarId:cid,googleEventId:event.id,googleEtag:event.etag};}
export async function deleteGoogle(block){if(!block.googleEventId)return;return request(`calendars/${encodeURIComponent(block.googleCalendarId)}/events/${encodeURIComponent(block.googleEventId)}?sendUpdates=none`,{method:'DELETE',etag:block.googleEtag});}
