import {esc,at,dateKey,timeKey,addDays,monthDays} from './core.js';
import {PALETTE,day,monday,plusDay,spec,repeatStatus,repeatLabel,colorOf,rangeDays} from './journey-domain.js';
export const journeyUI={range:30,category:'all',tab:'journey',shop:'all',end:day()};
export const ji=name=>{const paths={check:'M5 12l4 4L19 6',stats:'M4 20V12m5 8V4m6 16V9m5 11V6',compass:'M12 3a9 9 0 1 0 .01 0M15 9l-2 4-4 2 2-4z',moon:'M20 15A9 9 0 0 1 9 3a7 7 0 0 0 11 12',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M6 6l1 1m10 10 1 1M6 18l1-1M17 7l1-1M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0',spark:'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z',leaf:'M5 19C-2 8 11 2 21 3c0 13-5 17-16 16zm0 0L16 8',shield:'M12 3l8 3v6c0 4-5 8-8 9-3-1-8-5-8-9V6z',paw:'M8 21c-7-2-3-9 1-8 2-3 5-3 6 0 5-1 7 6 2 8zM5 5v3m5-6v4m5-4v4m5-1v3',book:'M12 6c-3-3-7-3-10-2v15c4-1 7-1 10 2m0-15c3-3 7-3 10-2v15c-4-1-7-1-10 2V6',crown:'M3 6l4 4 5-7 5 7 4-4-2 13H5z',flag:'M5 22V3c6-5 7 5 15 0v11c-8 5-9-5-15 0',footsteps:'M6 3c-4 2-4 9 0 9s3-7 0-9m1 12v4m10-12c4 2 4 9 0 9s-3-7 0-9m-1 12v3',shop:'M3 8l3-5h12l3 5v3H3zM5 11v10h14V11M9 21v-6h6v6',arrow:'M5 12h14m-5-5 5 5-5 5',undo:'M8 5L3 10l5 5M3 10h10a6 6 0 0 1 0 12',clock:'M12 3a9 9 0 1 0 .01 0M12 7v5l3 2',coin:'M12 3a9 9 0 1 0 .01 0M12 7l4 5-4 5-4-5z',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5z',heart:'M12 20S-2 12 4 5c4-4 8 1 8 1s4-5 8-1c6 7-8 15-8 15',plus:'M12 5v14M5 12h14'};return `<svg viewBox="0 0 24 24" class="icon" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;};
export const action=(name,text,id='',cls='')=>`<button type="button" class="button ${cls}" data-action="${name}" data-id="${esc(id)}">${text}</button>`;
export const pct=(n,d)=>d?Math.min(100,Math.round(n/d*100)):0;
export const meter=(n,d,cls='')=>`<div class="j-meter ${cls}" role="progressbar" aria-label="목표 진행" aria-valuenow="${pct(n,d)}" aria-valuemin="0" aria-valuemax="100"><span style="width:${pct(n,d)}%"></span></div>`;
export function completion(i,d=day(),compact=false){const s=repeatStatus(i,d);if(!s)return `<button type="button" class="check ${i.status==='done'?'done':''}" data-action="complete" data-id="${esc(i.id)}" aria-label="${esc(i.title)} ${i.status==='done'?'완료 취소':'완료'}">${i.status==='done'?ji('check'):''}</button>`;return `<span class="j-repeat-check ${compact?'compact':''}"><button type="button" class="check ${s.done?'done':''}" data-action="v3-check" data-id="${esc(i.id)}|${d}|${s.done?'undo':'add'}" ${!s.done&&!s.canCheck?'disabled':''} aria-label="${esc(i.title)} ${s.done?'마지막 1회 완료 취소':'1회 완료'} · ${s.count}/${s.target}" title="${esc(repeatLabel(i,d))}${d>day()?' · 미래 완료 불가':''}">${s.done?ji('check'):'<span class="j-check-plus">+</span>'}</button>${!compact?`<small>${s.count}/${s.target}</small>${s.count>0&&!s.done?`<button type="button" class="j-undo-check" data-action="v3-check" data-id="${esc(i.id)}|${d}|undo" aria-label="${esc(i.title)} 마지막 1회 취소">${ji('undo')}</button>`:''}`:''}</span>`;}
function eventCard(b,state,d,compact=false){const i=state.items.find(t=>t.id===b.taskId),done=i?(repeatStatus(i,d)?.done??(i.status==='done')):!!b.completedAt;return `<div class="j-cal-entry ${done?'j-finished':''}" data-color="${colorOf(b,state.items)}" ${!compact?`draggable="${!b.locked}" data-drag-type="block" data-id="${esc(b.id)}"`:''}>${i?completion(i,d,true):`<button type="button" class="check ${done?'done':''}" data-action="v3-event-check" data-id="${esc(b.id)}" aria-label="${esc(b.title)} 보드에서 ${done?'완료 취소':'완료'}">${done?ji('check'):''}</button>`}<button class="j-cal-title" data-action="edit-block" data-id="${esc(b.id)}" title="${esc(b.title)}"><small>${b.allDay?'종일':timeKey(b.start)+(compact?'':'–'+timeKey(b.end))}</small><span>${esc(b.title)}</span>${!compact&&i&&spec(i)?`<em>${repeatStatus(i,d).count}/${repeatStatus(i,d).target}회</em>`:''}</button></div>`;}
function taskCard(i,d,compact=false){const s=repeatStatus(i,d),done=s?s.done:i.status==='done';return `<div class="j-cal-entry j-cal-task ${done?'j-finished':''}" data-color="${colorOf(i)}">${completion(i,d,compact)}<button class="j-cal-title" data-action="edit-item" data-id="${esc(i.id)}"><small>${s?repeatLabel(i,d):'마감 업무'}</small><span>${esc(i.title)}</span></button></div>`;}
export function entriesForDate(state,d){const blocks=state.blocks.filter(b=>+new Date(b.start)<+at(addDays(d,1))&&+new Date(b.end)>+at(d)).sort((a,b)=>+new Date(a.start)-+new Date(b.start)),linked=new Set(blocks.map(b=>b.taskId)),leaves=state.items.filter(i=>i.kind!=='project'&&!state.items.some(c=>c.parentId===i.id)),tasks=leaves.filter(i=>!linked.has(i.id)&&(spec(i)?repeatStatus(i,d).eligible:i.deadline===d));return {blocks,tasks,total:blocks.length+tasks.length};}
export function dateContents(state,d,limit=Infinity,compact=false){const e=entriesForDate(state,d);return [...e.blocks.map(b=>({b})),...e.tasks.map(i=>({i}))].slice(0,limit).map(v=>v.b?eventCard(v.b,state,d,compact):taskCard(v.i,d,compact)).join('');}
export function calendarV3(ctx){const state=ctx.rawState||ctx.state;if(ctx.view==='week'){const dates=rangeDays(plusDay(monday(ctx.date),6),7);return `<div class="filters">${action('plan',ji('spark')+' 빈 시간에 배치')}${action('add-item',ji('plus')+' 할 일 추가')}<span class="tiny muted">체크 한 번으로 완료 · 반복은 1회씩 기록</span></div><div class="week-board j-week">${dates.map(d=>`<section class="week-day ${d===day()?'today':''}" data-drop-day="${d}"><button class="week-day-header" data-action="v3-day" data-id="${d}">${'일월화수목금토'[new Date(+at(d)+32400000).getUTCDay()]}<strong>${+d.slice(8)}</strong></button>${dateContents(state,d)||'<div class="empty-plain">정해진 일정이 없습니다.</div>'}<div class="add-day">${action('new-block-on-day','+ 일정',d,'ghost')}</div></section>`).join('')}</div>`;}return `<p class="j-view-hint">체크를 눌러 바로 완료하세요. ‘더 보기’에서 그날의 모든 업무를 확인할 수 있습니다.</p><section class="month j-month"><div class="month-head">${'월화수목금토일'.split('').map(d=>`<span>${d}</span>`).join('')}</div><div class="month-grid">${monthDays(ctx.date).map(d=>{const n=entriesForDate(state,d).total;return `<div class="month-cell ${d.slice(0,7)!==ctx.date.slice(0,7)?'outside':''} ${d===day()?'today':''}" data-drop-day="${d}"><button class="month-date" data-action="v3-day" data-id="${d}" aria-label="${d} 전체 일정">${+d.slice(8)}</button>${dateContents(state,d,3,true)}${n>3?action('v3-day',`+${n-3} 더 보기`,d,'j-more-day ghost'):''}</div>`;}).join('')}</div></section><div class="j-mobile-month-note">작은 화면에서는 날짜를 눌러 큰 체크 목록을 여세요.</div>`;}
export function routineFields(i){const r=spec(i);return `<div class="j-form-section full"><div class="j-form-section-head"><strong>반복 목표</strong><span class="hint">완료할 때마다 1회씩 기록합니다.</span></div><div class="fields"><div><label for="repeatMode">반복 방식</label><select id="repeatMode" name="repeatMode"><option value="legacy" ${!r?'selected':''}>위의 기본 반복 설정 사용</option><option value="daily" ${r?.mode==='daily'?'selected':''}>매일 N회</option><option value="weekly" ${r?.mode==='weekly'?'selected':''}>매주 N회 · 요일 선택</option></select></div><div><label for="repeatTarget">목표 횟수</label><input type="number" id="repeatTarget" name="repeatTarget" min="1" max="99" value="${r?.target||1}"></div><div class="full"><label>실행 가능한 요일</label><div class="j-days">${[1,2,3,4,5,6,0].map(n=>`<label class="j-day-choice"><input type="checkbox" name="repeatDay" value="${n}" ${(r?.days||[0,1,2,3,4,5,6]).includes(n)?'checked':''}><span>${'일월화수목금토'[n]}</span></label>`).join('')}</div></div><div><label for="repeatStart">반복 시작일</label><input id="repeatStart" name="repeatStart" type="date" value="${r?.start||day()}"></div><div><label class="inline-label j-pause"><input type="checkbox" name="routinePaused" ${i.routinePaused?'checked':''}>반복 일시 중지</label></div></div><p class="hint">매일은 선택한 요일마다 목표 횟수, 매주는 선택한 요일에 한 주 목표 횟수를 합산합니다. 주간 기준은 월요일입니다. 기존 기록은 유지되며 미래 완료는 기록하지 않습니다.</p></div>`;}
export function colorFields(value,context='업무'){return `<div class="full j-color-field"><label>${context} 색상</label><div class="j-color-choices"><label title="상위 업무 색상 상속"><input type="radio" name="color" value="" ${!value?'checked':''}><span class="j-color-auto">자동</span></label>${PALETTE.map(([v,label,hex])=>`<label title="${label}"><input type="radio" name="color" value="${v}" ${value===v?'checked':''}><span style="--swatch:${hex}">${ji('check')}</span><em>${label}</em></label>`).join('')}</div><p class="hint">색은 구분을 돕는 용도입니다. Google 원본 색상은 바꾸지 않습니다.</p></div>`;}
export {statsView} from './journey-stats.js';
export {adventureView} from './journey-adventure.js';
