export const SEOUL='Asia/Seoul';
export const day=(v=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:SEOUL,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
export const midnight=d=>new Date(`${d}T00:00:00+09:00`);
export const plusDay=(d,n)=>day(new Date(+midnight(d)+n*86400000));
export const weekday=d=>new Date(+midnight(d)+32400000).getUTCDay();
export const monday=d=>plusDay(d,-((weekday(d)+6)%7));
export const nowISO=()=>new Date().toISOString();
export const PALETTE=[['indigo','인디고','#6468e8'],['sky','하늘','#318cbb'],['teal','청록','#228578'],['green','초록','#568846'],['amber','호박','#b87c26'],['coral','산호','#ce665b'],['rose','분홍','#be608d'],['violet','보라','#9062b9']];
export const validColor=value=>PALETTE.some(c=>c[0]===value)?value:null;
export function colorOf(item,items=[]){let current=item;for(let depth=0;current&&depth<4;depth++){if(validColor(current.color))return current.color;if(current.taskId)current=items.find(t=>t.id===current.taskId);else current=items.find(t=>t.id===current.parentId);}return 'indigo';}
export function spec(item){if(!item?.repeatRule||item.repeatRule.mode==='none')return null;const r=item.repeatRule;return {mode:r.mode==='weekly'?'weekly':'daily',target:Math.max(1,Math.min(r.mode==='weekly'?99:20,Number(r.target)||1)),days:Array.isArray(r.days)&&r.days.length?[...new Set(r.days)].sort():[0,1,2,3,4,5,6],start:r.start||day(item.createdAt||new Date())};}
export function periodOf(r,d){return (r.mode==='weekly'?'W:':'D:')+(r.mode==='weekly'?monday(d):d);}
export function repeatStatus(item,d=day()){const r=spec(item);if(!r)return null;const period=periodOf(r,d),checks=(item.checkins||[]).filter(c=>c.period===period),count=checks.length;const eligible=d>=r.start&&r.days.includes(weekday(d))&&!item.routinePaused;return {rule:r,period,count,target:r.target,done:count>=r.target,eligible,canCheck:eligible&&d<=day()&&count<r.target,checks};}
export function repeatLabel(item,d=day()){const s=repeatStatus(item,d);if(!s)return '';return `${s.rule.mode==='weekly'?'매주':'매일'} ${s.target}회${s.rule.days.length===7?'':' · '+[1,2,3,4,5,6,0].filter(n=>s.rule.days.includes(n)).map(n=>'일월화수목금토'[n]).join('·')}`;}
export function repeatOperations(state,id,d=day(),undo=false){const i=state.items.find(t=>t.id===id),s=repeatStatus(i,d);if(!i||!s)throw new Error('반복 업무를 찾을 수 없습니다.');let log=[...(i.checkins||[])];if(undo){const last=s.checks.at(-1);if(!last)return [];log=log.filter(c=>c.id!==last.id);}else{if(!s.canCheck)throw new Error(s.done?'이번 목표는 이미 완료했습니다.':d>day()?'미래의 완료 기록을 미리 만들 수 없습니다.':'지정한 실행 요일이 아니거나 일시 중지된 업무입니다.');if(log.length>=2500)throw new Error('기록을 백업하고 새 반복 업무를 시작하세요.');const used=new Set(s.checks.map(c=>c.slot));let slot=1;while(used.has(slot))slot++;log.push({id:`${s.period}:${slot}`,period:s.period,slot,day:d,at:nowISO()});}return [{collection:'items',action:'upsert',data:{...i,checkins:log,status:'todo',progress:0,completedAt:null}}];}
export function effectiveItems(items,d=day()){return items.map(i=>{const s=repeatStatus(i,d);return s?{...i,status:s.done?'done':s.count?'doing':'todo',progress:Math.min(100,Math.round(s.count/s.target*100)),_repeatDay:d}:i;});}
export const leafItems=items=>items.filter(i=>i.kind!=='project'&&!items.some(c=>c.parentId===i.id));
export const eventXP=i=>Math.min(80,Math.max(5,Math.round((Number(i.estimatedMinutes)||30)/15)*5)+(Number(i.importance)||2)*5);
function eventFor(i,key,date,at,kind='task'){return {id:key,taskId:i.id,title:i.title,category:i.category||'일반',color:validColor(i.color)||'indigo',minutes:Number(i.estimatedMinutes)||30,deadline:i.deadline||null,day:date,at,kind,xp:eventXP(i),active:true};}
export function reconcileActivity(before,next){const ledger=structuredClone(before?.settings?.activity||{});for(const i of leafItems(next.items||[])){if(spec(i)){const alive=new Set((i.checkins||[]).map(c=>`routine:${i.id}:${c.id}`));for(const [key,event] of Object.entries(ledger))if(event.taskId===i.id&&event.kind==='routine'&&!alive.has(key))ledger[key]={...event,active:false};for(const c of i.checkins||[]){const key=`routine:${i.id}:${c.id}`;if(!ledger[key]?.active)ledger[key]=eventFor(i,key,c.day,c.at,'routine');}if(ledger[`task:${i.id}`])ledger[`task:${i.id}`].active=false;}else if(i.status==='done'){const key=`task:${i.id}`;if(!ledger[key]?.active)ledger[key]=eventFor(i,key,day(i.completedAt||new Date()),i.completedAt||nowISO());}else if(ledger[`task:${i.id}`])ledger[`task:${i.id}`].active=false;}for(const i of next.items||[])if(next.items.some(c=>c.parentId===i.id)&&ledger[`task:${i.id}`])ledger[`task:${i.id}`].active=false;return ledger;}
export function activity(state){return Object.values(reconcileActivity(state,state)).filter(e=>e.active&&e.day<=day()).sort((a,b)=>a.day.localeCompare(b.day)||a.at.localeCompare(b.at));}
export function rewardSummary(state){const events=activity(state),projectBonus=state.items.filter(i=>i.kind==='project'&&i.status==='done').length*100,xp=events.reduce((s,e)=>s+e.xp,0)+projectBonus,w=monday(day());return {events,xp,level:1+Math.floor(xp/250),levelXP:xp%250,weekly:events.filter(e=>e.day>=w).length,completed:events.length,projects:projectBonus/100,goal:state.settings.weeklyGoal||5};}
export function rangeDays(end=day(),count=30){return Array.from({length:count},(_,n)=>plusDay(end,n-count+1));}
export function statistics(state,days=30,end=day(),category='all'){const dates=rangeDays(end,days),start=dates[0],all=activity(state),events=all.filter(e=>e.day>=start&&e.day<=end&&(category==='all'||e.category===category)),prevStart=plusDay(start,-days),previous=all.filter(e=>e.day>=prevStart&&e.day<start&&(category==='all'||e.category===category)),dated=events.filter(e=>e.deadline),onTime=dated.filter(e=>e.day<=e.deadline);const daily=dates.map(d=>({day:d,count:events.filter(e=>e.day===d).length,minutes:events.filter(e=>e.day===d).reduce((s,e)=>s+e.minutes,0)}));const byCategory=[...new Set(events.map(e=>e.category))].map(c=>({name:c,count:events.filter(e=>e.category===c).length,minutes:events.filter(e=>e.category===c).reduce((s,e)=>s+e.minutes,0),color:events.find(e=>e.category===c).color})).sort((a,b)=>b.count-a.count),weekdays=[1,2,3,4,5,6,0].map(w=>({weekday:w,count:events.filter(e=>weekday(e.day)===w).length,days:dates.filter(d=>weekday(d)===w).length})),hourBuckets=Array.from({length:6},(_,b)=>({start:b*4,count:events.filter(e=>Math.floor(Number(new Intl.DateTimeFormat('en-GB',{timeZone:SEOUL,hour:'numeric',hour12:false}).format(new Date(e.at)))/4)===b).length}));const open=leafItems(state.items).filter(i=>!spec(i)&&i.status!=='done'&&(category==='all'||i.category===category)),overdue=open.filter(i=>i.deadline&&i.deadline<day()),daysActive=daily.filter(d=>d.count).length,minutes=events.reduce((n,e)=>n+e.minutes,0),routines=leafItems(state.items).filter(i=>spec(i)&&!i.routinePaused&&(category==='all'||i.category===category)).map(i=>{const r=spec(i),eligible=dates.filter(d=>d>=r.start&&r.days.includes(weekday(d))),periods=[...new Set(eligible.map(d=>periodOf(r,d)))],completed=periods.reduce((n,p)=>n+Math.min(r.target,(i.checkins||[]).filter(c=>c.period===p&&c.day<=end).length),0);return {item:i,target:periods.length*r.target,completed};});return {dates,start,end,events,previous:previous.length,delta:events.length-previous.length,daily,byCategory,weekdays,hourBuckets,open,overdue,daysActive,minutes,onTime:onTime.length,dated:dated.length,onTimeRate:dated.length?Math.round(onTime.length/dated.length*100):null,routines,routineTotal:routines.reduce((n,r)=>n+r.target,0),routineDone:routines.reduce((n,r)=>n+r.completed,0)};}
export const CATALOG=[{id:'outfit-ranger',slot:'outfit',value:'ranger',name:'숲의 레인저',description:'초록빛 망토 · 길을 찾아가는 여행자',price:45,level:1,icon:'leaf'},{id:'outfit-mage',slot:'outfit',value:'mage',name:'별빛 기록자',description:'자줏빛 망토 · 지식을 모으는 마법사',price:100,level:2,icon:'spark'},{id:'outfit-knight',slot:'outfit',value:'knight',name:'새벽의 수호자',description:'은빛 망토 · 꾸준함으로 단단해지기',price:160,level:3,icon:'shield'},{id:'pet-cat',slot:'pet',value:'cat',name:'구름 고양이',description:'여행자를 따라오는 동료',price:60,level:1,icon:'paw'},{id:'pet-wisp',slot:'pet',value:'wisp',name:'별의 정령',description:'길을 밝혀주는 작은 빛',price:90,level:2,icon:'spark'},{id:'scene-dusk',slot:'scene',value:'dusk',name:'노을의 정원',description:'하루를 마무리하는 따뜻한 풍경',price:80,level:1,icon:'sun'},{id:'scene-night',slot:'scene',value:'night',name:'달빛의 숲',description:'깊은 밤, 고요한 여정',price:140,level:3,icon:'moon'},{id:'aura-starlight',slot:'aura',value:'starlight',name:'별빛 발자국',description:'주위를 흐르는 작은 별들',price:70,level:2,icon:'spark'},{id:'aura-leaves',slot:'aura',value:'leaves',name:'잎새의 축복',description:'바람에 흩날리는 숲의 흔적',price:70,level:2,icon:'leaf'},{id:'title-explorer',slot:'title',value:'explorer',name:'길을 만드는 사람',description:'여행자의 칭호',price:35,level:1,icon:'compass'},{id:'title-scholar',slot:'title',value:'scholar',name:'기록의 수호자',description:'배움과 기록을 위한 칭호',price:120,level:3,icon:'book'},{id:'title-master',slot:'title',value:'master',name:'하루의 설계자',description:'작은 실행이 쌓인 자리에',price:220,level:5,icon:'crown'}];
export const ZONES=[{id:'trail',name:'시작의 산책로',xp:0,text:'작은 완료 하나가 지도를 열었습니다.'},{id:'grove',name:'지식의 숲',xp:150,text:'배움의 흔적이 숲에 빛을 남깁니다.'},{id:'bridge',name:'꾸준함의 다리',xp:400,text:'서두르지 않고도 건널 수 있습니다.'},{id:'lake',name:'회고의 호수',xp:800,text:'돌아본 시간도 앞으로 가는 길입니다.'},{id:'observatory',name:'별빛 관측소',xp:1400,text:'하루의 점들이 별자리가 됩니다.'},{id:'summit',name:'내일의 정상',xp:2400,text:'다음 여정의 시작입니다.'}];
export const DEFAULT_GAME={name:'여행자',outfit:'traveler',pet:'none',scene:'forest',aura:'none',title:'none',motion:true,purchases:[],claims:[],visits:[],customRewards:[],redemptions:[]};
export const gameState=state=>({...DEFAULT_GAME,...state.settings.adventure});
export function quests(state,d=day()){const a=activity(state),w=monday(d),daily=a.filter(e=>e.day===d),weekly=a.filter(e=>e.day>=w&&e.day<plusDay(w,7));return [{id:`day:${d}`,name:'오늘의 작은 세 걸음',description:'오늘 업무를 3회 완료하기',count:daily.length,target:3,reward:10,scope:'오늘'},{id:`week:${w}`,name:'한 주의 여정',description:'이번 주 업무를 12회 완료하기',count:weekly.length,target:12,reward:30,scope:'이번 주'},{id:`balance:${w}`,name:'다양한 길을 걷기',description:'이번 주 서로 다른 3개 분야 실행하기',count:new Set(weekly.map(e=>e.category)).size,target:3,reward:15,scope:'이번 주'},{id:`reflect:${w}`,name:'돌아보는 여행자',description:'이번 주 회고를 한 번 작성하기',count:Object.entries(state.settings.reflections||{}).filter(([date,v])=>date>=w&&date<plusDay(w,7)&&String(v.win||v.next||v.friction||'').trim()).length,target:1,reward:10,scope:'이번 주'}];}
export function validClaim(state,claim){return claim?.id&&claim?.day?quests(state,claim.day).find(q=>q.id===claim.id&&q.count>=q.target):null;}
export function economy(state){const g=gameState(state),summary=rewardSummary(state);let bonuses=0;for(const c of g.claims){const q=validClaim(state,c);if(q)bonuses+=q.reward;}const earned=summary.events.reduce((n,e)=>n+Math.max(1,Math.floor(e.xp/5)),0)+summary.projects*20+bonuses,spent=g.purchases.reduce((n,p)=>n+(CATALOG.find(c=>c.id===p.id)?.price||0),0)+g.redemptions.reduce((n,r)=>n+(Number(r.cost)||0),0);return {...summary,earned,spent,balance:earned-spent,bonuses,game:g};}
export function gameOperation(state,action,id){const e=economy(state),g=structuredClone(e.game);if(action==='buy'){const item=CATALOG.find(i=>i.id===id);if(!item)throw new Error('상품이 없습니다.');if(g.purchases.some(p=>p.id===id))throw new Error('이미 보유한 상품입니다.');if(e.level<item.level)throw new Error(`레벨 ${item.level}부터 교환할 수 있습니다.`);if(e.balance<item.price)throw new Error('별조각이 부족합니다.');g.purchases.push({id,at:nowISO()});g[item.slot]=item.value;}if(action==='equip'){if(id==='default')Object.assign(g,{outfit:'traveler',pet:'none',scene:'forest',aura:'none',title:'none'});else{const item=CATALOG.find(i=>i.id===id);if(!item||!g.purchases.some(p=>p.id===id))throw new Error('보유한 아이템만 장착할 수 있습니다.');g[item.slot]=item.value;}}if(action==='claim'){const q=quests(state).find(q=>q.id===id);if(!q||q.count<q.target)throw new Error('아직 퀘스트 조건을 달성하지 않았습니다.');if(g.claims.some(c=>c.id===id))throw new Error('이미 받은 보상입니다.');g.claims.push({id,day:day(),at:nowISO()});}if(action==='visit'){const z=ZONES.find(z=>z.id===id);if(!z||e.xp<z.xp)throw new Error('아직 열리지 않은 지역입니다.');if(!g.visits.includes(id))g.visits.push(id);g.zone=id;}if(action==='redeem'){const r=g.customRewards.find(r=>r.id===id);if(!r||e.balance<r.cost)throw new Error('보상을 찾을 수 없거나 별조각이 부족합니다.');g.redemptions.push({id:crypto.randomUUID(),rewardId:id,title:r.title,cost:r.cost,at:nowISO()});}return [{collection:'settings',action:'merge',data:{adventure:g}}];}
export function achievements(state){const e=economy(state);return [{name:'첫 걸음',description:'업무 1회 완료',unlocked:e.completed>=1,icon:'footsteps'},{name:'꾸준한 여행자',description:'서로 다른 7일 실행',unlocked:new Set(e.events.map(c=>c.day)).size>=7,icon:'compass'},{name:'작은 완성',description:'업무 25회 완료',unlocked:e.completed>=25,icon:'check'},{name:'목표의 완성',description:'프로젝트 1개 완료',unlocked:e.projects>=1,icon:'flag'},{name:'기록하는 사람',description:'회고 3일 작성',unlocked:Object.values(state.settings.reflections||{}).filter(r=>r.win||r.next||r.friction).length>=3,icon:'book'},{name:'백 번의 실행',description:'업무 100회 완료',unlocked:e.completed>=100,icon:'crown'}];}
export function enrichDemo(state){const s=structuredClone(state),colors=['indigo','teal','green','amber'],cats=['학습','연구','건강','생활'],titles=['논문 읽고 핵심 정리','자료 분석과 기록','가벼운 운동','하루 공간 정리'];for(let ago=1;ago<=28;ago++){if(ago%7===0)continue;for(let n=0;n<(ago%4)+1;n++){const c=(ago+n)%4,id=crypto.randomUUID(),d=plusDay(day(),-ago);s.items.push({id,kind:'task',parentId:null,title:`${titles[c]} · 샘플 ${ago}-${n+1}`,deadline:plusDay(d,ago%6===0?-1:0),estimatedMinutes:[30,60,20,15][c],importance:2,urgency:2,category:cats[c],recurrence:'none',progress:100,status:'done',notes:'샘플 통계용 데이터입니다.',completedAt:`${d}T${String(9+(ago+n)%10).padStart(2,'0')}:00:00+09:00`,createdAt:`${plusDay(d,-1)}T09:00:00+09:00`,color:colors[c]});}}const d=day(),r={id:crypto.randomUUID(),kind:'task',parentId:null,title:'짧게 몸 풀기',deadline:null,estimatedMinutes:10,importance:2,urgency:1,category:'건강',recurrence:'daily',progress:0,status:'todo',notes:'샘플 반복 업무: 매일 2회',completedAt:null,createdAt:`${plusDay(d,-14)}T09:00:00+09:00`,color:'green',repeatRule:{mode:'daily',target:2,days:[0,1,2,3,4,5,6],start:plusDay(d,-14)},checkins:[]};for(let ago=0;ago<14;ago++){const rd=plusDay(d,-ago);for(let slot=1;slot<=(ago===0?1:ago%3===0?1:2);slot++)r.checkins.push({id:`D:${rd}:${slot}`,period:`D:${rd}`,slot,day:rd,at:`${rd}T10:00:00+09:00`});}s.items.push(r);s.settings.activity=reconcileActivity(null,s);s.settings.adventure={...DEFAULT_GAME,name:'샘플 여행자',outfit:'mage',pet:'cat',purchases:[{id:'outfit-mage',at:nowISO()},{id:'pet-cat',at:nowISO()}]};s.settings.reflections={[plusDay(d,-2)]:{win:'[샘플] 작은 행동으로 나누니 시작이 쉬웠다.',friction:'[샘플] 예정하지 않은 일이 생겼다.',next:'[샘플] 내일은 여유 시간 30분을 남긴다.',energy:3}};return s;}
