import {esc,upsert,completeOps,dayOfWeek,at} from './core.js';
import {spec,repeatStatus,repeatOperations,repeatLabel,validColor,colorOf,gameOperation,gameState,economy,ZONES,statistics,day,activity} from './journey-domain.js';
import {journeyUI,completion,dateContents,routineFields,colorFields,ji} from './journey-view.js';
import {paintOutfits} from './journey-art.js';
export function createJourneyController(api){
 const {store,getState,getDate,setView,render,notify,openModal,closeModal,getEditor}=api;let reflectionDraft=null;
 const frame=(title,body)=>`<div class="modal-head"><h2 id="modal-title">${title}</h2><button type="button" class="iconbutton" data-action="close" aria-label="닫기">×</button></div><div class="modal-body">${body}<div id="modal-error" class="error-text" role="alert"></div></div><div class="modal-foot"><button class="button" type="button" data-action="close">닫기</button></div>`;
 function openDay(d){openModal(frame(`${+d.slice(5,7)}월 ${+d.slice(8)}일 ${'일월화수목금토'[dayOfWeek(d)]}요일`,`<p class="hint">업무는 체크 한 번으로 완료합니다. 반복 목표는 1회씩 기록합니다. 약속 완료 표시는 보드 안에서만 적용됩니다.</p><div class="j-day-modal">${dateContents(getState(),d)||'<p class="empty-plain">등록된 일정이나 업무가 없습니다.</p>'}${activity(getState()).filter(a=>a.day===d).length?'<h3 class="space-top">이날의 완료 기록</h3>'+activity(getState()).filter(a=>a.day===d).map(a=>'<p class="j-history-line">'+esc(a.title)+' · '+(a.kind==='routine'?'반복 1회':'완료')+'</p>').join(''):''}</div>`),{type:'v3day',date:d});}
 function refreshDay(){const e=getEditor();if(e?.type==='v3day')openDay(e.date);}
 function capture(root){const form=root.querySelector('#reflection-form');if(form)reflectionDraft=Object.fromEntries(new FormData(form));}
 function restore(root){const form=root.querySelector('#reflection-form');if(form&&reflectionDraft)for(const [k,v] of Object.entries(reflectionDraft))if(form.elements[k])form.elements[k].value=v;}
 function decorate(root){paintOutfits(root);const state=getState();if(!state)return;
  for(const el of root.querySelectorAll('.dash-task,.kanban-card,.task-row')){const i=state.items.find(i=>i.id===el.dataset.id);if(i){el.dataset.color=colorOf(i,state.items);const control=el.querySelector('button[data-action=complete]');if(control&&spec(i))control.outerHTML=completion(i,getDate());if(spec(i)&&!el.querySelector('.j-repeat-caption')){const meta=el.querySelector('.meta');if(meta){const hint=document.createElement('div');hint.className='j-repeat-caption';hint.textContent=repeatLabel(i,getDate());meta.after(hint);}}}}
  for(const bEl of [...root.querySelectorAll('.dash-event')]){if(bEl.parentElement.classList.contains('j-completion-sibling'))continue;const b=state.blocks.find(b=>b.id===bEl.dataset.id);if(!b)continue;const i=state.items.find(i=>i.id===b.taskId),wrap=document.createElement('div');wrap.className='j-completion-sibling';wrap.dataset.color=colorOf(b,state.items);bEl.before(wrap);wrap.append(bEl);const d=getDate(),finished=i?(repeatStatus(i,d)?.done??i.status==='done'):!!b.completedAt;if(finished)bEl.classList.add('is-finished');wrap.insertAdjacentHTML('beforeend',i?completion(i,d):`<button type="button" class="check ${finished?'done':''}" data-action="v3-event-check" data-id="${b.id}" aria-label="${esc(b.title)} 보드에서 ${finished?'완료 취소':'완료'}">${finished?ji('check'):''}</button>`);}
  for(const el of [...root.querySelectorAll('button.time-block')]){const b=state.blocks.find(b=>b.id===el.dataset.id);if(!b)continue;const i=state.items.find(i=>i.id===b.taskId),wrap=document.createElement('div');wrap.className=el.className;wrap.setAttribute('style',el.getAttribute('style')||'');wrap.dataset.color=colorOf(b,state.items);wrap.classList.add('j-time-wrap');el.before(wrap);wrap.append(el);el.removeAttribute('style');el.className='j-time-title';const done=i?(repeatStatus(i,getDate())?.done??i.status==='done'):!!b.completedAt;wrap.insertAdjacentHTML('beforeend',`<span class="j-time-complete">${i?completion(i,getDate(),true):`<button type="button" class="check ${done?'done':''}" data-action="v3-event-check" data-id="${b.id}" aria-label="${esc(b.title)} 보드에서 완료">${done?ji('check'):''}</button>`}</span>`);}
 }
 function decorateEditor(data,modal){if(!data?.value)return;const i=data.value;if(data.type==='item'){modal.querySelector('#modal-error').insertAdjacentHTML('beforebegin',`<div class="fields space-top">${colorFields(i.color)}${i.kind!=='project'&&!data.hasChildren?routineFields(i):''}</div>`);if(spec(i)){const status=modal.querySelector('#status'),progress=modal.querySelector('#progress');if(status)status.disabled=true;if(progress)progress.disabled=true;}}else if(data.type==='block')modal.querySelector('#modal-error').insertAdjacentHTML('beforebegin',`<div class="fields space-top">${colorFields(i.color,'일정')}</div>`);}
 function itemValues(form,original){const fd=new FormData(form),mode=fd.get('repeatMode'),result={color:validColor(fd.get('color'))};if(mode&&mode!=='legacy'){if(fd.get('kind')==='project')throw new Error('프로젝트에는 반복 목표를 설정할 수 없습니다. 하위 업무에 설정하세요.');const target=Number(fd.get('repeatTarget')),days=fd.getAll('repeatDay').map(Number),start=fd.get('repeatStart');if(!Number.isInteger(target)||target<1||target>(mode==='daily'?20:99))throw new Error(mode==='daily'?'매일 횟수는 1–20회입니다.':'매주 횟수는 1–99회입니다.');if(!days.length)throw new Error('실행 요일을 하나 이상 선택하세요.');if(!/^\d{4}-\d{2}-\d{2}$/.test(start||'')||Number.isNaN(+at(start))||day(at(start))!==start)throw new Error('시작일을 확인하세요.');Object.assign(result,{repeatRule:{mode,target,days,start},recurrence:mode==='weekly'?'weekly':'daily',routinePaused:fd.has('routinePaused'),checkins:original.checkins||[],status:'todo',progress:0,completedAt:null});}else if(mode==='legacy')Object.assign(result,{repeatRule:null,routinePaused:false});return result;}
 async function checkTask(id,d,undo){const i=getState().items.find(i=>i.id===id);if(!i)return;const old=economy(getState());await store.commit(spec(i)?repeatOperations(getState(),id,d,undo):completeOps(getState(),id));const next=economy(getState()),s=repeatStatus(getState().items.find(i=>i.id===id),d);notify(s?`${undo?'1회 취소':'1회 완료'} · ${s.count}/${s.target}회${!undo&&next.xp>old.xp?' · +'+(next.xp-old.xp)+' XP':''}`:i.status==='done'?'완료를 취소했습니다.':`완료했습니다.${next.xp>old.xp?' +'+(next.xp-old.xp)+' XP':''}`,true);refreshDay();}
 async function handle(action,id){if(action==='complete'){const i=getState().items.find(i=>i.id===id);if(i&&!getState().items.some(child=>child.parentId===id)){await checkTask(id,getDate(),spec(i)?repeatStatus(i,getDate()).done:false);return true;}return false;}if(!action.startsWith('v3-'))return false;
  if(action==='v3-check'){const [tid,d,what]=id.split('|');await checkTask(tid,d,what==='undo');}
  if(action==='v3-event-check'){const b=getState().blocks.find(b=>b.id===id);if(b){await store.commit([upsert('blocks',{...b,completedAt:b.completedAt?null:new Date().toISOString()})]);notify('보드의 완료 표시만 변경했습니다. Google 원본은 변경하지 않았습니다.',true);refreshDay();}}
  if(action==='v3-day')openDay(id);
  if(action==='v3-more')openModal(frame('더 살펴보기',`<div class="j-more-menu">${[['stats','통계와 회고','기록에서 나의 리듬 찾기','stats'],['adventure','하루의 숲','모험 · 상점 · 캐릭터 꾸미기','compass'],['projects','프로젝트','큰 목표와 다음 행동','flag'],['settings','연결·설정','계정과 데이터 관리','book']].map(([v,t,sub,ico])=>`<button type="button" data-action="v3-open-view" data-id="${v}">${ji(ico)}<span><strong>${t}</strong><small>${sub}</small></span>${ji('arrow')}</button>`).join('')}</div>`));
  if(action==='v3-open-view'){closeModal(true);setView(id);render();window.scrollTo(0,0);}
  if(action==='v3-range'){journeyUI.range=[7,30,90].includes(+id)?+id:30;journeyUI.end=day();render();}
  if(action==='v3-adventure-tab'){journeyUI.tab=['journey','quests','shop','wardrobe','rewards'].includes(id)?id:'journey';render();}
  if(action==='v3-shop-filter'){journeyUI.shop=id;render();}
  if(['v3-buy','v3-equip','v3-claim','v3-visit','v3-redeem'].includes(action)){if(action==='v3-redeem'){const r=gameState(getState()).customRewards.find(r=>r.id===id);if(!r||!confirm(`‘${r.title}’ 보상에 ${r.cost} 별조각을 사용할까요? 실제 구매나 예약은 진행하지 않습니다.`))return true;}await store.commit(gameOperation(getState(),action.slice(3),id),{remember:false});notify(action==='v3-buy'?'교환하고 장착했습니다.':action==='v3-equip'?'꾸미기를 적용했습니다.':action==='v3-claim'?'퀘스트 보상을 받았습니다.':action==='v3-visit'?`${ZONES.find(z=>z.id===id).name}에 도착했습니다.`:'보상 사용을 기록했습니다.');}
  if(action==='v3-motion'){const g=gameState(getState());await store.commit([{collection:'settings',action:'merge',data:{adventure:{...g,motion:!g.motion}}}],{remember:false});}
  if(action==='v3-reward-delete'){const g=gameState(getState()),r=g.customRewards.find(r=>r.id===id);if(r&&confirm(`‘${r.title}’ 보상을 지울까요? 기존 사용 기록은 남습니다.`))await store.commit([{collection:'settings',action:'merge',data:{adventure:{...g,customRewards:g.customRewards.filter(r=>r.id!==id)}}}],{remember:false});}
  if(action==='v3-export-stats'){const m=statistics(getState(),journeyUI.range,journeyUI.end,journeyUI.category);download(`Dayboard-통계-${m.start}-${m.end}.json`,{period:{start:m.start,end:m.end},meaning:'완료 횟수와 완료 업무의 예상시간. 실측 집중시간이 아님.',completed:m.events.length,activeDays:m.daysActive,onTime:m.onTime,withDeadline:m.dated,estimatedMinutes:m.minutes,byDate:m.daily,categories:m.byCategory,reflections:Object.fromEntries(Object.entries(getState().settings.reflections||{}).filter(([d])=>d>=m.start&&d<=m.end))});notify('통계와 회고를 내보냈습니다. 연결키는 포함하지 않습니다.');}
  return true;
 }
 async function submit(form,data){if(form.id==='reflection-form'){const refs={...getState().settings.reflections};if(!refs[day()]&&Object.keys(refs).length>=730)throw new Error('회고 보관 한도입니다. 백업 후 정리하세요.');refs[day()]={win:(data.win||'').trim(),friction:(data.friction||'').trim(),next:(data.next||'').trim(),energy:data.energy?Number(data.energy):null,updatedAt:new Date().toISOString()};await store.commit([{collection:'settings',action:'merge',data:{reflections:refs}}],{remember:false});reflectionDraft=null;notify('오늘의 회고를 저장했습니다.');return true;}if(form.id==='character-form'){const name=(data.characterName||'').trim();if(!name||name.length>24)throw new Error('이름은 1–24자로 입력하세요.');await store.commit([{collection:'settings',action:'merge',data:{adventure:{...gameState(getState()),name}}}],{remember:false});notify('여행자 이름을 저장했습니다.');return true;}if(form.id==='reward-form'){const g=gameState(getState()),title=(data.rewardTitle||'').trim(),cost=Number(data.rewardCost);if(!title||title.length>100||!Number.isInteger(cost)||cost<5||cost>10000)throw new Error('보상 이름과 비용(5–10000)을 확인하세요.');if(g.customRewards.length>=30)throw new Error('보상은 30개까지 등록할 수 있습니다.');await store.commit([{collection:'settings',action:'merge',data:{adventure:{...g,customRewards:[...g.customRewards,{id:crypto.randomUUID(),title,cost}]}}}],{remember:false});notify('나만의 보상을 추가했습니다.');return true;}return false;}
 function change(e){if(e.target.id==='repeatMode'){const counted=e.target.value!=='legacy';const st=document.querySelector('#status'),pr=document.querySelector('#progress');if(st)st.disabled=counted;if(pr)pr.disabled=counted;}if(e.target.id==='stats-category'){journeyUI.category=e.target.value;render();}}
 function download(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return {handle,submit,itemValues,decorateEditor,decorate,capture,restore,change};
}
