import {Store,esc,promptText} from './core.js';
import {authorizeGoogle,googleReady,calendars} from './google.js';
import {PROJECT_ID,SETUP_SLOT,CLIENT_PATTERN,validateConnection,prepareConnection,connectionSQL,setupError} from './setup-core.js';
let panel,active='workspace',pending=null,sql='',store=null,googleCalendars=[],busy=false,needsReload=false;
let clientDraft='',calendarDraft='',status='',isError=false;
const button=(action,text,primary=false)=>`<button type="button" class="button ${primary?'primary':''}" data-setup-action="${action}">${text}</button>`;
const link=(href,text)=>`<a class="button" target="_blank" rel="noopener noreferrer" href="${esc(href)}">${text}</a>`;
const value=id=>panel.querySelector('#'+id)?.value?.trim()||'';
function message(text,error=false){status=text;isError=error;const el=panel.querySelector('#setup-status');if(el){el.textContent=text;el.dataset.error=String(error);el.scrollIntoView({block:'nearest'});}}
async function copy(text){try{await navigator.clipboard.writeText(text);message('복사했습니다.');}catch{const el=panel.querySelector('textarea');if(el){el.focus();el.select();message('내용을 선택했습니다. 복사해 주세요.');}else throw new Error('클립보드에 접근할 수 없습니다. 표시된 내용을 직접 복사해 주세요.');}}
function saveConnectionFile(c){const blob=new Blob([JSON.stringify(validateConnection(c),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Dayboard-개인연결.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function validSavedConnection(){return store?.snapshot&&/^[a-f0-9]{64}$/.test(store.key)?{format:'dayboard.connection',version:1,projectId:PROJECT_ID,workspaceId:store.snapshot.workspaceId,key:store.key}:null;}
function workspaceView(){const saved=validSavedConnection();if(saved)return `<h3>개인 보드에 연결되어 있습니다.</h3><div class="setup-callout setup-success">저장소 연결 확인 완료 · revision ${Number(store.snapshot.revision)}<br>PC와 모바일에서 같은 연결 파일을 사용하면 같은 보드를 엽니다.</div><div class="setup-actions">${button('download-saved','개인 연결 파일 저장',true)}${button('back','보드로 돌아가기')}</div><p class="setup-note">연결 파일은 비밀번호입니다. 다른 사람과 공유하거나 공개 저장소에 올리지 마세요. 일정 백업에는 연결키가 들어 있지 않습니다.</p><div class="setup-step"><h4>다음 단계</h4><div class="setup-actions">${button('google-tab','Google Calendar 연결')}${button('chat-tab','ChatGPT 연결 확인')}</div></div>`;return `<h3>내 보드의 첫 연결</h3><p>이미 다른 기기에서 사용 중이면 연결 파일을 가져오세요. 처음이라면 본인 Supabase 계정에서 새 빈 보드를 한 번 승인해 주세요.</p><div class="setup-actions">${button('restore','연결 파일 가져오기')}${button('prepare','새 빈 보드 준비',true)}</div><p class="setup-note">기존 보드나 접속키를 변경하지 않습니다. 새 보드에 이전 일정이 자동 이전되지는 않습니다.</p>${pending?`<div class="setup-callout">연결 정보 준비됨 · <strong>서버 생성·연결은 아직 완료되지 않았습니다.</strong><br>아래 생성문은 본인 Supabase SQL Editor에서 직접 실행합니다.</div><div class="setup-step"><h4>1. 생성문 복사 → 본인 계정에서 실행</h4><textarea id="setup-sql" readonly aria-label="새 빈 보드 생성문">${esc(sql)}</textarea><div class="setup-actions">${button('copy-sql','생성문 복사')}${link('https://supabase.com/dashboard/project/'+PROJECT_ID+'/sql/new','Supabase SQL Editor 열기')}</div><p class="setup-note">연결키 원문은 생성문에 포함되지 않습니다. 새 행 하나만 추가하며 권한·요금제·기존 데이터는 변경하지 않습니다. 이미 연결 파일을 가져왔다면 생성문을 실행하지 말고 다음 단계에서 연결을 확인하세요.</p></div><div class="setup-step"><h4>2. 연결 파일 보관 → 연결 확인</h4><div class="setup-actions">${button('download-pending','개인 연결 파일 저장')}${button('verify','연결 확인',true)}</div><p class="setup-note">파일을 안전하게 보관하세요. 이 탭의 준비 정보는 탭을 닫으면 사라질 수 있습니다. 연결 파일이 없으면 새 기기에서 접근할 수 없습니다.</p></div>`:''}`;}
function googleView(){const saved=validSavedConnection();if(!saved)return `<h3>먼저 개인 보드를 연결하세요.</h3><p>Google 설정은 개인 보드에 저장합니다. 샘플 보드에는 계정 설정을 저장하지 않습니다.</p>${button('workspace-tab','개인 보드 연결로',true)}`;const settings=store.snapshot.state.settings;const client=clientDraft||settings.googleClientId||'';const chosen=calendarDraft||settings.googleCalendarId||'primary';return `<h3>Google Calendar 연결</h3><p>이 앱 전용 웹 클라이언트를 등록한 뒤 Google 계정에서 접근에 동의합니다. ChatGPT에 연결된 Google 인증과는 별도입니다.</p><details ${client?'':'open'}><summary>처음 한 번: Google 앱 등록 안내</summary><div class="setup-step"><h4>1. Google Calendar API 사용 설정</h4><p>Google Cloud에서 프로젝트를 선택하고 Calendar API만 사용 설정하세요. 결제 계정 등록이나 유료 업그레이드는 진행하지 마세요.</p>${link('https://console.cloud.google.com/apis/library/calendar-json.googleapis.com','Calendar API 열기')}</div><div class="setup-step"><h4>2. 앱 이름·대상 사용자·웹 클라이언트 등록</h4><p>Google Auth Platform에서 앱 이름을 Dayboard로 설정합니다. 개인 계정은 대상 External의 테스트 사용자에 본인 이메일을 추가하고, 클라이언트 유형은 <strong>웹 애플리케이션</strong>으로 선택합니다.</p>${link('https://console.cloud.google.com/auth/overview','Google 앱 등록 열기')}<p>승인된 JavaScript 원본에 아래 주소를 그대로 추가합니다. 경로와 마지막 슬래시는 넣지 않습니다.</p><code class="setup-origin">${esc(location.origin)}</code>${button('copy-origin','현재 앱 원본 주소 복사')}<p class="setup-note">PC와 모바일 모두 같은 앱 주소를 사용하세요. 다른 배포 주소도 사용할 때만 해당 원본을 추가합니다. 이 토큰 방식에는 리디렉션 URI나 클라이언트 시크릿이 필요하지 않습니다.</p></div></details><div class="setup-step"><h4>3. 클라이언트 ID 입력 → 계정 인증</h4><label for="setup-google-client">웹 클라이언트 ID</label><input id="setup-google-client" value="${esc(client)}" placeholder="…apps.googleusercontent.com" autocomplete="off"><p class="setup-note">Client secret이 아니라 Client ID만 입력합니다.</p><div class="setup-actions">${button('authorize-google',googleReady()?'Google 계정 다시 선택':'Google 계정 인증',true)}</div>${googleReady()?'<div class="setup-callout setup-success">현재 탭에서 Google 인증됨 · 아직 일정을 가져오거나 수정하지 않았습니다.</div>':''}<label for="setup-google-calendar">사용할 캘린더</label>${googleCalendars.length?`<select id="setup-google-calendar">${googleCalendars.map(c=>`<option value="${esc(c.id)}" ${c.id===chosen?'selected':''}>${esc(c.summary||c.id)}${['owner','writer'].includes(c.accessRole)?'':' · 읽기 전용'}</option>`).join('')}</select>`:`<input id="setup-google-calendar" value="${esc(chosen)}" placeholder="primary">`}<div class="setup-actions">${button('save-google','연결 설정 저장',true)}${button('back','보드로 돌아가기')}</div><p class="setup-note">저장 후 앱의 ‘앞뒤 한 달 동기화’를 누르면 가져올 변경을 검토합니다. 승인하기 전에는 보드에 반영하지 않습니다. Google 인증은 현재 탭에서만 유지되며 새로고침·만료 후 다시 인증합니다.</p></div>`;}
function chatView(){const saved=validSavedConnection();return `<h3>지금 쓰는 ChatGPT에서 계획하기</h3><p>‘최신 일정 조회 → 계획 제안 → 사용자 승인 → 저장’ 순서입니다. 다른 대화를 자동 감시하지 않으며 별도 OpenAI API를 호출하지 않습니다.</p>${saved?`<label for="setup-prompt">이 보드 전용 요청</label><textarea id="setup-prompt" readonly>${esc(promptText('최신 저장 내용을 읽고 오늘·이번 주·이번 달 일정을 보여줘. 먼저 조회만 해줘',saved.workspaceId))}</textarea><div class="setup-actions">${button('copy-chat','요청 복사',true)}${link('https://chatgpt.com/','ChatGPT 열기')}</div><div class="setup-callout">ChatGPT에서 <strong>@Supabase</strong>를 선택하고 붙여넣으세요. 이 보드의 ID가 자동 포함됩니다. 연결키나 개인 연결 파일을 붙여넣을 필요는 없습니다.</div>`:`<div class="setup-callout">개인 보드를 연결하면 그 보드의 ID를 포함한 요청을 복사할 수 있습니다. 샘플용 ID로 실제 일정을 조회하지 않습니다.</div>${button('workspace-tab','개인 보드 연결로',true)}`}<p class="setup-note">Google 일정도 ChatGPT에서 다룰 때는 Google Calendar 도구를 함께 선택하세요. 앱은 ChatGPT 도구 선택이나 계정 동의를 대신 수행할 수 없습니다.</p>`;}
function render(){if(!panel)return;panel.innerHTML=`<div class="setup-head"><h2 id="connection-setup-title">연결 설정</h2><button type="button" class="icon-button" aria-label="연결 설정 닫기" data-setup-action="close"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><path d="M6 6l12 12M6 18L18 6"/></svg></button></div><div class="setup-tabs">${[['workspace','1 · 개인 보드'],['google','2 · Google'],['chat','3 · ChatGPT']].map(([id,label])=>`<button type="button" class="setup-tab" aria-pressed="${active===id}" data-setup-tab="${id}">${label}</button>`).join('')}</div><div class="setup-body">${active==='workspace'?workspaceView():active==='google'?googleView():chatView()}<div id="setup-status" class="setup-status" data-error="${isError}" role="status" aria-live="polite">${esc(status)}</div></div>`;}
function back(){if(needsReload){const url=new URL(location.href);url.searchParams.delete('setup');url.hash='';location.replace(url.pathname+url.search);}else{panel.close();document.querySelector('[data-action="refresh"]')?.click();}}
async function readConnection(c){validateConnection(c);const probe=new Store();probe.key=c.key;const snapshot=await probe.rpc('dayboard_read');if(snapshot.workspaceId!==c.workspaceId)throw new Error('연결 파일의 보드 ID와 실제 저장소가 다릅니다. 이전 연결은 변경하지 않았습니다.');probe.snapshot=snapshot;probe.lastRead=Date.now();localStorage.setItem('dayboard.key',c.key);store=probe;sessionStorage.removeItem(SETUP_SLOT);needsReload=true;return snapshot;}
async function act(action){
 if(action==='close'){if(needsReload)back();else panel.close();return;}if(action==='back'){back();return;}
 if(action.endsWith('-tab')){active=action.split('-')[0];status='';render();return;}
 if(action==='prepare'){if(validSavedConnection())throw new Error('이미 개인 보드에 연결되어 있습니다.');if(pending){message('준비한 연결 정보를 유지합니다. 아래 단계를 완료해 주세요.');return;}pending=await prepareConnection();sessionStorage.setItem(SETUP_SLOT,JSON.stringify(pending));sql=await connectionSQL(pending);render();return;}
 if(action==='copy-sql'){await copy(sql);return;}if(action==='copy-origin'){await copy(location.origin);return;}
 if(action==='download-pending'){saveConnectionFile(pending);message('연결 파일을 저장했습니다. 서버 연결 완료를 뜻하지는 않습니다.');return;}
 if(action==='download-saved'){saveConnectionFile(validSavedConnection());message('개인 연결 파일을 저장했습니다. 다른 기기에서 이 파일을 가져오세요.');return;}
 if(action==='restore'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const f=input.files?.[0];if(!f)return;if(f.size>4096)throw new Error('연결 파일은 4KB 이하여야 합니다. 일정 백업이 아닌 연결 파일을 선택하세요.');pending=validateConnection(JSON.parse(await f.text()));sessionStorage.setItem(SETUP_SLOT,JSON.stringify(pending));sql=await connectionSQL(pending);status='파일을 읽었습니다. 기존 보드라면 생성문 실행 없이 연결 확인을 눌러주세요.';render();}catch(e){message(setupError(e),true);}};input.click();return;}
 if(action==='verify'){await readConnection(pending);status='개인 저장소 연결 확인 완료. 보드로 돌아가면 같은 저장소를 사용합니다.';isError=false;render();return;}
 if(action==='authorize-google'&&needsReload)throw new Error('먼저 보드로 돌아가기를 눌러 첫 연결을 마친 뒤 Google을 연결하세요.');
 if(action==='authorize-google'){clientDraft=value('setup-google-client');calendarDraft=value('setup-google-calendar');if(!CLIENT_PATTERN.test(clientDraft))throw new Error('올바른 Google 웹 클라이언트 ID를 입력하세요.');await authorizeGoogle(clientDraft);googleCalendars=await calendars();status='Google 인증과 캘린더 목록 조회를 확인했습니다. 사용할 캘린더를 선택한 뒤 설정을 저장하세요.';render();return;}
 if(action==='save-google'){const client=value('setup-google-client');const calendar=value('setup-google-calendar');if(!CLIENT_PATTERN.test(client)||!calendar)throw new Error('클라이언트 ID와 캘린더를 확인하세요.');if(!googleReady())throw new Error('먼저 Google 계정 인증을 완료하세요.');if(!googleCalendars.some(c=>c.id===calendar))throw new Error('인증된 계정의 목록에서 캘린더를 선택하세요.');store.snapshot=await store.rpc('dayboard_read');await store.commit([{collection:'settings',action:'merge',data:{googleClientId:client,googleCalendarId:calendar}}],{remember:false});clientDraft=client;calendarDraft=calendar;message('Google 연결 설정을 저장했습니다. 보드로 돌아가 동기화를 눌러주세요.');return;}
 if(action==='copy-chat'){await copy(value('setup-prompt'));return;}
}
export async function openSetup(tab='workspace'){
 if(busy)return;active=['workspace','google','chat'].includes(tab)?tab:'workspace';status='';isError=false;
 if(!panel){panel=document.createElement('dialog');panel.id='connection-setup';panel.setAttribute('aria-labelledby','connection-setup-title');document.body.append(panel);panel.addEventListener('click',async e=>{const tabButton=e.target.closest('[data-setup-tab]');if(tabButton&&!busy){clientDraft=value('setup-google-client')||clientDraft;calendarDraft=value('setup-google-calendar')||calendarDraft;active=tabButton.dataset.setupTab;status='';render();return;}const target=e.target.closest('[data-setup-action]');if(!target||busy)return;busy=true;target.disabled=true;try{await act(target.dataset.setupAction);}catch(error){message(setupError(error),true);}finally{busy=false;if(target.isConnected)target.disabled=false;}});panel.addEventListener('close',()=>{if(!needsReload)document.querySelector('[data-action="refresh"]')?.click();});}
 try{const raw=sessionStorage.getItem(SETUP_SLOT);if(raw){pending=validateConnection(JSON.parse(raw));sql=await connectionSQL(pending);}}catch{sessionStorage.removeItem(SETUP_SLOT);pending=null;}
 store=new Store();if(store.key){try{store.snapshot=await store.rpc('dayboard_read');}catch(error){store.snapshot=null;status=setupError(error);isError=true;}}
 render();if(!panel.open)panel.showModal();
}
export function installSetup(){
 function mount(){const root=document.getElementById('app');if(!root||root.querySelector('[data-setup-entry]'))return;const form=root.querySelector('#connect-form');const settings=root.querySelector('.settings-grid');if(form){const entry=document.createElement('div');entry.className='setup-shortcut';entry.dataset.setupEntry='';entry.innerHTML='<button class="button" type="button" data-open-setup="workspace">처음 연결하기 · 다른 기기 연결</button>';form.before(entry);}else if(settings){const entry=document.createElement('div');entry.className='setup-shortcut';entry.dataset.setupEntry='';entry.innerHTML='<span>계정 연결을 단계별로 확인하세요.</span><button type="button" class="button" data-open-setup="workspace">연결 설정 도우미</button>';settings.prepend(entry);}}
 mount();const root=document.getElementById('app');if(root)new MutationObserver(mount).observe(root,{childList:true});
 document.addEventListener('click',e=>{const target=e.target.closest('[data-open-setup],[data-action="google-help"]');if(!target)return;e.preventDefault();e.stopImmediatePropagation();openSetup(target.dataset.openSetup||'google');},true);
 document.addEventListener('keydown',e=>{if(panel?.open)e.stopImmediatePropagation();},true);
 const initial=new URL(location.href).searchParams.get('setup');if(['workspace','google','chat'].includes(initial))openSetup(initial);
}
