"""Assemble ID-linked, attributed example packs without altering words or user state.
Run from repository root. The input artifact is generated by direct-ja-ko038.py.
Complete structural coverage is not a claim of independent linguistic approval.
"""
from pathlib import Path
from collections import Counter,defaultdict
import hashlib,json,os,re
from pykakasi import kakasi
WEB=Path('jlpt-quest');SRC=Path(os.environ.get('KOTOBA_EXAMPLE_INPUT','/tmp/kotoba038-direct'))
OUT=Path(os.environ.get('KOTOBA_EVIDENCE_DIR','/tmp/kotoba038-qa'));OUT.mkdir(parents=True,exist_ok=True)
words=[w for level in ['N5','N4','N3','N2','N1'] for w in json.loads((WEB/f'data/{level}.json').read_text())['words']]
assert len(words)==8451 and len({w['id'] for w in words})==8451
byid={w['id']:w for w in words};original=json.loads((WEB/'data/examples.json').read_text())
legacy={w['id'] for w in words if any(w['word'] in e['targets'] for e in original['entries'])}
assert len(original['entries'])==164 and len(legacy)==482
report=json.loads((SRC/'translation-report.json').read_text());raw=json.loads((SRC/'examples-corpus.json').read_text())
assert report['entries']==6026 and report['wordIds']==6992
assert report['model']=='facebook/m2m100_1.2B' and report['revision']=='11301d1d63d756517521fc0fd34d81c5bff0d946'
corrections={}
if Path('release/examples038/corrections.json').exists():corrections=json.loads(Path('release/examples038/corrections.json').read_text())
reader=kakasi();expanded=[];linked=set();bad=[]
for source in raw['entries']:
 e={k:source[k] for k in ['id','ja','ko','reading','wordIds','source','sourceId','license','dictionaryEntry','surface','translationReview','translationModel','translationRevision','readingReview'] if k in source}
 assert e['translationModel']==report['model'] and e['translationRevision']==report['revision'], 'Incomplete translation checkpoint'
 if e['id'] in corrections:
  fixed=corrections[e['id']];assert fixed['ja']==e['ja'],e['id'];e['ko']=fixed['ko'];e['translationReview']='assistant-edited'
 if not re.search('[가-힣]',e['ko']) or '<unk>' in e['ko'] or len(e['ko'])>220:bad.append(e['id'])
 assert e['wordIds'] and all(i in byid for i in e['wordIds']) and not (set(e['wordIds'])&legacy)
 e['targets']=[];e['independentNativeReview']=False;linked.update(e['wordIds']);expanded.append(e)
assert not bad, 'Repair invalid Korean before publishing: '+str(bad)
assert len(linked)==6992 and len(expanded)==6026
missing={w['id']:w for w in words if w['id'] not in legacy|linked};assert len(missing)==977
lookup=defaultdict(list)
for w in missing.values():lookup[w['word']].append(w['id'])
authored=set();unused=[];count=0
for path in sorted(Path('release/examples038').glob('*.tsv')):
 for lineno,line in enumerate(path.read_text().splitlines(),1):
  if not line.strip():continue
  parts=line.split('\t');assert len(parts)==3,(path,lineno)
  heads,ja,ko=parts;targets=heads.split(',');ids=sorted({i for h in targets for i in lookup.get(h,[])})
  if not ids:unused.append({'file':path.name,'line':lineno,'targets':targets});continue
  assert 5<=len(ja)<=180 and re.search('[가-힣]',ko)
  e={'id':f'kotoba038-{path.stem}-{lineno:04d}','ja':ja,'ko':ko,'reading':''.join(x['hira'] for x in reader.convert(ja)),'wordIds':ids,'targets':[],'authoredTargets':targets,'source':'Kotoba original example, assistant-authored','license':'Project original example; CC BY-SA 4.0 vocabulary linkage','translationReview':'assistant-authored','readingReview':'automated-pykakasi-2.3.0','independentNativeReview':False}
  expanded.append(e);authored.update(ids);count+=1
assert authored==set(missing), 'Uncovered words: '+str([missing[i] for i in set(missing)-authored])
covered=legacy|linked|authored;assert len(covered)==8451
assert len({e['id'] for e in original['entries']+expanded})==len(original['entries'])+len(expanded)
coverage={'version':'0.3.8-internal','totalWords':len(words),'coveredWords':len(covered),'missingWordIds':[],'byLevel':{l:{'total':sum(w['level']==l for w in words),'covered':sum(w['level']==l and w['id'] in covered for w in words)} for l in ['N5','N4','N3','N2','N1']},'existingExampleRecords':len(original['entries']),'newCorpusExampleRecords':6026,'newAuthoredExampleRecords':count,'totalExampleRecords':len(original['entries'])+len(expanded),'corpusWordIds':len(linked),'authoredWordIds':len(authored),'translationReviewCounts':dict(Counter(e['translationReview'] for e in expanded)),'independentNativeReview':False,'readingReview':'Existing authored readings retained; newly generated readings are automatic and may contain ambiguity','productionReleased':False,'model':report['model'],'revision':report['revision'],'unusedAuthoredRows':unused}
pack={'version':1,'generatedAt':'2026-09-28','license':'Tatoeba sentences CC BY 2.0 FR; dictionary-derived linkage CC BY-SA 4.0; see licenses.html','editorialStatus':'Korean machine drafts plus assistant-authored/edited examples. Independent native-speaker review pending.','coverage':coverage,'entries':expanded}
(WEB/'data/examples-expanded.json').write_text(json.dumps(pack,ensure_ascii=False,separators=(',',':')))
(WEB/'data/example-coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2))
(OUT/'example-coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2))
notice='''# Example expansion 0.3.8\n\nJapanese corpus sentences and original English translations: Tatoeba contributors, https://tatoeba.org/ . Per-sentence source IDs are retained and linked from the application. Sentences are used under CC BY 2.0 FR: https://creativecommons.org/licenses/by/2.0/fr/ . Korean translations are adaptations; draft/edited status is recorded.\n\nVocabulary-to-sentence linkage: EDRDG JMdict example edition, https://www.edrdg.org/pub/Nihongo/ . Dictionary material is licensed CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/ . Source archive SHA256: 18a075c6312692b1beb2cf2a0ac5f377874e7d3df5e7412eb7a83117603344cb.\n\nNew project-authored sentences: release/examples038/*.tsv. These are assistant-authored, not independently native-speaker-approved. Unusual spellings/readings in the original vocabulary are not silently changed by this update.\n\nBuild-only direct Korean translation model: facebook/m2m100_1.2B, revision 11301d1d63d756517521fc0fd34d81c5bff0d946, MIT. No model weights are distributed in the application. No user records are used or transmitted.\n\nNew kana readings are generated with pykakasi 2.3.0 and may require contextual correction. Complete coverage means every stored vocabulary ID has Japanese and Korean example text; it does not mean every sentence has passed independent linguistic review.\n'''
p=WEB/'data/licenses/Examples-038-NOTICE.md';p.parent.mkdir(exist_ok=True);p.write_text(notice)
p=WEB/'licenses.html';html=p.read_text();section='''<section class="card" id="examples038"><h2>0.3.8 전체 어휘 예문</h2><p>일본어 용례: Tatoeba 기여자. 각 예문의 출처 링크에서 원문과 기여자를 확인할 수 있습니다. <a href="https://creativecommons.org/licenses/by/2.0/fr/">CC BY 2.0 FR</a>. 어휘 연결 자료: EDRDG JMdict, <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.</p><p>한국어 자동번역 초안과 코토바 작성·수정 예문이 포함됩니다. 추가 예문과 읽기는 독립적인 원어민 전체 검수를 마치지 않았습니다. 단어별 드문 표기와 읽기는 원자료를 유지합니다.</p><p>한국어 번역은 빌드 시 M2M100 1.2B(MIT)로 생성했으며, 앱은 번역 모델을 포함하거나 외부 번역 서비스로 학습 기록을 보내지 않습니다. 예문 듣기는 기기의 일본어 오프라인 음성을 사용합니다.</p><a href="data/licenses/Examples-038-NOTICE.md">상세 출처 및 변경 고지</a></section>'''
if 'id="examples038"' not in html:p.write_text(html.replace('</body>',section+'</body>'))
# Expose pronunciation draft status without claiming that automated readings are verified.
p=WEB/'src/examples.js';s=p.read_text();old="const note=e.translationReview==='machine-draft'?' · 한국어 자동번역 초안':'';"
new="const note=(e.translationReview==='machine-draft'?' · 한국어 자동번역 초안':'')+(showReading&&e.readingReview?.startsWith('automated-')?' · 읽기 자동 생성':'');"
assert old in s or new in s
p.write_text(s.replace(old,new))
paths=['jlpt-quest/data/examples-expanded.json','jlpt-quest/data/example-coverage.json','jlpt-quest/data/licenses/Examples-038-NOTICE.md','jlpt-quest/licenses.html','jlpt-quest/src/examples.js']
Path('/tmp/kotoba038-final-paths.json').write_text(json.dumps(paths))
print(json.dumps(coverage,ensure_ascii=False,indent=2))
