"""Explicit, idempotent 0.4 source corrections. No user records are touched."""
from pathlib import Path
r=Path('jlpt-quest')
p=r/'src/example-quality.js';s=p.read_text().replace("['N4','頼む'","['N5','頼む'")
s=s.replace("register:['N1','N2'].includes(row.level)?'문어·격식':'일상',koTargets:[row.meaning]", "register:'학습 용례',koTargets:[row.meaning.replace(/(하다|되다|함)$/,'')]")
s=s.replace("register:'일상'});}","register:'일상',koTargets:surface==='頼んだ'?[sense==='부탁하다'?'부탁했다':'주문했다']:surface==='聞きました'?['물었습니다']:sense==='돌보다'?['돌봅니다']:sense==='듣다'?['듣는']:['봅니다']});}")
p.write_text(s)
p=r/'src/playlist.js';s=p.read_text().replace("current=null,options={};","current=null,options={},speechTimer=null;")
s=s.replace("const timeout=setTimeout(","const timeout=speechTimer=setTimeout(")
s=s.replace("function stopBrowser(){generation++;","function stopBrowser(){clearTimeout(speechTimer);generation++;")
s=s.replace("if('mediaSession'in navigator){navigator.mediaSession.metadata=", "if('mediaSession'in navigator&&typeof MediaMetadata==='function'){navigator.mediaSession.metadata=")
p.write_text(s)
p=r/'src/examples.js';s=p.read_text()
s=s.replace('<p class="example-meta">${esc(meta.sense)}', '<p class="example-meta">${e.tier?(e.tier===\'easy\'?\'쉬운 문장\':\'자연스러운 문장\')+\' · \':\'\'}${esc(meta.sense)}')
p.write_text(s)
p=r/'src/app.js';s=p.read_text()
s=s.replace("if(a==='practice-character'&&p.ink){const i=Number(el.dataset.index);if(Number.isInteger(i)&&i>=0&&i<p.ink.characters.length)p.ink.active=i;}","if(a==='practice-character'&&p.ink){const i=Number(el.dataset.index),first=p.ink.results.findIndex(x=>!x);if(Number.isInteger(i)&&i>=0&&i<p.ink.characters.length&&(first<0||i<=first))p.ink.active=i;}")
p.write_text(s)
p=r/'src/learning-policy.js';s=p.read_text()
s=s.replace("if(!correct||same||early){result.intervalMs=previous.intervalMs??Math.max(0,base.due-(base.lastAt||now));return result;}","if(!correct){result.intervalMs=600000;return result;}\n if(same||early){result.intervalMs=previous.intervalMs??Math.max(0,base.due-(base.lastAt||now));return result;}")
p.write_text(s)
