"""Explicit corrections after transport; preserve every behavioral assertion."""
from pathlib import Path
import hashlib,json,subprocess,zipfile
p=Path('jlpt-quest/tests/release037-browser.py');text=p.read_text()
text=text.replace('p.wait_for_function("document.querySelector', 'p.wait_for_function("()=>document.querySelector')
p.write_text(text)
# Icons are reproducible original artwork generated by the existing build script.
subprocess.run(['node','scripts/generate-icons.mjs'],cwd='jlpt-quest',check=True)
# Verify every vocabulary and kana ID, and every referenced offline clip.
gate=Path('jlpt-quest/scripts/release-check.mjs');g=gate.read_text()
old="try{const a=await read('../data/audio-coverage.json');if(!a.complete||a.words!==8451)failures.push('Offline audio incomplete');}catch{failures.push('Offline audio evidence missing');}"
new="""try{
 const a=await read('../data/audio-coverage.json'),m=await read('../data/audio-manifest.json');
 const {ALL_KANA}=await import('../src/kana-engine.js');
 const all=[...ALL_KANA];
 for(const l of ['N5','N4','N3','N2','N1'])all.push(...(await read('../data/'+l+'.json')).words);
 if(!a.complete||!m.complete||a.words!==all.length||m.words!==all.length||all.some(w=>!m.clips[w.id]))failures.push('Offline audio incomplete');
 for(const file of new Set(Object.values(m.clips))){const b=await readFile(new URL('../data/audio/'+file,import.meta.url));if(b.length<180||b.subarray(0,4).toString()!=='OggS')throw Error('bad audio');}
}catch{failures.push('Offline audio evidence missing or invalid');}"""
assert old in g, 'audio gate baseline changed'
gate.write_text(g.replace(old,new))
paths=json.loads(Path('/tmp/kotoba037-source-paths.json').read_text())
for name in ['jlpt-quest/scripts/release-check.mjs','jlpt-quest/icon-192.png','jlpt-quest/icon-512.png']:
    if name not in paths:paths.append(name)
Path('/tmp/kotoba037-source-paths.json').write_text(json.dumps(paths))
out=Path('/tmp/kotoba037-qa');out.mkdir(exist_ok=True)
files=[p for base in ['jlpt-quest','kotoba-android','billing-server','release'] for p in Path(base).rglob('*') if p.is_file() and not any(x in p.parts for x in ['assets','audio','.git','__pycache__','build','.gradle']) and p.suffix not in ['.b64','.pyc','.ttf','.otf','.woff','.woff2','.jks','.keystore','.pem','.key']]
(out/'executed-source-checksums.json').write_text(json.dumps({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in files},indent=2))
with zipfile.ZipFile(out/'executed-source.zip','w',zipfile.ZIP_DEFLATED) as z:
    for p in files:z.write(p,str(p))
(out/'executed-browser037.py').write_text(text)
print('CSP-safe QA predicates; generated icons; strict per-ID audio gate. No production approval bypass.')
