"""Small, explicit corrections after the immutable reviewed source transfer.
No product behavior or assertion is bypassed. Keep the executed QA source as evidence.
"""
from pathlib import Path
import hashlib,json
root=Path('jlpt-quest')
test=root/'tests/release036-browser.py'
src=test.read_text()
src=src.replace('import json,os,math','import json,os,math,re')
src=src.replace('import os,json,time,hashlib','import os,json,time,hashlib,re')
old="int(page.locator('.pad-practice').inner_text().split('/')[1].split()[0])"
new="int(re.search(r'/\\s*(\\d+)',page.locator('.pad-practice').inner_text()).group(1))"
src=src.replace(old,new)
test.write_text(src)
evidence=Path('/tmp/kotoba036-qa');evidence.mkdir(exist_ok=True)
(evidence/'executed-browser-test.py').write_text(src)
(evidence/'executed-source-checksums.json').write_text(json.dumps({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in [test,root/'src/app.js',root/'src/stroke-pad.js',root/'release.css']},indent=2))
# Generated bytecode is not a source file and must not be committed.
gitignore=Path('billing-server/.gitignore')
gitignore.write_text('__pycache__/\n*.pyc\n.env\n*.pem\n*.key\n')
print('Checked executable QA source and recorded hashes.')
