import {btn,esc,icon,heading,empty} from './view.js';
import {LEVELS,writingChars} from './catalog.js';
import {SKILLS,keyOf,dayKey,DAY,dueItems,createTargetReview,shuffle} from './course-engine.js';
import {activateSession,restoreParked,lessonName} from './session-controls.js';
import {study,weakItems,createFolder,putInFolder,monthlyStats,spreadPlan,applySpread,undoSpread,recordStroke} from './study-data.js';
import {EXAM_TYPES,startExam,startErrorExam,examItems,selectExam,finishExam} from './exam-engine.js';
import {examplesFor} from './examples.js';
import {auditExamples,quality} from './example-quality.js';
import {startPlaylist,playlistAction,playlistStatus} from './playlist.js';
import {isNative} from './native.js';
import {speechSetupGuide,updateSpeechGuide} from './speech-guide.js';
import {characterStrokes} from './stroke-bank.js';
import {attachStrokePad} from './stroke-pad.js';
export const advanced={tab:'weak',level:'all',category:'all',folder:'all',folderPage:0,selected:new Set(),month:dayKey().slice(0,7),date:dayKey(),minutes:0,sort:false,order:[],drill:null};
let stopMount=()=>{},playlistPoll=null,examPoll=null;
const labels={meaning:'뜻',listening:'듣기',writing:'쓰기'};
const tabs=[['weak','약점'],['folders','내 단어장'],['exam','미니시험'],['commute','연속 듣기'],['strokes','획 연습'],['quality','예문 검토']];
export function hubEntry(){return `<section class="study-entry"><div><h2>맞춤 학습</h2><span>약점 · 단어장 · 미니시험</span></div>${btn('hub-open','열기','soft')}</section>`;}
export const selectedWordButton=w=>btn('select-word',advanced.selected.has(w.id)?'선택됨':'선택','text select-word',`data-id="${w.id}" aria-label="${esc(w.word)} 선택" aria-pressed="${advanced.selected.has(w.id)}"`);
export function wordSelectionBar(){return `<div class="selection-toolbar">${btn('selection-menu',`선택 ${advanced.selected.size}개`,'soft')}${btn('word-shuffle','순서 섞기','text')}${btn('hub-open','폴더 관리','text','data-tab="folders"')}</div>`;}
export function monthlyPanel(state,words){
 const m=monthlyStats(state,words,advanced.month),d=new Date(advanced.month+'-01T12:00:00'),offset=d.getDay(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();
 const cells=Array.from({length:days},(_,i)=>{const key=advanced.month+'-'+String(i+1).padStart(2,'0'),n=(state.daily[key]?.keys.length||0)+(state.practiceLog[key]?.rounds||0);return btn('calendar-day',String(i+1),'calendar-cell activity-'+(n===0?0:n<10?1:n<30?2:3),`data-date="${key}" title="${key} · ${n}건" aria-label="${key} ${n}건" aria-pressed="${advanced.date===key}"`);}).join('');
 const map=LEVELS.map(l=>{const v=words.filter(w=>w.level===l),long=v.filter(w=>SKILLS.every(k=>(state.memory[keyOf(w.id,k)]?.stage??-1)>=3)).length;return `<div class="memory-map-row"><b>${l}</b><div class="skill-track"><i style="width:${v.length?long/v.length*100:0}%"></i></div><span>${long}/${v.length}</span></div>`;}).join('');
 const worst=m.worst?words.find(w=>w.id===m.worst.id):null;
 return `<section class="advanced-panel"><div class="stats-section-title"><h2>월간 기록 · 전체</h2><div>${btn('month-prev','이전','text')}<b>${advanced.month.replace('-','.')}</b>${btn('month-next','다음','text',advanced.month>=dayKey().slice(0,7)?'disabled':'')}</div></div><div class="monthly-kpis"><div><b>${m.newIds.length}</b><span>새로 본 단어</span></div><div><b>${m.mastered}</b><span>장기 복습 진입</span></div><div><b>${m.relapsed}</b><span>다시 틀린 단어</span></div><div><b>${m.total?Math.round(m.correct/m.total*100)+'%':'—'}</b><span>첫 풀이 정답률</span></div></div><div class="calendar-week">${['일','월','화','수','목','금','토'].map(x=>`<span>${x}</span>`).join('')}</div><div class="study-calendar">${'<span></span>'.repeat(offset)}${cells}</div><p class="monthly-day-readout" aria-live="polite">${advanced.date} · 문제 ${state.daily[advanced.date]?.keys.length||0}개 · 단어장 쓰기 ${state.practiceLog[advanced.date]?.rounds||0}회</p><p>${worst?'오답이 가장 많았던 단어: '+esc(worst.word)+' · '+m.worst.count+'회':'이달의 오답 기록이 없습니다.'}</p>${m.weakest?`<p class="weakest-month">오답 비율이 높은 유형: ${m.weakest.level} ${labels[m.weakest.skill]} · ${m.weakest.misses}/${m.weakest.total}회</p>`:'<p class="fine">유형별 정오답이 3회 이상 쌓이면 약점을 표시합니다.</p>'}<p class="stats-note">정답률·재오답·장기 진입은 0.4 사용 이후 기록입니다. 같은 수업의 재시도는 첫 풀이 정답률에서 제외합니다.${m.partial?' 최근 30,000개 응답 기준입니다.':''}</p><h3>급수별 장기 복습 현황</h3>${map}</section>`;
}
function levelScope(){return `<div class="stats-scope">${['all',...LEVELS].map(l=>btn('hub-level',l==='all'?'전체':l,'text'+(advanced.level===l?' selected':''),`data-level="${l}" aria-pressed="${advanced.level===l}"`)).join('')}</div>`;}
function filtered(words){return words.filter(w=>advanced.level==='all'||w.level===advanced.level);}
function weakness(state,words){
 const rows=weakItems(state,filtered(words),advanced.category),ids=[...new Set(rows.map(r=>r.wordId))];
 return `<p class="fine">${ids.length}단어 · ${rows.length}유형. 점은 복습 단계이며 정답 확률이 아닙니다.</p><div class="filter-chips">${[['all','전체'],['meaning','뜻'],['listening','듣기'],['writing','쓰기'],['repeated','3회 이상'],['history','과거 오답 많음']].map(([k,l])=>btn('weak-category',l,advanced.category===k?'soft':'text',`data-category="${k}"`)).join('')}</div>${btn('weak-target-start','약한 유형만 테스트','primary wide',rows.length?'':'disabled')}<div class="weak-list">${ids.slice(0,60).map(id=>{const w=words.find(w=>w.id===id),weak=rows.filter(r=>r.wordId===id);return `<article class="weak-item"><header><button data-action="word" data-id="${id}"><b lang="ja">${esc(w.word)}</b><small>${esc(w.meaning)}</small></button><span>약점: ${weak.map(r=>labels[r.skill]).join(' · ')}</span></header>${SKILLS.map(k=>{const r=state.memory[keyOf(id,k)];return `<div class="weak-meter"><span>${labels[k]}</span><span aria-label="${r?'복습 '+r.stage+'단계':'시험 전'}">${Array.from({length:5},(_,i)=>`<i class="${r&&r.stage>i?'filled':''}"></i>`).join('')}</span><small>${r?'오답 '+(r.independentFailures??r.lapses)+'회':'시험 전'}</small></div>`;}).join('')}</article>`;}).join('')||empty('약점 기록이 없습니다.','문제를 풀면 유형별로 분류됩니다.')}</div>`;
}
export function folderPageItems(state,words){
 const f=study(state).folders.find(f=>f.id===advanced.folder),members=new Set(f?f.wordIds:advanced.selected),list=words.filter(w=>members.has(w.id));
 const pages=Math.max(1,Math.ceil(list.length/100)),page=Math.min(Math.max(0,Number.isInteger(advanced.folderPage)?advanced.folderPage:0),pages-1);
 return {folder:f,list,rows:list.slice(page*100,(page+1)*100),page,pages};
}
function folderView(state,words){
 const folders=study(state).folders,{folder:f,list,rows,page,pages}=folderPageItems(state,words);
 return `<div class="folder-toolbar">${btn('folder-create','새 폴더','primary')}${btn('selection-menu',`선택 ${advanced.selected.size}개`,'soft')}</div><div class="filter-chips">${btn('folder-open','선택한 단어',!f?'soft':'text','data-id="all"')}${folders.map(f=>btn('folder-open',esc(f.name)+` (${f.wordIds.length})`,f.id===advanced.folder?'soft':'text',`data-id="${f.id}"`)).join('')}</div>${f?`<div class="folder-toolbar">${btn('folder-select-all',pages>1?'이 페이지 선택':'폴더 단어 선택','soft')}${btn('folder-rename','이름 변경','text')}${btn('folder-delete','폴더 삭제','text danger')}</div>`:''}<div class="folder-word-list">${rows.map(w=>`<div class="folder-word">${selectedWordButton(w)}<button data-action="word" data-id="${w.id}"><b lang="ja">${esc(w.word)}</b><span>${esc(w.meaning)}</span></button>${f?btn('folder-remove','빼기','text',`data-id="${w.id}"`):''}</div>`).join('')||empty('등록된 단어가 없습니다.','단어장에서 단어를 선택한 다음 폴더에 추가하세요.')}</div>${pages>1?`<div class="folder-pagination" role="navigation" aria-label="폴더 페이지">${btn('folder-page','이전','soft',`data-page="${page-1}" ${page===0?'disabled':''}`)}<span>${page+1} / ${pages} · ${list.length}단어</span>${btn('folder-page','다음','soft',`data-page="${page+1}" ${page===pages-1?'disabled':''}`)}</div>`:''}`;
}

function examHome(state){const e=study(state).exam;return `<section class="advanced-panel"><h2>JLPT 유형 어휘 미니시험</h2><p>20문제 · 10분 · 5유형</p><p class="fine">코토바 자체 연습문제입니다. 공식 JLPT의 전체 구성·배점·난이도를 재현한 모의고사는 아닙니다. 급수별 20문제, 총 100문항의 시작용 문제은행입니다.</p><div class="filter-chips">${LEVELS.map(l=>btn('exam-start',l,'soft',`data-level="${l}" ${e&&!e.finished?'disabled':''}`)).join('')}</div>${e?btn('exam-resume',e.finished?'최근 시험 결과':'진행 중인 시험 이어서','primary wide'):''}${btn('exam-errors-start',`시험 오답 복습 (${(study(state).examWrongIds||[]).length})`,'soft wide',(study(state).examWrongIds||[]).length?'':'disabled')}<p class="fine">화면을 닫아도 제한시간은 계속 흐릅니다. 제출 전에는 정답과 해설을 표시하지 않습니다.</p></section><section class="advanced-panel"><h3>시험 기록</h3>${study(state).exams.slice(-10).reverse().map(e=>`<div class="memory-row"><b>${e.level} · ${dayKey(e.at)}</b><span>${e.correct} / ${e.total}</span></div>`).join('')||'<p>아직 응시 기록이 없습니다.</p>'}</section>`;}
function strokeView(state,words){const allowed=new Set(filtered(words).flatMap(writingChars));const rows=Object.entries(study(state).strokes).filter(([char])=>allowed.has(char)).flatMap(([char,a])=>a.map((r,i)=>({char,index:i,...r}))).filter(r=>r.misses).sort((a,b)=>b.misses-a.misses);const d=advanced.drill;return `<p class="fine">0.4 이후 획 판정 기록입니다. 오답 획 연습은 시험 결과나 단어 숙련도에 합산하지 않습니다.</p>${d?`<section class="advanced-panel"><h2 lang="ja">${esc(d.char)} · ${d.index+1}번째 획</h2><div class="ink-pad snap-pad"><canvas id="weak-stroke" aria-label="오답 획만 연습"></canvas></div><p id="weak-stroke-status" role="status">표시된 획만 써 주세요.</p><div class="writing-help">${btn('stroke-again','다시 쓰기','soft')}${btn('stroke-hint','힌트·정답 획','soft')}</div></section>`:''}<div class="stroke-list">${rows.slice(0,60).map(r=>`<div class="memory-row"><b lang="ja">${esc(r.char)} · ${r.index+1}획</b><span>${r.misses}/${r.attempts}회 불일치</span>${btn('stroke-drill','연습','soft',`data-char="${esc(r.char)}" data-index="${r.index}"`)}</div>`).join('')||empty('획별 오답 기록이 없습니다.','쓰기 문제에서 판정된 획부터 기록합니다.')}</div>`;}
function qualityView(state,words){const a=auditExamples(words,examplesFor);const first=words.filter(w=>examplesFor(w).every(e=>e.translationReview==='machine-draft')).sort((x,y)=>LEVELS.indexOf(x.level)-LEVELS.indexOf(y.level));return `<section class="advanced-panel"><h2>예문 검토 현황</h2><p>어휘 ${a.totalWords.toLocaleString()}개 · 새 작성 용례 ${a.curatedWords}개 어휘</p><table class="audit-table"><thead><tr><th>급수</th><th>전체</th><th>새 작성</th><th>번역 초안만</th></tr></thead><tbody>${LEVELS.map(l=>`<tr><th>${l}</th><td>${a.levels[l]?.total||0}</td><td>${a.levels[l]?.curated||0}</td><td>${a.levels[l]?.draftOnly||0}</td></tr>`).join('')}</tbody></table><p class="fine">새 예문에는 쉬운 문장·자연스러운 문장·뜻 구분을 붙였습니다. 기존 예문은 길이·번역 상태·옛 표현을 전수 점검해 표시합니다. 이 점검은 의미와 문법의 원어민 전수 검수를 대체하지 않습니다.</p><h3>N5부터 검토할 예문</h3>${first.slice(0,20).map(w=>btn('word',esc(w.word)+' · '+w.level,'text',`data-id="${w.id}"`)).join('')}</section>`;}
function commuteHome(state){const p=study(state).playlist;return `<section class="advanced-panel"><h2>연속 듣기</h2><p>단어 → 한국어 뜻 → 일본어 예문</p><div class="playlist-options"><label><input type="checkbox" id="play-meaning" ${p.includeMeaning?'checked':''}> 한국어 뜻</label><label><input type="checkbox" id="play-example" ${p.includeExample?'checked':''}> 예문</label><label><input type="checkbox" id="play-repeat" ${p.repeat?'checked':''}> 목록 반복</label></div><p>${p.ids.length}단어 저장됨 · ${advanced.selected.size}단어 선택됨</p><div class="folder-toolbar">${btn('playlist-selected','선택 단어로 시작','primary',advanced.selected.size?'':'disabled')}${btn('playlist-starred','별표 단어로 시작','soft')}${btn('playlist-weak','약점 단어로 시작','soft')}</div>${btn('playlist-saved','저장된 목록 재생','soft wide',p.ids.length?'':'disabled')}<p class="fine">${isNative()?'Android 앱에서는 화면을 꺼도 재생됩니다. 알림에서 일시정지·이전·다음·정지를 사용할 수 있습니다.':'브라우저에서는 화면을 켜 둔 상태에서 재생합니다. 화면을 끄고 듣기는 Android 앱에서 지원합니다.'} 한국어 뜻 듣기를 켜면 한국어 오프라인 음성도 필요해요.</p><details class="playlist-voice-help"><summary>음성 설치 안내</summary>${speechSetupGuide({includeMeaning:true,settings:true,test:false})}</details><div id="playlist-start-guide"></div></section>`;}
export function hubView(state,words){return `${heading('맞춤 학습')}<div class="hub-tabs">${tabs.map(([k,l])=>btn('hub-tab',l,advanced.tab===k?'soft':'text',`data-tab="${k}"`)).join('')}</div>${['weak','strokes'].includes(advanced.tab)?levelScope():''}${({weak:()=>weakness(state,words),folders:()=>folderView(state,words),exam:()=>examHome(state),commute:()=>commuteHome(state),strokes:()=>strokeView(state,words),quality:()=>qualityView(state,words)}[advanced.tab]||(()=>''))()}${state.parkedSessions?.length?`<section class="advanced-panel"><h3>보관한 학습</h3>${state.parkedSessions.map(s=>btn('parked-resume',esc(lessonName(s)),'soft wide',`data-id="${s.id}"`)).join('')}</section>`:''}`;}
export function examView(state){const e=study(state).exam;if(!e)return examHome(state);const rows=examItems(e);if(e.finished){const r=finishExam(state);return `${heading('미니시험 결과')}<div class="exam-score"><b>${r.correct}</b> / ${r.total}</div><div class="exam-types">${Object.entries(r.byType).map(([k,v])=>`<div><span>${EXAM_TYPES[k]}</span><b>${v.correct} / ${v.total}</b></div>`).join('')}</div>${btn('exam-errors-start','오답 복습','primary wide',(study(state).examWrongIds||[]).length?'':'disabled')}<section class="exam-solutions">${rows.map((q,i)=>`<details><summary>${i+1}. ${e.answers[i]===q.answer?'정답':'오답'} · ${EXAM_TYPES[q.type]}</summary><p>${esc(q.stem)}</p><p>선택: ${e.answers[i]===null?'미응답':esc(q.options[e.answers[i]])}</p><p>정답: ${esc(q.options[q.answer])}</p><p>${esc(q.explanation)}</p></details>`).join('')}</section>${btn('hub-open','맞춤 학습으로','soft wide','data-tab="exam"')}`;}
 const q=rows[e.index],seconds=Math.max(0,Math.ceil((e.deadline-Date.now())/1000));return `<div class="exam-top"><h1>어휘 미니시험</h1><b id="exam-clock" role="timer">${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}</b></div><p>${e.level} · ${e.index+1}/${rows.length} · ${EXAM_TYPES[q.type]}</p><h2 class="exam-stem" lang="ja">${esc(q.stem)}</h2><div class="exam-options">${q.options.map((v,i)=>btn('exam-option',esc(v),e.answers[e.index]===i?'soft selected':'soft',`data-index="${i}" aria-pressed="${e.answers[e.index]===i}"`)).join('')}</div><div class="exam-navigation">${btn('exam-prev','이전','soft',e.index===0?'disabled':'')}${btn('exam-next','다음','primary',e.index===rows.length-1?'disabled':'')}${btn('exam-submit','제출','soft')}</div><div class="exam-grid">${rows.map((_,i)=>btn('exam-jump',String(i+1),e.answers[i]!==null?'soft':'text',`data-index="${i}" aria-label="${i+1}번 ${e.answers[i]!==null?'응답함':'미응답'}"`)).join('')}</div><p class="fine">제한시간이 끝나면 자동 제출됩니다. 나갔다 돌아와도 남은 시간은 늘어나지 않습니다.</p>${btn('hub-open','나중에 이어서','text','data-tab="exam"')}`;
}
export function commuteView(state){return `${heading('연속 듣기')}<section class="commute-player"><strong id="playlist-word" lang="ja">준비</strong><p id="playlist-progress" aria-live="polite"></p><div class="commute-controls">${btn('playlist-prev','이전','soft')}${btn('playlist-play','재생','primary')}${btn('playlist-pause','일시정지','soft')}${btn('playlist-next','다음','soft')}</div>${btn('playlist-stop','재생 종료','text wide')}<p id="playlist-error" role="status"></p><div id="playlist-speech-guide"></div></section>${btn('hub-open','목록 설정','soft wide','data-tab="commute"')}`;}
function selectedItems(words,skill){const ids=[...advanced.selected];return ids.flatMap(wordId=>(skill==='all'?SKILLS:[skill]).map(skill=>({wordId,skill})));}
async function launch(ctx,items,label,minutes=0){ctx.cancelWork();const s=createTargetReview(ctx.state,ctx.words,items,{label,minutes});if(!s)return ctx.toast('복습할 문항이 없습니다.');activateSession(ctx.state,s);ctx.closeModal();if(await ctx.save())ctx.go('lesson');}
function chooseMenu(ctx){ctx.openModal(`${ctx.modalHead(`선택 ${advanced.selected.size}단어`)}<div class="selection-tests">${['meaning','listening','writing','all'].map(k=>btn('selected-test',(labels[k]||'전체')+' 테스트','soft',`data-skill="${k}" ${advanced.selected.size?'':'disabled'}`)).join('')}</div><h3>폴더에 추가</h3><select id="target-folder" aria-label="추가할 폴더">${study(ctx.state).folders.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select>${btn('selection-add-folder','폴더에 추가','primary',study(ctx.state).folders.length&&advanced.selected.size?'':'disabled')}${btn('selection-clear','선택 해제','text')}${btn('playlist-selected','선택 단어 연속 듣기','soft wide',advanced.selected.size?'':'disabled')}`);}
export async function handleAdvanced(a,el,ctx){const {state,words,save,render,toast,go,openModal,closeModal,modalHead}=ctx;
 if(a==='hub-open'||a==='hub-tab'){advanced.tab=el.dataset.tab||'weak';closeModal();go('study-hub');return true;}
 if(a==='hub-level'){advanced.level=el.dataset.level;advanced.drill=null;render();return true;}
 if(a==='weak-category'){advanced.category=el.dataset.category;render();return true;}
 if(a==='weak-target-start'){await launch(ctx,weakItems(state,filtered(words),advanced.category).slice(0,60),'약점 집중');return true;}
 if(a==='timebox-start'){const min=Number(el.dataset.minutes);const items=dueItems(state,words).concat(dueItems(state,words,Date.now(),'preview')).slice(0,100);await launch(ctx,items,`${min}분 복습`,min);return true;}
 if(a==='budget-add'){state.session.budgetMs+=300000;closeModal();await save();render();return true;}
 if(a==='select-word'){const id=el.dataset.id;if(!words.some(w=>w.id===id))return true;if(advanced.selected.has(id))advanced.selected.delete(id);else if(advanced.selected.size<100)advanced.selected.add(id);else toast('최대 100단어까지 선택할 수 있습니다.');const y=scrollY;render();scrollTo(0,y);return true;}
 if(a==='selection-menu'){chooseMenu(ctx);return true;}
 if(a==='selection-clear'){advanced.selected.clear();closeModal();render();return true;}
 if(a==='selection-add-folder'){putInFolder(state,document.querySelector('#target-folder')?.value,[...advanced.selected]);await save();closeModal();render();toast('폴더에 추가했습니다.');return true;}
 if(a==='selected-test'){await launch(ctx,selectedItems(words,el.dataset.skill),'선택 단어 테스트');return true;}
 if(a==='word-shuffle'){advanced.order=shuffle(words.map(w=>w.id));advanced.sort=true;render();return true;}
 if(a==='folder-open'){advanced.folder=el.dataset.id;advanced.folderPage=0;render();return true;}
 if(a==='folder-page'){const {pages}=folderPageItems(state,words),page=Number(el.dataset.page);if(Number.isInteger(page)&&page>=0&&page<pages){advanced.folderPage=page;render();document.querySelector('.folder-toolbar')?.scrollIntoView({block:'start'});}return true;}
 if(a==='folder-create'||a==='folder-rename'){const f=study(state).folders.find(f=>f.id===advanced.folder);openModal(`${modalHead(a==='folder-create'?'새 폴더':'폴더 이름 변경')}<input id="folder-name" maxlength="40" value="${a==='folder-rename'?esc(f?.name||''):''}" aria-label="폴더 이름" placeholder="예: 시험 전날"><div class="modal-actions">${btn(a==='folder-create'?'folder-save':'folder-rename-save','저장','primary')}${btn('close-modal','취소','soft')}</div>`);return true;}
 if(a==='folder-save'||a==='folder-rename-save'){const name=document.querySelector('#folder-name').value.trim();if(a==='folder-save')advanced.folder=createFolder(state,name).id;else{if(!name)throw new Error('이름을 입력하세요.');const f=study(state).folders.find(f=>f.id===advanced.folder);if(study(state).folders.some(x=>x.id!==f.id&&x.name===name))throw new Error('같은 이름이 있습니다.');f.name=name.slice(0,40);}await save();closeModal();render();return true;}
 if(a==='folder-delete'){openModal(`${modalHead('폴더를 삭제할까요?')}<p>단어와 학습 기록은 유지됩니다.</p>${btn('folder-delete-confirm','폴더 삭제','danger')}${btn('close-modal','취소','soft')}`);return true;}
 if(a==='folder-delete-confirm'){study(state).folders=study(state).folders.filter(f=>f.id!==advanced.folder);advanced.folder='all';await save();closeModal();render();return true;}
 if(a==='folder-select-all'){advanced.selected=new Set(folderPageItems(state,words).rows.map(w=>w.id));render();chooseMenu(ctx);return true;}
 if(a==='folder-remove'){putInFolder(state,advanced.folder,[el.dataset.id],true);await save();render();return true;}
 if(a==='exam-start'){startExam(state,el.dataset.level);await save();go('exam');return true;}
 if(a==='exam-resume'){if(study(state).exam&&!study(state).exam.finished&&Date.now()>=study(state).exam.deadline){finishExam(state);await save();}go('exam');return true;}
 if(a==='exam-option'){selectExam(state,Number(el.dataset.index));await save();render();return true;}
 if(['exam-next','exam-prev','exam-jump'].includes(a)){const e=study(state).exam;if(e&&!e.finished){e.index=Math.max(0,Math.min(e.ids.length-1,a==='exam-next'?e.index+1:a==='exam-prev'?e.index-1:Number(el.dataset.index)));await save();render();}return true;}
 if(a==='exam-submit'){openModal(`${modalHead('시험을 제출할까요?')}<p>미응답 문항은 오답으로 처리됩니다.</p>${btn('exam-confirm','제출','primary')}${btn('close-modal','계속 풀기','soft')}`);return true;}
 if(a==='exam-confirm'){finishExam(state);await save();closeModal();render();return true;}
 if(a==='exam-errors-start'){startErrorExam(state);await save();go('exam');return true;}
 if(a==='month-prev'||a==='month-next'){const date=new Date(advanced.month+'-01T12:00:00');date.setMonth(date.getMonth()+(a==='month-prev'?-1:1));advanced.month=dayKey(date).slice(0,7);render();return true;}
 if(a==='calendar-day'){advanced.date=el.dataset.date;render();return true;}
 if(a==='spread-open'){openModal(`${modalHead('복습 일정 분산')}<p>미래 복습을 최대 2일, 남은 간격의 20% 이내에서 앞당깁니다. 이미 기한이 지난 복습은 바꾸지 않습니다.</p><label>하루 기준 <input id="spread-cap" type="number" min="10" max="300" value="60"></label>${btn('spread-preview','변경안 보기','primary')}${study(state).balance?btn('spread-undo','마지막 분산 되돌리기','soft'):''}`);return true;}
 if(a==='spread-preview'){advanced.spread=spreadPlan(state,Number(document.querySelector('#spread-cap').value));openModal(`${modalHead('분산 미리보기')}<p>${advanced.spread.moves.length}개 복습을 앞당깁니다. 기준을 넘는 날짜 ${advanced.spread.unresolvedDays}일은 그대로 남습니다.</p>${btn('spread-apply','이 일정 적용','primary',advanced.spread.moves.length?'':'disabled')}${btn('close-modal','취소','soft')}`);return true;}
 if(a==='spread-apply'){const n=applySpread(state,advanced.spread);await save();closeModal();render();toast(n+'개 일정을 변경했습니다.');return true;}
 if(a==='spread-undo'){const n=undoSpread(state);await save();closeModal();render();toast(n+'개 일정을 복원했습니다.');return true;}
 if(a==='stroke-drill'){const char=el.dataset.char,index=Number(el.dataset.index);if(characterStrokes(char)[index])advanced.drill={char,index,lines:[]};render();return true;}
 if(a==='stroke-again'||a==='stroke-hint'){if(advanced.drill)advanced.drill.lines=[];render();return true;}
 if(['playlist-selected','playlist-starred','playlist-weak','playlist-saved'].includes(a)){
  const p=study(state).playlist;let ids=a==='playlist-selected'?[...advanced.selected]:a==='playlist-starred'?state.starred:a==='playlist-weak'?[...new Set(weakItems(state,words).map(r=>r.wordId))]:p.ids;
  p.ids=ids.slice(0,200);p.includeMeaning=document.querySelector('#play-meaning')?.checked??p.includeMeaning;p.includeExample=document.querySelector('#play-example')?.checked??p.includeExample;p.repeat=document.querySelector('#play-repeat')?.checked??p.repeat;if(a!=='playlist-saved')p.index=0;
  if(!p.ids.some(id=>words.some(w=>w.id===id))){toast('재생할 단어를 선택하세요.');return true;}
  ctx.cancelWork();
  try{await startPlaylist(words,p.ids,{...p,rate:state.settings.rate});await save();closeModal();go('commute');}
  catch(error){const target=playlistGuideTarget('playlist-start-guide');updateSpeechGuide(target,error,{includeMeaning:p.includeMeaning});toast(error.message);}return true;
 }
 if(a.startsWith('playlist-')&&['play','pause','next','prev','stop'].includes(a.slice(9))){try{await playlistAction(a.slice(9));await refreshPlaylist(ctx);}catch(error){const p=document.querySelector('#playlist-error');if(p)p.textContent=error.message;updateSpeechGuide(playlistGuideTarget('playlist-speech-guide'),error,{includeMeaning:study(state).playlist.includeMeaning});toast(error.message);}return true;}
 if(a==='parked-resume'){if(restoreParked(state,el.dataset.id)){await save();go('lesson');}return true;}
 return false;
}
function playlistGuideTarget(id){let target=document.querySelector('#'+id);if(!target){const sheet=document.querySelector('.sheet');if(sheet){target=document.createElement('div');target.id=id;sheet.append(target);}}return target;}
async function refreshPlaylist(ctx){try{const s=await playlistStatus();const word=document.querySelector('#playlist-word');if(!word)return;word.textContent=s.word||'목록 없음';document.querySelector('#playlist-progress').textContent=`${s.total?s.index+1:0} / ${s.total||0} · ${s.playing?'재생 중':'일시정지'}`;document.querySelector('#playlist-error').textContent=s.error||'';updateSpeechGuide(playlistGuideTarget('playlist-speech-guide'),s.error||'',{includeMeaning:study(ctx.state).playlist.includeMeaning});if(study(ctx.state).playlist.index!==s.index){study(ctx.state).playlist.index=s.index||0;await ctx.save();}}catch(e){const p=document.querySelector('#playlist-error');if(p)p.textContent=e.message;updateSpeechGuide(playlistGuideTarget('playlist-speech-guide'),e,{includeMeaning:study(ctx.state).playlist.includeMeaning});}}
export function disposeAdvanced(){stopMount();stopMount=()=>{};clearInterval(playlistPoll);clearInterval(examPoll);}
export function mountAdvanced(ctx){
 const e=study(ctx.state).exam;
 if(location.hash==='#exam'&&e&&!e.finished){let finishing=false;const tick=async()=>{const seconds=Math.max(0,Math.ceil((e.deadline-Date.now())/1000)),clock=document.querySelector('#exam-clock');if(clock)clock.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(!seconds&&!finishing){finishing=true;finishExam(ctx.state);await ctx.save();ctx.closeModal();ctx.render();}};tick();examPoll=setInterval(tick,500);}
 if(location.hash==='#commute'){refreshPlaylist(ctx);playlistPoll=setInterval(()=>refreshPlaylist(ctx),1000);}
 const canvas=document.querySelector('#weak-stroke'),d=advanced.drill;
 if(canvas&&d){const pad=attachStrokePad(canvas,[characterStrokes(d.char)[d.index]],d.lines,{guide:true,motion:ctx.state.settings.motion,width:ctx.state.settings.penWidth,character:d.char,onAttempt(r){recordStroke(ctx.state,d.char,d.index,r.accepted);document.querySelector('#weak-stroke-status').textContent=r.accepted?'획 연습 완료':r.reason;ctx.save();}});stopMount=()=>pad.destroy();}
}
