import {LEVELS,EXPECTED,TITLES,courses,writingChars,writingPattern,validateStoredPack,SOURCE_REV} from './catalog.js';
import {fresh,current,createClass,createReview,submit,next,remediate,unresolved,levelStats,dueItems,dueLabel,dayKey,streak,keyOf,validateState} from './course-engine.js';
import {openStore,loadState,commit,rawState,replaceBackup,ConflictError} from './storage.js';
import {packs,catalog,initializePacks,installPack,packInfo} from './packs.js';
import {btn,icon,esc,mark,ring,wave,heading,empty} from './view.js';
import {attachInk,hasInk} from './ink.js';
import {speak,stopAudio} from './audio.js';
import {isNative,callNative,judgeInk,installBridge} from './native.js';
import {applyMotion,haptic,celebrate} from './motion.js';

const root=document.querySelector('#app'),modal=document.querySelector('#modal-root');
let state=fresh(),words=[],lookup=new Map(),ready=false,saving=false,busy=false,ink=null,storageOK=true,warning='',toastTimer,epoch=0,audioNonce=0,gradeNonce=0;
let filter='due',wordFilter='all',search='',limit=80,courseLimit=24,pendingCourse=null,imported=null,priorFocus=null,downloading=false;
let savedRevision=0,tail=Promise.resolve();
const names={study:'새 단어',audio:'발음 듣기',trace:'한자 따라 쓰기',meaning:'뜻 확인',listening:'듣기 시험',writing:'한자 쓰기 시험'};
const route=()=>location.hash.slice(1)||'home';
const W=id=>lookup.get(id)||state.session?.wordSnapshots?.find(w=>w.id===id);
function mergeWords(){words=catalog();lookup=new Map(words.map(w=>[w.id,w]));for(const w of state.session?.wordSnapshots||[])if(!lookup.has(w.id))lookup.set(w.id,w);}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.className='on show';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.className='',4500);}
function save(){
 const snapshot=structuredClone(state),generation=epoch;
 const job=tail.then(async()=>{if(generation!==epoch||!storageOK)return false;saving=true;
 try{const saved=await commit(snapshot,savedRevision);savedRevision=saved.revision;state.revision=savedRevision;return true;}
 catch(e){epoch++;if(e instanceof ConflictError){state=await loadState();savedRevision=state.revision;mergeWords();toast(e.message);render();}else{storageOK=false;warning='저장에 실패했습니다. 학습을 멈추고 설정에서 백업해 주세요.';toast(warning);render();}return false;}finally{saving=false;}});
 tail=job.catch(()=>false);return job;
}
function cancelWork(){audioNonce++;gradeNonce++;stopAudio();if(isNative())callNative('stopAudio',{},3000).catch(()=>{});busy=false;}
function go(name){if(route()===name)render();else location.hash=name;}
function showReading(w){return state.settings.furigana&&w.reading?`<span class="reading" lang="ja">${esc(w.reading)}</span>`:'';}
function wordHTML(w,large=false){return `<div class="${large?'big-japanese':'japanese'}"><strong lang="ja">${esc(w.word)}</strong>${showReading(w)}</div>`;}
function levelButtons(){return `<div class="level-tabs" role="group" aria-label="학습 급수">${LEVELS.map(l=>`<button data-action="level" data-level="${l}" class="${state.settings.level===l?'active':''}" aria-pressed="${state.settings.level===l}">${l}</button>`).join('')}</div>`;}
const menus=[['home','home','홈'],['course','book','커리큘럼'],['review','refresh','복습'],['words','library','단어장'],['profile','chart','내 기록']];
function nav(mobile=false){return `<nav class="${mobile?'bottom-nav':'side-nav'}" aria-label="${mobile?'모바일 메뉴':'주 메뉴'}">${menus.map(([id,ic,label])=>`<a href="#${id}" class="${route()===id?'active':''}" ${route()===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></a>`).join('')}</nav>`;}
function shell(body){const d=state.daily[dayKey()]?.keys.length||0;return `<aside class="sidebar"><a class="brand" href="#home">${mark()}<span>kotoba</span></a>${nav()}<div class="sidebar-bottom">한 번 더, 내 단어로.<button class="quiet-link" data-action="settings">${icon('settings')}설정</button><a href="./privacy.html">개인정보 · 데이터 안내</a></div></aside><div class="workspace">${warning?`<div class="store-warning" role="alert">${esc(warning)}</div>`:''}<header class="appbar"><a class="mobile-brand" href="#home">${mark()}<b>코토바</b></a><span class="desktop-title">나의 일본어 수업</span><div class="appbar-tools"><button class="reading-toggle ${state.settings.furigana?'active':''}" data-action="furigana" aria-pressed="${state.settings.furigana}" aria-label="히라가나 ${state.settings.furigana?'끄기':'켜기'}"><span lang="ja">あ</span><span>${state.settings.furigana?'켜짐':'꺼짐'}</span></button><button class="icon-btn" data-action="settings" aria-label="설정">${icon('settings')}</button></div></header><div class="layout"><main class="page" id="main">${body}</main><aside class="right-rail"><section class="panel rail-goal">${ring(d,state.settings.goal)}<h3>오늘도 작은 기억을 쌓아요</h3><p>뜻·듣기·쓰기 문제를 풀면<br>오늘의 목표에 반영돼요.</p></section><section class="panel"><h3>수업은 이렇게 흘러가요</h3><ol class="class-flow"><li>새 단어와 뜻 확인</li><li>발음을 듣고 한자 쓰기</li><li>모든 단어의 3유형 시험</li><li>빠진 기억을 다시 확인</li></ol><p class="fine">틀린 문제를 남긴 채 완료되지는 않아요.</p></section><p class="fine rail-note">N5~N1 공개 어휘팩과 한국어 시작 단어를 함께 제공합니다. 단어 수는 설치된 실제 데이터 기준이며, 공식 JLPT 출제 목록은 아닙니다.</p></aside></div></div>${nav(true)}`;}
function resume(){const s=state.session;return s&&!s.finished?`<section class="resume"><div><b>진행 중인 수업이 있어요</b><p>${s.index+1} / ${s.queue.length}단계 · 필기도 저장돼요</p></div>${btn('resume','이어서','soft')}</section>`:'';}
function home(){const l=state.settings.level,list=courses(words,l),c=list.find(c=>!state.completed[c.id])||list[0],stats=levelStats(state,words,l),p=packInfo(l);return `${heading('오늘도, 한 회차만.','쓰고 듣고 확인하면, 내 단어가 돼요.')}${resume()}<section class="panel levels-panel"><div class="section-title"><h2>급수별 학습 현황</h2><span>완료 / 설치 단어</span></div><div class="level-progress-grid">${LEVELS.map(level=>{const st=levelStats(state,words,level);return `<button data-action="level" data-level="${level}" class="level-progress ${level===l?'selected':''}" aria-pressed="${level===l}"><div><b>${level}</b><span>${st.learned}<small> / ${st.total.toLocaleString()}</small></span></div><span class="line-progress"><i style="width:${st.total?st.learned/st.total*100:0}%"></i></span><small>학습 중 ${Math.max(0,st.encountered-st.learned)} · 복습 ${st.due}</small></button>`;}).join('')}</div><p class="fine">‘완료’는 수업의 뜻·듣기·쓰기 시험을 모두 통과한 단어예요.</p></section><section class="hero course-hero"><div class="hero-copy"><span class="hero-label">${l} · ${String(c.index).padStart(2,'0')}회차</span><h2>${esc(c.title)}</h2><p>단어 ${c.wordIds.length}개를 한 수업에서 끝까지.</p><div class="lesson-words">${c.wordIds.map(id=>wordHTML(W(id))).join('')}</div>${btn('start-course',`${icon('next')} 회독 수업 시작`,'primary wide',`data-id="${c.id}" ${storageOK?'':'disabled'}`)}<p class="hero-meta">${c.wordIds.length}단어 학습 → ${c.wordIds.length*3}문제 → 오답 재확인</p></div></section><div class="home-shortcuts"><button class="panel shortcut" data-action="review-start"><span class="soft-icon lavender">${icon('refresh')}</span><div><b>잊기 전에 복습</b><p>${stats.due?`${stats.due}단어가 기다려요`:'예정된 복습을 확인해요'}</p></div>${icon('next')}</button><a class="panel shortcut" href="#course"><span class="soft-icon mint">${icon('book')}</span><div><b>메인 커리큘럼</b><p>${list.length}회차 · ${p.installed.toLocaleString()}단어 설치됨</p></div>${icon('next')}</a></div><p class="page-footnote">${p.complete?'전체 공개 단어팩 설치됨':`${l} 기본 60단어로 시작 중 · 전체팩 ${p.available.toLocaleString()}개 원본 항목 제공`}</p>`;}
function curriculum(){const l=state.settings.level,p=packInfo(l),list=courses(words,l);return `${heading('하나씩 이어지는 수업.','매 회차 5단어, 모든 단어를 쓰고 듣고 시험해요.')}${levelButtons()}<section class="panel pack-banner"><div><span class="label">${l}</span><h2>${TITLES[l]}</h2><p>${p.installed.toLocaleString()}단어 설치 · ${list.length}회차</p><p class="fine">${p.complete?`전체 공개팩 설치됨 · 영어 뜻 ${p.english.toLocaleString()}개`:`기본 한국어 60단어 · 전체팩 원본 ${p.available.toLocaleString()}개`}</p></div>${btn('packs',icon('download')+' 단어팩','soft')}</section><div class="curriculum-list">${list.slice(0,courseLimit).map(c=>{const done=state.completed[c.id],n=c.wordIds.filter(id=>state.learned[id]).length;return `<button class="curriculum-row" data-action="start-course" data-id="${c.id}"><span class="lesson-number ${done?'done':''}">${done?icon('check'):String(c.index).padStart(2,'0')}</span><div><strong>${esc(c.title)}</strong><p lang="ja">${c.wordIds.map(id=>esc(W(id).word)).join(' · ')}</p><small>${n}/${c.wordIds.length}단어 수업 완료</small></div>${icon('next')}</button>`;}).join('')}</div>${list.length>courseLimit?btn('more-courses','수업 더 보기','soft wide'):''}<div class="info-note">${icon('book')}<div>공식 JLPT는 급수별 전체 어휘 목록을 공개하지 않습니다. 기본 단어는 자체 편집 분류이며, 전체팩은 공개 자료의 분류입니다. 전체팩의 미번역 뜻은 영어로 표시되고 검수가 필요합니다.</div></div>`;}
function review(){const rows=dueItems(state,words,Date.now(),filter),due=dueItems(state,words),weak=dueItems(state,words,Date.now(),'weak');return `${heading('다시 만나면, 더 오래.','뜻·한자 쓰기·듣기를 따로 기억해요.')}${levelButtons()}<section class="panel review-summary"><span class="soft-icon lavender">${icon('refresh')}</span><div><h2>${due.length}문제 복습할 시간</h2><p>헷갈린 ${weak.length}문제 · 현재 ${state.settings.level}</p></div>${btn('review-start','복습 시작','primary',due.length?'':'disabled')}</section><div class="filter-chips" role="group" aria-label="복습 필터">${[['due','지금 복습'],['weak','헷갈린 단어'],['all','전체 일정']].map(([id,name])=>`<button class="${filter===id?'active':''}" data-action="filter" data-id="${id}">${name}</button>`).join('')}</div>${filter==='weak'&&rows.length?btn('weak-start','헷갈린 문제만 풀기','soft wide'):''}<section class="panel word-list">${rows.slice(0,80).map(r=>{const w=W(r.wordId);return `<button class="word-row" data-action="word" data-id="${w.id}">${wordHTML(w)}<div class="word-detail"><p>${esc(w.meaning)}</p><small>${names[r.skill]} · ${dueLabel(r.due)}</small></div>${icon('next')}</button>`;}).join('')||empty('지금은 복습할 문제가 없어요.','수업에서 단어를 배운 뒤 다시 만나요.')}</section><div class="panel spaced"><h3>맞힐수록, 복습 간격이 늘어요</h3><p class="interval-copy">10분 → 1일 → 3일 → 7일 → 14일 → 30일</p><p class="fine">틀리면 10분 뒤에 다시 확인해요. 같은 수업에서 다시 맞히거나 너무 일찍 복습한 기록은 다음 복습일을 뒤로 미루지 않아요. 이 간격은 규칙 기반이며 개인별 효과가 검증된 모델은 아닙니다.</p></div>`;}
function matchingWords(){return words.filter(w=>w.level===state.settings.level&&(wordFilter!=='star'||state.starred.includes(w.id))&&(!search||[w.word,w.reading,w.meaning].some(v=>v.toLowerCase().includes(search.toLowerCase()))));}
function wordRows(){const list=matchingWords();return `${list.slice(0,limit).map(w=>`<div class="word-row"><button class="word-button" data-action="word" data-id="${w.id}">${wordHTML(w)}<div class="word-detail"><p>${esc(w.meaning)}</p><small>${state.learned[w.id]?'수업 완료':state.encountered[w.id]?'학습 중':'아직 안 배운 단어'}${w.language==='en'?' · 영어 뜻':''}</small></div></button><button class="icon-btn ${state.starred.includes(w.id)?'starred':''}" data-action="star" data-id="${w.id}" aria-label="${esc(w.word)} 별표" aria-pressed="${state.starred.includes(w.id)}">${icon('star')}</button></div>`).join('')||empty('일치하는 단어가 없어요.','다른 뜻이나 읽기로 찾아보세요.')}${list.length>limit?btn('more-words',`${list.length-limit}개 더 보기`,'soft wide'):''}`;}
function wordPage(){return `${heading('배운 단어를 한곳에.','한자, 히라가나, 뜻으로 찾아보세요.')}${levelButtons()}<label class="word-search">${icon('search')}<input id="search" type="search" value="${esc(search)}" aria-label="단어 검색" placeholder="한자, 읽기, 한국어·영어 뜻" autocomplete="off"></label><div class="filter-chips"><button data-action="word-filter" data-id="all" class="${wordFilter==='all'?'active':''}">전체</button><button data-action="word-filter" data-id="star" class="${wordFilter==='star'?'active':''}">별표</button></div><section class="panel word-list" id="word-results">${wordRows()}</section>`;}
function profile(){const d=state.daily[dayKey()]?.keys.length||0;return `${heading('기억이 쌓인 자리.','맞혔다는 사실과 오래 기억하는 것은 달라요.')}<section class="panel profile-summary">${ring(d,state.settings.goal)}<div><h2>${state.xp.toLocaleString()} XP</h2><p>${streak(state)}일 연속 학습</p><p class="fine">중복 문제에는 오늘의 XP를 다시 주지 않아요.</p></div></section><section class="panel spaced"><h3>장기 복습 단계에 도달한 단어</h3>${LEVELS.map(l=>{const s=levelStats(state,words,l);return `<div class="memory-row"><strong>${l}</strong><span>수업 완료 ${s.learned} · 장기 복습 ${s.mastered}</span></div>`;}).join('')}<p class="fine">‘장기 복습’은 뜻·듣기·쓰기가 모두 7일 간격 이상인 단어예요. 한 번 맞혔다고 완전히 외웠다고 표시하지 않아요.</p></section><div class="settings-quick spaced">${btn('settings',icon('settings')+' 학습 설정','soft')}${btn('export',icon('download')+' 기록 백업','soft')}</div>${state.legacy?'<p class="info-note">이전 버전의 자가평가 기록은 자동 채점 숙련도와 구분해 보관했어요.</p>':''}`;}
function ensureInk(s,w){const chars=writingChars(w);if(!s.ink||s.ink.characters.length!==chars.length)s.ink={characters:chars.map(()=>[]),results:chars.map(()=>false),active:0};return s.ink;}
function questionPage(){const s=state.session;if(!s)return `<div class="focus-shell">${heading('시작한 수업이 없어요.')}${btn('home','홈으로','primary')}</div>`;if(s.finished)return resultPage();const t=current(s),w=W(t.wordId);if(!w)return '<div class="loading">수업 단어를 찾지 못했습니다. 기록을 백업해 주세요.</div>';const training=t.phase==='learn',writing=['trace','writing'].includes(t.skill);let body='';
 if(t.skill==='study')body=`${heading('새로운 단어를 만나요.','뜻을 확인한 뒤 소리로도 기억해요.')}<section class="flashcard intro-card">${wordHTML(w,true)}<p class="word-meaning">${esc(w.meaning)}</p><span class="label">${w.level}${w.language==='en'?' · 영어 뜻':''}</span></section>`;
 if(t.skill==='audio'||t.skill==='listening')body=`${heading(training?'소리까지 함께 기억해요.':'듣고, 알맞은 단어를 골라요.',training?'재생이 끝나면 한자를 직접 써 볼 거예요.':'소리를 듣기 전에는 정답을 제출할 수 없어요.')}<section class="listening-stage ${training?'training-audio':''}">${training?wordHTML(w,true):''}<div class="audio-controls"><button class="audio-main" data-action="listen" aria-label="단어 듣기">${icon('sound')}${wave()}</button><button class="slow-button" data-action="slow" aria-label="천천히 듣기">0.7×</button></div><p class="audio-status" id="audio-status">${s.heard?'재생 완료 · 다시 들어도 괜찮아요.':'재생 버튼을 눌러 주세요.'}</p>${training?`<p class="word-meaning">${esc(w.meaning)}</p>`:''}</section>${training?'':options(t,w)}`;
 if(t.skill==='meaning')body=`${heading('이 단어의 뜻은 무엇일까요?','방금 배운 단어를 기억에서 꺼내 보세요.')}<section class="word-question">${wordHTML(w,true)}</section>${options(t,w)}`;
 if(writing){const inkState=ensureInk(s,w),chars=writingChars(w),active=inkState.active,guide=training||s.assisted;body=`${heading(training?'한자를 직접 써 보세요.':'뜻을 보고, 한자로 써 보세요.',training?'연한 글자 위에 손가락이나 펜으로 써 주세요.':'타이핑이 아니라 화면에 직접 씁니다.')}<div class="ink-prompt"><div><strong>${esc(w.meaning)}</strong><p lang="ja">${guide?esc(w.word):esc(writingPattern(w))}</p>${guide?showReading(w):''}</div><span class="label">${training?'따라 쓰기':'기억해서 쓰기'}</span></div><div class="character-tabs" role="group" aria-label="쓸 글자 선택">${chars.map((c,i)=>`<button data-action="character" data-index="${i}" class="${i===active?'active':''} ${inkState.results[i]?'complete':''}" aria-label="${i+1}번째 글자" ${s.feedback?'disabled':''}>${inkState.results[i]?icon('check'):guide?esc(c):i+1}</button>`).join('')}</div><div class="ink-pad ${guide?'guided':''}"><div class="cross-lines"></div>${guide?`<span class="trace-guide" lang="ja">${esc(chars[active])}</span>`:''}<canvas id="ink-canvas" aria-label="${active+1}번째 한자 손글씨 필기장"></canvas><span class="pad-counter">${active+1} / ${chars.length}</span></div><div class="ink-toolbar">${btn('undo',icon('undo')+' 되돌리기','text',s.feedback?'disabled':'')}${btn('clear',icon('trash')+' 지우기','text',s.feedback?'disabled':'')}${btn('replay',icon('refresh')+' 필기 재생','text')}</div><p class="grader-status" id="grade-status" role="status">${inkState.results[active]?'이 글자는 통과했어요.':isNative()?'일본어 인식 모델이 정답을 판정합니다.':'웹에서는 글자 형태를 비교합니다. 반듯하게 써 주세요.'}</p>${!training&&!s.feedback?btn('hint','정답을 보고 다시 연습','text hint-button'):''}<p class="fine ink-fine">${isNative()?'한자를 히라가나로 바꿔 쓰면 통과하지 않아요.':'웹 형태 비교는 일반 손글씨 인식이 아닙니다. 자유로운 필체는 Android 인식 모델로 검증해야 합니다.'}</p>`;}
 if(s.feedback&&!s.feedback.training)body+=`<section class="answer-reveal">${wordHTML(w)}<p>${esc(w.meaning)}</p>${s.feedback.method==='shape-template'?'<small>웹 형태 비교 판정</small>':''}</section>`;
 return `<div class="focus-shell"><header class="focus-top"><button class="icon-btn" data-action="pause" aria-label="저장하고 나가기">${icon('close')}</button><div class="session-progress"><div class="line-progress"><i style="width:${s.index/s.queue.length*100}%"></i></div></div><button class="reading-toggle" data-action="furigana" aria-pressed="${state.settings.furigana}" aria-label="히라가나 표시 전환"><span lang="ja">あ</span>${state.settings.furigana?'ON':'OFF'}</button></header><div class="session-label"><span>${training?'배우기':'전체 단어 시험'} · ${names[t.skill]}${t.attempt?' · 다시 확인':''}</span><span>${s.index+1}/${s.queue.length}</span></div><main class="question" id="main">${body}</main></div>${footer(s,t)}`;
}
function options(t,w){return `<div class="options" role="group" aria-label="답 선택">${t.options.map((o,i)=>{const selected=state.session.selection===o,correct=o===(t.skill==='listening'?w.word:w.meaning);const f=state.session.feedback;return `<button class="answer-option ${selected?'selected':''} ${f?(correct?'correct':selected?'wrong':''):''}" data-action="option" data-index="${i}" aria-pressed="${selected}" ${f?'disabled':''}><span>${i+1}</span><b ${t.skill==='listening'?'lang="ja"':''}>${esc(o)}</b></button>`;}).join('')}</div>`;}
function canAnswer(){const s=state.session,t=current(s);return !!s&&!s.feedback&&!s.finished&&!!s.selection&&(t.skill!=='listening'||s.heard);}
function footer(s,t){let content='',kind='';if(s.feedback){const f=s.feedback;kind=f.correct?'correct':'wrong';content=`<div class="feedback-copy" role="status"><span class="feedback-mark">${icon(f.correct?'check':'refresh')}</span><div><b>${f.training?'기억에 한 걸음 더.':f.correct?'정답이에요.':'다시 확인할 단어예요.'}</b><p>${f.training?'아직 암기 완료로 기록하지 않아요.':f.correct?`${f.gained?`+${f.gained} XP · `:''}이 유형을 통과했어요.`:f.assisted?'힌트 사용 · 도움 없이 다시 확인해요.':'정답을 확인하고, 뒤에서 한 번 더 풀어요.'}</p></div></div>${btn('next','다음으로','primary')}`;}
 else if(t.skill==='study')content=`<span class="footer-hint">이제 발음을 들어 볼게요.</span>${btn('studied','발음 들으러 가기','primary')}`;
 else if(t.skill==='audio')content=`<span class="footer-hint">재생이 끝나야 다음으로 갈 수 있어요.</span>${btn('audio-done','한자 쓰러 가기','primary',s.heard?'':'disabled')}`;
 else if(['trace','writing'].includes(t.skill)){const q=s.ink,all=q?.results.every(Boolean);content=`<span class="footer-hint">${q?.results.filter(Boolean).length||0}/${q?.results.length||1}글자 통과 · 자동 판정</span>${btn(all?'ink-done':'grade',all?'단어 쓰기 완료':'쓴 글자 확인','primary',all||hasInk(q?.characters[q.active])?'':'disabled')}`;}
 else content=`<span class="footer-hint">${t.skill==='listening'?'소리를 끝까지 듣고 선택하세요.':'알맞은 답을 골라 주세요.'}</span>${btn('answer','정답 확인','primary',canAnswer()?'':'disabled')}`;
 return `<footer class="lesson-footer ${kind}"><div class="lesson-footer-inner">${content}</div></footer>`;
}
function resultPage(){const s=state.session,missing=unresolved(s),ratio=s.originalQuiz?Math.round(s.firstCorrect/s.originalQuiz*100):0;return `<main class="focus-shell"><section class="result"><div class="result-emblem">${icon(s.completed?'check':'refresh')}</div><h1>${s.completed?'이번 회차를 완성했어요.':'아직 남은 기억이 있어요.'}</h1><p>${s.completed?`${s.wordIds.length}단어의 모든 필수 문제를 확인했어요.`:`${missing.length}개 유형을 아직 통과하지 못했어요. 수업은 완료되지 않았어요.`}</p><div class="result-metrics"><div><span>첫 시도 정답률</span><b>${ratio}%</b></div><div><span>획득 경험치</span><b>+${s.earned}</b></div><div><span>남은 유형</span><b>${missing.length}</b></div></div><section class="panel result-words">${s.wordIds.map(id=>{const w=W(id);return `<div class="result-word">${wordHTML(w)}<div class="result-skills">${['meaning','listening','writing'].map(k=>`<span class="${s.passed[keyOf(id,k)]?'done':''}">${names[k].replace(' 시험','').replace(' 확인','')} ${s.passed[keyOf(id,k)]?'✓':'—'}</span>`).join('')}</div></div>`;}).join('')}</section>${missing.length?btn('remediate','남은 문제 다시 풀기','primary wide'):btn('next-course','다음 회차 시작','primary wide')}${btn('finish','학습 홈으로','soft wide')}<p class="fine">수업 완료와 장기 암기는 구분합니다. 복습 일정에 맞춰 다시 확인하세요.</p></section></main>`;}
function render(){ink?.destroy();ink=null;applyMotion(state.settings);root.innerHTML=route()==='lesson'?questionPage():shell(({home,course:curriculum,review,words:wordPage,profile}[route()]||home)());const canvas=document.querySelector('#ink-canvas');if(canvas){const s=state.session,q=s.ink;ink=attachInk(canvas,q.characters[q.active],{width:state.settings.penWidth,onStart(){q.results[q.active]=false;document.querySelector('#grade-status').textContent='쓰기를 마친 뒤 확인을 눌러 주세요.';},onChange(){save();syncButtons();}});if(s.feedback||busy)canvas.style.pointerEvents='none';}}
function syncButtons(){const s=state.session;if(!s)return;const b=document.querySelector('[data-action="answer"]');if(b)b.disabled=!canAnswer()||busy;const g=document.querySelector('[data-action="grade"]');if(g)g.disabled=busy||!hasInk(s.ink?.characters[s.ink.active]);const a=document.querySelector('[data-action="audio-done"]');if(a)a.disabled=!s.heard||busy;}
function modalHead(title){return `<div class="sheet-head"><h2 id="sheet-title">${title}</h2><button class="icon-btn" data-action="close-modal" aria-label="닫기">${icon('close')}</button></div>`;}
function openModal(body){priorFocus=document.activeElement;modal.innerHTML=`<div class="modal-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title">${body}</section></div>`;document.body.classList.add('modal-open');modal.querySelector('button,input,select')?.focus();}
function closeModal(){modal.innerHTML='';document.body.classList.remove('modal-open');priorFocus?.focus?.();}
function settings(){openModal(`${modalHead('내 속도에 맞춰요')}<div class="setting-row"><div><b>히라가나 표시</b><p>단어의 읽기를 켜거나 끄기</p></div><input type="checkbox" data-setting="furigana" aria-label="히라가나 표시" ${state.settings.furigana?'checked':''}></div><div class="setting-row"><div><b>화면 애니메이션</b><p>기기의 동작 줄이기도 반영해요</p></div><input type="checkbox" data-setting="motion" aria-label="화면 애니메이션" ${state.settings.motion?'checked':''}></div><div class="setting-row"><div><b>일본어 재생 속도</b></div><select data-setting="rate" aria-label="재생 속도">${[.7,.85,1].map(n=>`<option value="${n}" ${n===state.settings.rate?'selected':''}>${n}×</option>`).join('')}</select></div><div class="setting-row"><div><b>펜 굵기</b></div><select data-setting="penWidth" aria-label="펜 굵기">${[3,4,6].map(n=>`<option value="${n}" ${n===state.settings.penWidth?'selected':''}>${n}px</option>`).join('')}</select></div><div class="setting-row"><div><b>하루 목표</b></div><select data-setting="goal" aria-label="하루 목표">${[5,10,20,30].map(n=>`<option value="${n}" ${n===state.settings.goal?'selected':''}>${n}문제</option>`).join('')}</select></div><div class="modal-actions">${btn('export','기록 백업','soft')}${btn('import','백업 가져오기','soft')}</div><input id="backup-file" type="file" accept="application/json,.json" class="sr-only"><div class="spaced">${btn('packs',icon('download')+' N5~N1 전체 단어팩','soft wide')}</div>${isNative()?`<p class="info-note">손글씨 인식 모델은 앱이 자동으로 준비합니다. 최초 한 번은 약 20MB 다운로드 때문에 첫 판정이 조금 오래 걸릴 수 있으며, 이후에는 기기 안에서 인식합니다.</p>`:`<p class="info-note">현재 웹 형태 비교 모드입니다. Android의 ML Kit 손글씨 인식과 정확도가 같지 않습니다. 인식이 어려우면 기록을 남기지 않고 재작성을 요청합니다.</p>`}<a class="quiet-link" href="./privacy.html">개인정보 · 콘텐츠 출처 · 앱 제한</a><div class="spaced">${btn('reset','학습 기록 초기화','text danger')}</div>`);}
function packsModal(){openModal(`${modalHead('N5부터 N1까지')}<p class="fine">OpenJLPT 고정 버전에서 내려받습니다. 기본 단어는 한국어, 전체팩 대부분은 영어 뜻이며 한국어 검수가 남아 있어요. 다운로드 시 GitHub에 접속 정보가 전달됩니다. 학습 기록·필기는 전송하지 않습니다.</p><div class="pack-levels">${LEVELS.map(l=>{const p=packInfo(l);return `<div class="pack-level"><div><b>${l}</b><p>${p.installed.toLocaleString()}개 설치 / 원본 ${p.available.toLocaleString()}항목</p><small>${p.complete?`전체팩 · 영어 뜻 ${p.english.toLocaleString()}개`:'한국어 시작 단어 60개'}</small></div>${btn('install-level',p.complete?'다시 받기':'전체팩 설치','soft',`data-level="${l}" ${downloading?'disabled':''}`)}</div>`;}).join('')}</div>${btn('install-all','5개 급수 전체팩 받기','primary wide',downloading?'disabled':'')}<p class="fine spaced">공식 전수 목록이 아닌 공개 자료입니다. 중복 표기는 병합하며 설치 후 실제 단어 수를 표시합니다. 다른 뜻의 예문이 섞인 항목은 일괄 제외합니다.</p><p id="pack-status" role="status"></p>`);}
function detail(id){const w=W(id);if(!w)return;openModal(`${modalHead('단어의 기억')}<div class="detail-word">${wordHTML(w,true)}<p class="word-meaning">${esc(w.meaning)}</p>${btn('word-audio',icon('sound')+' 발음 듣기','soft',`data-id="${w.id}"`)}</div><div class="memory-list">${['meaning','writing','listening'].map(k=>{const r=state.memory[keyOf(id,k)];return `<div class="memory-row"><b>${names[k].replace(' 시험','')}</b><span>${r?dueLabel(r.due):'아직 학습하지 않았어요'}</span></div>`;}).join('')}</div><p class="fine spaced">${w.language==='en'?'영어 원문 뜻 · 한국어 미번역':'한국어 편집 뜻'} · ${w.source==='openjlpt'?'OpenJLPT / EDRDG 기반':'코토바 자체 편집'}<br>전체 어휘와 급수 분류는 출시 전 교육 검수가 필요합니다.</p>`);}
async function startCourse(id,replace=false){if(!storageOK)return toast(warning);const c=courses(words,state.settings.level).find(c=>c.id===id);if(!c)return toast('수업을 다시 선택해 주세요.');if(state.session&&!state.session.finished&&!replace){pendingCourse=id;openModal(`${modalHead('진행 중인 수업이 있어요')}<p>이어서 학습하거나 새 회차로 바꿀 수 있어요. 이미 답한 복습 기록은 유지되지만 현재 수업은 완료되지 않습니다.</p><div class="modal-actions">${btn('resume','이어서','primary')}${btn('replace-course','새 회차 시작','soft')}</div>`);return;}cancelWork();state.session=createClass(state,c,words);closeModal();if(await save())go('lesson');}
async function submitCurrent(result,advanceTraining=false){if(busy||!storageOK)return;const s=state.session,t=current(s);if(!t)return;if(submit(state,t.id,result)){busy=true;const ok=await save();busy=false;if(!ok)return;if(advanceTraining){next(state);await save();}else haptic(state.settings,result.correct);render();document.querySelector('[data-action="next"]')?.focus({preventScroll:true});}}
async function play(slow=false,wordId=null){const s=state.session,t=wordId?null:current(s),w=W(wordId||t?.wordId);if(!w)return;const nonce=++audioNonce,rate=slow?.7:state.settings.rate;const status=document.querySelector('#audio-status');if(status)status.textContent='발음을 재생하고 있어요…';document.querySelector('.audio-main')?.classList.add('playing');
 try{if(isNative())await callNative('speak',{text:w.reading||w.word,rate},25000);else await speak(w.reading||w.word,rate);
 if(nonce!==audioNonce)return;if(t&&state.session===s&&current(s)?.id===t.id&&route()==='lesson'){s.heard=true;await save();if(status)status.textContent='재생 완료 · 이제 다음 단계로 갈 수 있어요.';syncButtons();}}
 catch(e){if(nonce===audioNonce){if(status)status.textContent=e.message;else toast(e.message);}}
 finally{if(nonce===audioNonce)document.querySelector('.audio-main')?.classList.remove('playing');}
}
async function grade(){const s=state.session,t=current(s);if(!s||s.feedback||busy||!storageOK)return;const w=W(t.wordId),q=ensureInk(s,w),index=q.active,expected=writingChars(w)[index],lines=structuredClone(q.characters[index]);if(!hasInk(lines))return;
 busy=true;const nonce=++gradeNonce;const status=document.querySelector('#grade-status');status.textContent='쓴 글자를 확인하고 있어요…';syncButtons();const canvas=document.querySelector('#ink-canvas');canvas.style.pointerEvents='none';
 try{const result=await judgeInk(lines,expected);if(nonce!==gradeNonce||s!==state.session||current(s)?.id!==t.id)return;
 busy=false;if(result.status==='unavailable'||result.status==='ambiguous'){status.textContent=result.reason||'판독하기 어려워요. 지우고 한 글자씩 다시 써 주세요.';if(isNative()&&result.status==='unavailable')toast('손글씨 모델을 자동으로 준비하지 못했어요. 네트워크 연결 후 다시 눌러 주세요.');return;}
 if(result.correct){q.results[index]=true;q.method=result.method;await save();if(q.results.every(Boolean)){render();document.querySelector('#grade-status').textContent='모든 글자를 통과했어요. 단어 쓰기를 완료하세요.';}else{q.active=q.results.findIndex(v=>!v);await save();render();toast(`${index+1}번째 글자 통과. 다음 한자를 써 주세요.`);}}
 else if(t.phase==='learn'){status.textContent=`${result.recognized?`인식한 글자: ${result.recognized}. `:''}모양을 확인하고 다시 써 주세요. 아직 정답으로 기록하지 않았어요.`;}
 else{submit(state,t.id,result);await save();render();}
 }catch(e){if(nonce===gradeNonce){busy=false;status.textContent=e.message||'판독에 실패했습니다. 기록하지 않았어요.';}}
 finally{if(nonce===gradeNonce){busy=false;const c=document.querySelector('#ink-canvas');if(c&&!state.session?.feedback)c.style.pointerEvents='';syncButtons();}}
}
function downloadJSON(object,name){const url=URL.createObjectURL(new Blob([JSON.stringify(object)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportBackup(){await tail;const backup={format:'kotoba-backup',version:1,exportedAt:new Date().toISOString(),state:structuredClone(state),packs:[...packs.values()]};if(isNative())await callNative('exportBackup',{json:JSON.stringify(backup)},120000);else downloadJSON(backup,`kotoba-${dayKey()}.json`);toast('백업을 내보냈어요.');}
function confirmImport(raw){if(raw.length>30e6)throw new Error('백업 파일은 30MB 이하로 제한됩니다.');const value=JSON.parse(raw);if(value.format!=='kotoba-backup'||!Array.isArray(value.packs)||value.packs.length>5)throw new Error('코토바 백업 파일이 아닙니다.');const st=validateState(value.state),data=value.packs.map(validateStoredPack);if(new Set(data.map(p=>p.level)).size!==data.length)throw new Error('중복 급수팩입니다.');imported={state:st,packs:data};openModal(`${modalHead('백업 기록으로 바꿀까요?')}<p>현재 기록을 덮어씁니다. 먼저 현재 기록을 백업해 주세요. 확인하기 전에는 아무 기록도 바뀌지 않습니다.</p><div class="modal-actions">${btn('export','현재 기록 백업','soft')}${btn('confirm-import','기록 교체','primary')}</div>`);}
async function installLevels(levels){if(downloading)return;if(state.session&&!state.session.finished)return toast('진행 중인 수업을 마친 뒤 단어팩을 설치해 주세요.');downloading=true;packsModal();const status=document.querySelector('#pack-status');try{for(const l of levels){status.textContent=`${l} 전체팩을 내려받고 검증하고 있어요…`;const p=await installPack(l);mergeWords();status.textContent=`${l} ${p.words.length}단어 저장 완료`;}
 toast('요청한 전체 단어팩을 설치했어요.');}catch(e){toast(e.message);if(status)status.textContent=e.message;}finally{downloading=false;render();packsModal();}}
document.addEventListener('click',async event=>{
 const el=event.target.closest('[data-action]');if(!el||el.disabled||!ready)return;const a=el.dataset.action,s=state.session,t=current(s);
 try{
 if(a==='settings')settings();
 else if(a==='close-modal')closeModal();
 else if(a==='furigana'){state.settings.furigana=!state.settings.furigana;await save();render();}
 else if(a==='level'){if(s&&!s.finished)return toast('진행 중인 수업을 먼저 마쳐 주세요.');state.settings.level=el.dataset.level;search='';limit=80;courseLimit=24;await save();render();}
 else if(a==='start-course')await startCourse(el.dataset.id);
 else if(a==='replace-course'){await startCourse(pendingCourse,true);pendingCourse=null;}
 else if(a==='resume'){closeModal();go('lesson');}
 else if(a==='pause'){cancelWork();ink?.destroy();ink=null;if(await save())go('home');}
 else if(a==='home'){go('home');}
 else if(a==='studied')await submitCurrent({correct:true,method:'study'},true);
 else if(a==='audio-done')await submitCurrent({correct:true,method:'audio'},true);
 else if(a==='listen')await play();
 else if(a==='slow')await play(true);
 else if(a==='word-audio')await play(false,el.dataset.id);
 else if(a==='option'&&t&&!s.feedback){s.selection=t.options[Number(el.dataset.index)];document.querySelectorAll('.answer-option').forEach(b=>{b.classList.toggle('selected',b===el);b.setAttribute('aria-pressed',String(b===el));});await save();syncButtons();}
 else if(a==='answer'&&canAnswer()){const w=W(t.wordId);await submitCurrent({correct:s.selection===(t.skill==='listening'?w.word:w.meaning),method:'choice'});}
 else if(a==='grade')await grade();
 else if(a==='ink-done'&&s.ink?.results.every(Boolean)){await submitCurrent({correct:true,method:s.ink.method||(isNative()?'mlkit':'shape-template'),assisted:s.assisted===true},t.phase==='learn');}
 else if(a==='character'&&s.ink&&!s.feedback&&!busy){s.ink.active=Number(el.dataset.index);await save();render();}
 else if(a==='undo'&&s.ink&&!s.feedback&&!busy){s.ink.characters[s.ink.active].pop();s.ink.results[s.ink.active]=false;await save();render();}
 else if(a==='clear'&&s.ink&&!s.feedback&&!busy){s.ink.characters[s.ink.active]=[];s.ink.results[s.ink.active]=false;await save();render();}
 else if(a==='replay'){if(state.settings.motion)ink?.replay();else toast('애니메이션이 꺼져 있어요. 설정에서 켤 수 있습니다.');}
 else if(a==='hint'&&!s.feedback){s.assisted=true;await save();render();toast('이번 답은 암기로 인정하지 않고 다시 출제해요.');}
 else if(a==='next'&&!busy){cancelWork();const was=s.finished;if(next(state)){if(await save()){render();scrollTo(0,0);if(!was&&s.finished&&s.completed)celebrate(document.querySelector('#celebration'),state.settings.motion);}}}
 else if(a==='remediate'){if(remediate(state)){await save();render();scrollTo(0,0);}}
 else if(a==='finish'){state.session=null;cancelWork();await save();go('home');}
 else if(a==='next-course'){state.session=null;const c=courses(words,state.settings.level).find(c=>!state.completed[c.id]);await save();if(c)await startCourse(c.id);else{toast('설치된 수업을 모두 마쳤어요. 복습으로 기억을 이어가세요.');go('review');}}
 else if(a==='review-start'||a==='weak-start'){if(s&&!s.finished){toast('진행 중인 수업을 마친 뒤 복습해 주세요.');return;}const nextSession=createReview(state,words,a==='weak-start'?'weak':'due');if(!nextSession){go('review');return;}state.session=nextSession;if(await save())go('lesson');}
 else if(a==='filter'){filter=el.dataset.id;render();}
 else if(a==='word-filter'){wordFilter=el.dataset.id;limit=80;render();}
 else if(a==='word')detail(el.dataset.id);
 else if(a==='star'){const id=el.dataset.id;state.starred=state.starred.includes(id)?state.starred.filter(x=>x!==id):[...state.starred,id];await save();render();}
 else if(a==='more-words'){limit+=80;document.querySelector('#word-results').innerHTML=wordRows();}
 else if(a==='more-courses'){courseLimit+=24;render();}
 else if(a==='packs')packsModal();
 else if(a==='install-level')await installLevels([el.dataset.level]);
 else if(a==='install-all')await installLevels(LEVELS);

 else if(a==='export')await exportBackup();
 else if(a==='import'){if(isNative()){const r=await callNative('importBackup',{},180000);confirmImport(r.json);}else document.querySelector('#backup-file')?.click();}
 else if(a==='confirm-import'&&imported){cancelWork();await tail;const nextState=await replaceBackup(imported.state,imported.packs,savedRevision);epoch++;state=nextState;savedRevision=state.revision;for(const p of imported.packs)packs.set(p.level,p);mergeWords();imported=null;closeModal();go('home');toast('백업을 가져왔어요.');}
 else if(a==='reset')openModal(`${modalHead('기록을 초기화할까요?')}<p>수업, 복습, 필기, 경험치 기록을 지웁니다. 단어팩은 유지됩니다. 삭제 전 백업을 내보내 주세요.</p><div class="modal-actions">${btn('export','먼저 백업','soft')}${btn('confirm-reset','기록 삭제','danger')}</div>`);
 else if(a==='confirm-reset'){cancelWork();await tail;state=await replaceBackup(fresh(),[],savedRevision);savedRevision=state.revision;epoch++;closeModal();go('home');}
 }catch(e){toast(e.message||'작업을 완료하지 못했어요.');}
});
document.addEventListener('input',event=>{if(event.target.id==='search'){search=event.target.value;limit=80;document.querySelector('#word-results').innerHTML=wordRows();}});
document.addEventListener('change',async event=>{
 const k=event.target.dataset.setting;
 if(k&&['furigana','motion','penWidth','rate','goal'].includes(k)){state.settings[k]=['furigana','motion'].includes(k)?event.target.checked:Number(event.target.value);await save();render();}
 if(event.target.id==='backup-file'){const f=event.target.files[0];if(!f)return;try{if(f.size>30e6)throw new Error('백업은 30MB 이하만 가능합니다.');confirmImport(await f.text());}catch(e){toast(e.message);}}
});
document.addEventListener('keydown',event=>{if(!modal.firstChild)return;if(event.key==='Escape'){event.preventDefault();closeModal();}if(event.key==='Tab'){const all=[...modal.querySelectorAll('button:not(:disabled),input:not(.sr-only),select,a[href]')],first=all[0],last=all.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
window.addEventListener('hashchange',()=>{cancelWork();closeModal();if(ready)render();scrollTo(0,0);});
document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelWork();ink?.destroy();ink=null;save();}else if(ready)render();});
window.addEventListener('beforeunload',()=>{cancelWork();});
async function boot(){installBridge();try{await openStore();state=await loadState();savedRevision=state.revision;await initializePacks();mergeWords();ready=true;render();}catch(e){storageOK=false;warning=e.message;ready=true;await initializePacks();mergeWords();root.innerHTML=`<main class="fatal"><h1>기존 기록을 먼저 보호할게요.</h1><p>${esc(e.message)}</p><p>손상된 기록을 새 기록으로 덮어쓰지 않았습니다. 원본 백업을 내려받고 개발자에게 전달해 주세요.</p><button id="raw-backup" class="btn primary">원본 기록 백업</button></main>`;document.querySelector('#raw-backup').onclick=async()=>{try{downloadJSON(await rawState(),'kotoba-recovery.json');}catch{toast('저장소 접근이 차단되어 백업도 읽을 수 없습니다. 다른 브라우저에서 확인하세요.');}};}
 if('serviceWorker'in navigator&&!isNative()&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
boot();
window.addEventListener('kotoba-back',()=>{if(modal.firstChild){closeModal();return;}if(route()==='lesson'){document.querySelector('[data-action="pause"]')?.click();return;}if(route()!=='home'){go('home');return;}if(isNative())callNative('requestExit',{},120000).catch(()=>{});});
