import {WORDS,WORD_MAP,UNITS,STEPS,SKILLS} from './content.js';
import {STORAGE_KEY,DAY,defaults,validateState,dayKey,uid,shuffle,recordKey,unitProgress,unitUnlocked,nextStep,createSession,currentTask,answerTask,skipTask,advance,isCorrect,reviews,isWeak,streak,dueLabel,masteredCount} from './engine.js';
import {icon,mascot,button,esc} from './ui.js';
import {speak,stopAudio,voices,hasSpeech} from './audio.js';
import {attachCanvas} from './handwriting.js';
const app=document.querySelector('#app'), modalRoot=document.querySelector('#modal-root');
let state=defaults(),storageWarning='',rawBackup=null,storageWritable=true;
try {const raw=localStorage.getItem(STORAGE_KEY);if(raw){try{state=validateState(JSON.parse(raw));}catch{rawBackup=raw;storageWarning='기존 기록을 읽지 못했어요. 원본을 보존 중입니다. 설정에서 백업한 후 초기화해 주세요.';storageWritable=false;}}}
catch {storageWarning='기기 저장소를 사용할 수 없어요. 이 탭에서만 학습되며, 설정에서 기록을 내보낼 수 있어요.';}
let selectedUnit=null,reviewFilter='due',wordFilter='all',searchTerm='',drawCleanup=null,toastTimer,previousFocus=null,deferredInstall=null,audioRequest=0;
function save(){state.revision++;if(!storageWritable)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{storageWarning='학습 기록을 기기에 저장하지 못했어요. 설정에서 백업해 주세요.';toast(storageWarning);}}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4500);}
function route(){return location.hash.slice(1).split('?')[0]||'learn';}
function go(page){if(route()===page)render();else location.hash=page;}
function allLevelWords(){return WORDS.filter(w=>w.level===state.settings.level);}
function activeUnit(){const units=UNITS.filter(u=>u.level===state.settings.level);return units.find(u=>u.id===selectedUnit)||units.find(u=>unitUnlocked(state,u.id)&&unitProgress(state,u.id).laps===0)||units[0];}
function navMarkup(mobile=false){const due=reviews(state).length;const tabs=[['learn','home','학습'],['review','refresh','복습'],['practice','pen','연습'],['words','library','단어장'],['profile','chart','내 기록']];return `<nav class="${mobile?'mobile-nav':'nav'}" aria-label="주 메뉴">${tabs.map(([id,ic,label])=>`<a href="#${id}" class="${mobile?'':'nav-item '}${route()===id?'selected':''}" ${route()===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span>${!mobile&&id==='review'&&due?`<span class="counter">${due}</span>`:''}</a>`).join('')}</nav>`;}
function shell(content){const d=state.daily[dayKey()]||{count:0};return `<aside class="sidebar"><a class="brand" href="#learn">${icon('sprout')}kotoba</a><div class="brand-sub">JLPT QUEST</div>${navMarkup()}<div class="sidebar-foot"><strong>한 번 더, 내 단어로.</strong><br>작은 회독이 만드는 큰 변화<br><br>${button('settings',icon('settings')+' 학습 설정','ghost')}</div></aside><div class="workspace">${storageWarning?`<div class="storage-banner">${esc(storageWarning)}</div>`:''}<header class="topbar"><div class="top-left"><strong>JLPT</strong><label class="sr-only" for="level-select">학습 레벨</label><select id="level-select" class="level-select"><option ${state.settings.level==='N5'?'selected':''}>N5</option><option ${state.settings.level==='N4'?'selected':''}>N4</option></select><span>나만의 단어 여행</span></div><div class="stats"><span class="stat" aria-label="${streak(state)}일 연속 학습">${icon('flame')}${streak(state)}<span class="small">일</span></span><span class="stat xp" aria-label="누적 ${state.xp} 경험치">${icon('bolt')}${state.xp}<span class="small">XP</span></span><span class="stat level">${icon('sprout')}Lv. ${1+Math.floor(state.xp/200)}</span><button class="icon-btn settings-top" data-action="settings" aria-label="설정">${icon('settings')}</button></div></header><div class="body-grid"><main class="main" id="main">${content}</main><aside class="rail"><section class="rail-panel"><div class="eyeline"><h3>오늘의 작은 목표</h3><span class="pill green">${Math.min(100,Math.floor(d.count/state.settings.goal*100))}%</span></div><div class="goal-line">${icon('bolt')}<div class="progress"><span style="width:${Math.min(100,d.count/state.settings.goal*100)}%"></span></div><strong>${d.count}/${state.settings.goal}</strong></div><p>완벽하지 않아도 괜찮아요.<br>오늘 ${state.settings.goal}번, 기억을 꺼내 보세요.</p></section><section class="rail-panel">${mascot('happy','float')}<h3 style="text-align:center">모찌와 한 걸음 더!</h3><p style="text-align:center">틀려도 괜찮아. 다시 만날수록<br>우리의 기억은 더 단단해져.</p>${button('quick-review',icon('refresh')+' 복습하러 가기','secondary wide')}</section><div><a class="rail-link" href="#practice">${icon('pen')}직접 쓰고, 소리로 기억하기</a><a class="rail-link" href="#words">${icon('library')}내 단어장 살펴보기</a><div class="notice">N5 · N4 각 24단어의 <strong>체험용 초안</strong>입니다. 레벨 분류는 자체 편집 기준이며 공식 JLPT 어휘 목록이 아닙니다.</div></div></aside></div></div>${navMarkup(true)}`;}
function resumeBanner(){const s=state.session;if(!s||s.finished)return '';return `<div class="resume-panel"><div><strong>아직 끝나지 않은 여행이 있어요</strong><small>${Math.min(s.index+1,s.queue.length)} / ${s.queue.length}문제 · 답한 기록은 저장됐어요</small></div>${button('resume','이어서','blue')}</div>`;}
function home(){const u=activeUnit(),p=unitProgress(state,u.id),next=nextStep(state,u.id);return `${resumeBanner()}<div class="welcome"><div><h1>한 번 더, 내 단어로.</h1><p>오늘의 작은 회독으로<br>일본어와 한 걸음 더 가까이.</p></div>${mascot()}</div><section class="unit-banner"><div><div class="unit-small">${u.level} · CHAPTER ${u.id.split('-')[1]} · ${p.laps+1}회독</div><h2>${u.title}</h2><p>${u.subtitle}</p></div>${icon(u.icon)}</section><div class="chapter-tabs" aria-label="챕터 선택">${UNITS.filter(x=>x.level===u.level).map((x,i)=>`<button class="chapter-tab ${x.id===u.id?'selected':''}" data-action="unit" data-id="${x.id}" ${unitUnlocked(state,x.id)?'':'disabled'}>${i+1}장${unitProgress(state,x.id).laps?' ✓':''}${!unitUnlocked(state,x.id)?' · 잠김':''}</button>`).join('')}</div><div class="lesson-path">${STEPS.map((s,i)=>{const done=p.completed.includes(s.id),current=next.id===s.id,locked=!done&&!current&&p.laps===0;return `<div class="lesson-row ${locked?'locked':''}"><button aria-label="${s.title}${locked?' · 이전 단계 완료 필요':''}" class="node ${s.id==='boss'?'boss ':''}${current?'current':done?'done':''}" data-action="lesson" data-unit="${u.id}" data-skill="${s.id}" ${locked?'disabled':''}>${icon(done?'check':locked?'lock':s.icon)}</button><div class="node-text">${current?'<span class="tag">여기서 시작!</span>':''}<strong>${s.title}</strong><p>${s.sub}</p></div></div>`;}).join('')}</div><div class="path-end">${icon('flag')}한 챕터를 마치면 다음 여행이 열려요</div><div class="home-cta">${button('lesson',`${icon(next.icon)} ${p.completed.length?'이어서 회독하기':'오늘의 회독 시작'}`,'primary wide',`data-unit="${u.id}" data-skill="${next.id}"`)}<p class="subnote">하트 제한 없이, 내 속도로. 틀린 단어는 다시 만나요.</p></div>`;}
function heading(title,sub){return `<div class="page-heading"><h1>${title}</h1><p>${sub}</p></div>`;}
function reviewPage(){const due=reviews(state),weak=reviews(state,'weak'),all=reviews(state,'all'),upcoming=all.filter(r=>r.due>Date.now());const list=reviews(state,reviewFilter);return `${heading('기억을 단단하게.','잊기 전에 한 번, 헷갈리면 한 번 더.')}<section class="feature-panel">${mascot(due.length?'think':'happy')}<div><h2>${due.length?`${due.length}개의 기억이 기다려요`:'복습 시간을 기다려요'}</h2><p>${due.length?'뜻 · 쓰기 · 듣기를 따로 확인해요.':upcoming.length?`다음 복습은 ${dueLabel(upcoming[0].due)}예요.`:'새 단어를 배우면 복습 일정이 생겨요.'}</p>${button(due.length?'due-review':'go-learn',due.length?'지금 복습하기':'새 단어 배우기','primary')}</div></section><div class="review-counts"><div class="count-box"><strong>${due.length}</strong><span>지금 복습할 문제</span></div><div class="count-box"><strong>${weak.length}</strong><span>약한 기억</span></div><div class="count-box"><strong>${upcoming.length}</strong><span>다음 복습 예정</span></div></div><div class="segment" aria-label="복습 필터">${[['due','복습 예정'],['weak','오답 모아보기'],['all','전체 일정']].map(([id,label])=>`<button class="${reviewFilter===id?'selected':''}" data-action="review-filter" data-id="${id}">${label}</button>`).join('')}</div>${reviewFilter==='weak'&&weak.length?button('weak-review','오답 집중 복습','secondary wide'):''}<div class="word-list">${list.slice(0,40).map(r=>reviewRow(r)).join('')||`<div class="empty">${icon('sprout')}${reviewFilter==='weak'?'아직 헷갈린 기록이 없어요.':'지금 표시할 복습 문제가 없어요.'}</div>`}</div><div class="notice"><strong>복습은 이렇게 돌아가요</strong><br>처음 정답 → 10분 → 1일 → 3일 → 7일 → 14일 → 30일. 예정된 복습에서 맞힐 때 간격이 늘어나요. 틀리거나 힌트를 쓰면 같은 세션에서 다시 만나고, 10분 뒤 복습으로 돌아가요. 정해진 시간보다 일찍 연습해도 예정일을 뒤로 미루지 않아요.<br><br>단어 하나도 뜻·쓰기·듣기를 각각 기록하므로, 문제 수와 단어 수는 달라요.</div>`;}
function reviewRow(r){const w=WORD_MAP[r.wordId];return `<div class="word-row"><button class="word-main" data-action="word" data-id="${w.id}"><strong lang="ja">${w.word}<span class="reading">(${w.reading})</span></strong><p>${w.meaning}</p></button><div class="word-meta"><span class="pill ${isWeak(r)?'blue':'green'}">${SKILLS[r.skill]}</span><p>${dueLabel(r.due)}</p></div></div>`;}
function practicePage(){return `${resumeBanner()}${heading('나에게 맞는 연습.','손으로 쓰고, 귀로 듣고, 기억으로 답해요.')}<div class="practice-menu">${[['read','book','카드 회독','뜻을 가리고 기억 꺼내기'],['writing','pen','단어 직접 쓰기','일본어 입력 · 가나 도움'],['listening','headphones','단어 듣기','보통 속도 · 천천히 듣기'],['handwriting','hand','손으로 쓰기','손가락 필기 · 자가평가']].map(([id,ic,title,sub])=>`<button class="practice-card" data-action="practice" data-skill="${id}"><span class="symbol">${icon(ic)}</span><strong>${title}</strong><p>${sub}</p></button>`).join('')}</div><div class="spacer"></div>${button('practice',icon('spark')+' 뜻 맞히기 연습','secondary wide','data-skill="meaning"')}<div class="spacer"></div>${button('practice',icon('trophy')+' 뜻 · 쓰기 · 듣기 섞어서 풀기','secondary wide','data-skill="boss"')}<div class="notice"><strong>한 번에 8단어, 종합 연습은 12문제</strong><br>${state.settings.level} 체험 단어에서 골라 출제해요. 오답은 최대 두 번 추가로 등장해요. 이미 오늘 푼 같은 단어·같은 유형에는 XP를 중복 지급하지 않아요.<br><br>직접 입력은 자동 채점합니다. 손으로 쓰기는 그림을 정답과 비교하는 자가평가이며, 필기 인식·자동 채점은 아직 제공하지 않아요.</div>`;}
function wordMatches(){return allLevelWords().filter(w=>(wordFilter!=='starred'||state.starred.includes(w.id))&&(!searchTerm||[w.word,w.reading,w.meaning].some(t=>t.toLowerCase().includes(searchTerm.toLowerCase()))));}
function wordRow(w){return `<div class="word-row"><button class="word-main" data-action="word" data-id="${w.id}"><strong lang="ja">${w.word}${state.settings.furigana?`<span class="reading">(${w.reading})</span>`:''}</strong><p>${w.meaning}</p></button><div class="word-meta">${['meaning','writing','listening'].filter(k=>state.memory[recordKey(w.id,k)]).length}/3 유형<div class="skill-dots" aria-hidden="true">${['meaning','writing','listening'].map(k=>`<span class="${state.memory[recordKey(w.id,k)]?'on':''}"></span>`).join('')}</div></div><button class="icon-btn ${state.starred.includes(w.id)?'active':''}" data-action="star" data-id="${w.id}" aria-label="${w.word} 즐겨찾기" aria-pressed="${state.starred.includes(w.id)}">${icon('star')}</button></div>`;}
function wordsPage(){return `${heading('내 단어 모음집.','뜻도, 예문도, 다음 복습도 한곳에서.')}<div class="eyeline"><span class="pill green">${state.settings.level} · ${allLevelWords().length}단어 체험</span><span class="small muted">등록된 단어만 표시해요</span></div><label class="search-box">${icon('search')}<input id="word-search" type="search" value="${esc(searchTerm)}" placeholder="단어, 읽기 또는 한국어 뜻 검색" aria-label="단어 검색" autocomplete="off"></label><div class="segment"><button class="${wordFilter==='all'?'selected':''}" data-action="word-filter" data-id="all">전체 단어</button><button class="${wordFilter==='starred'?'selected':''}" data-action="word-filter" data-id="starred">별표 단어</button></div>${wordFilter==='starred'&&wordMatches().length?button('star-practice','별표 단어 직접 쓰기','secondary wide'):''}<div class="word-list" id="word-results">${wordMatches().map(wordRow).join('')||'<div class="empty">해당하는 단어가 없어요.</div>'}</div>`;}
function profilePage(){const today=state.daily[dayKey()]||{count:0,xp:0};const writing=Object.entries(state.memory).filter(([key,r])=>key.endsWith(':writing')&&r.successes>0).length;const listening=Object.entries(state.memory).filter(([key,r])=>key.endsWith(':listening')&&r.successes>0).length;const laps=Object.values(state.units).reduce((n,p)=>n+p.laps,0);const badges=[['sprout','첫 기억의 씨앗','처음으로 한 문제 학습하기',state.xp>0],['pen','손끝의 기억','서로 다른 8단어 쓰기 정답',writing>=8],['headphones','귀가 열리는 순간','서로 다른 8단어 듣기 정답',listening>=8],['trophy','한 바퀴의 힘','챕터 1회독 완성하기',laps>0],['flame','꾸준함의 시작','3일 연속 학습하기',streak(state)>=3]];return `${heading('차곡차곡, 내 기록.','남과 비교하지 않고, 어제의 나보다 한 걸음.')}<div class="eyeline"><h2>Lv. ${1+Math.floor(state.xp/200)} · 단어 탐험가</h2><button class="icon-btn" data-action="settings" aria-label="학습 설정">${icon('settings')}</button></div><div class="progress"><span style="width:${state.xp%200/2}%"></span></div><p class="subnote">다음 레벨까지 ${200-state.xp%200} XP</p><div class="stat-grid"><div class="big-stat">${icon('flame')}<strong>${streak(state)}일</strong><p>연속 학습</p></div><div class="big-stat">${icon('bolt')}<strong>${state.xp}</strong><p>누적 경험치</p></div><div class="big-stat">${icon('trophy')}<strong>${laps}회</strong><p>완료한 챕터 회독</p></div><div class="big-stat">${icon('book')}<strong>${masteredCount(state)}단어</strong><p>${state.settings.level} 뜻·쓰기·듣기 모두 7일 단계 이상</p></div></div><h3>이번 7일의 발자국</h3><div class="week">${Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-6+i);const d=state.daily[dayKey(date)];return `<div class="day ${d?.count?'active':''}"><span>${d?.count?icon('check'):date.getDate()}</span>${['일','월','화','수','목','금','토'][date.getDay()]}</div>`;}).join('')}</div><div class="eyeline"><h3>오늘 ${today.count}/${state.settings.goal}번 학습</h3><span class="pill green">+${today.xp} XP</span></div><div class="spacer"></div><h3>나의 작은 성취</h3>${badges.map(([ic,title,sub,earned])=>`<div class="badge-row ${earned?'earned':''}"><span class="badge-symbol">${icon(ic)}</span><div><strong>${title}${earned?' · 달성':''}</strong><p>${sub}</p></div></div>`).join('')}<div class="notice">이 기기·브라우저에 저장되는 개인 기록이에요. 브라우저 데이터를 지우거나 기기를 바꾸기 전에는 설정에서 백업을 내보내 주세요. 계정 동기화는 아직 없습니다.</div>`;}
function lessonPage(){const s=state.session;if(!s){go('learn');return '';}if(s.finished)return resultPage(s);const t=currentTask(s),w=WORD_MAP[t.wordId];const fb=s.feedback;const skillLabel=t.skill==='read'?'카드 회독':SKILLS[t.skill];const count=Math.min(100,s.index/s.queue.length*100);let content='';
  if(t.skill==='read')content=`<h1>이 단어, 떠오르나요?</h1><p class="prompt-sub">뜻을 먼저 떠올린 뒤 확인해 보세요.</p><div class="word-card"><button class="icon-btn" data-action="speak-word" data-id="${w.id}" aria-label="단어 듣기">${icon('sound')}</button><div class="jp" lang="ja">${w.word}</div>${state.settings.furigana?`<div class="furigana" lang="ja">(${w.reading})</div>`:''}${s.revealed?`<div class="meaning">${w.meaning}</div>`:'<div class="spacer"></div><span class="sub">어떤 뜻이었을까요?</span>'}</div>${s.revealed?example(w):''}`;
  if(t.skill==='meaning')content=`<h1>알맞은 뜻을 골라 주세요.</h1><p class="prompt-sub">단어의 뜻을 기억에서 꺼내 보세요.</p><div class="word-card"><div class="jp" lang="ja">${w.word}</div>${state.settings.furigana?`<div class="furigana" lang="ja">(${w.reading})</div>`:''}</div>${options(t,s)}`;
  if(t.skill==='writing')content=`<h1>일본어로 직접 써 볼까요?</h1><p class="prompt-sub">히라가나 또는 단어의 한자 표기로 입력하세요.</p><div class="word-card"><span class="pill green">이 뜻을 가진 단어는?</span><div class="spacer"></div><div class="korean-prompt">${w.meaning}</div><span class="sub">${w.level} · 학습한 단어로 답해 주세요</span></div><label class="sr-only" for="word-answer">일본어 답안</label><input id="word-answer" class="write-input ${fb?(fb.correct?'correct':'wrong'):''}" lang="ja" value="${esc(s.draft||'')}" placeholder="일본어로 입력…" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" enterkeyhint="done" ${fb?'disabled':''}><div class="input-help"><span>일본어 키보드로 자유롭게 입력해요</span>${button('kana-help','글자 도움','ghost',fb?'disabled':'')}</div>${s.assisted?`<p class="small muted">도움 사용 · ${w.reading.length}글자. 도움을 쓴 답은 숙련 단계가 오르지 않아요.</p><div class="kana-board">${[...new Set(shuffle([...w.reading,'の','あ','る']))].map(c=>`<button class="kana" data-action="kana" data-char="${c}" ${fb?'disabled':''}>${c}</button>`).join('')}<button class="kana" data-action="backspace" aria-label="한 글자 지우기" ${fb?'disabled':''}>⌫</button></div>`:''}`;
  if(t.skill==='listening')content=`<h1>듣고, 뜻을 찾아 주세요.</h1><p class="prompt-sub">단어는 숨겨져 있어요. 재생 버튼을 눌러 보세요.</p><div class="audio-stage"><button class="big-audio" data-action="listen" aria-label="일본어 단어 듣기">${icon('sound')}</button><button class="slow-audio" data-action="listen-slow" aria-label="일본어 단어 천천히 듣기">0.7×</button></div><p class="audio-status" id="audio-status">${s.heard?'다시 들어도 괜찮아요.':'음성을 재생한 뒤 답할 수 있어요.'}</p><div class="spacer"></div><div id="audio-error"></div>${options(t,s)}${!fb?button('skip-audio','지금 소리를 들을 수 없어요','ghost skip-audio'):''}`;
  if(t.skill==='handwriting')content=`<h1>손끝으로 단어를 기억해요.</h1><p class="prompt-sub">${w.meaning} — 손가락·펜·마우스로 써 보세요.</p><div class="draw-wrap"><div class="draw-guide" lang="ja">${s.trace?w.word:''}</div><canvas id="writing-canvas" aria-label="손글씨 연습 칸"></canvas></div><div class="draw-tools">${button('draw-undo',icon('undo')+' 되돌리기','secondary',fb?'disabled':'')}${button('draw-clear',icon('trash')+' 지우기','secondary',fb?'disabled':'')}${button('draw-guide',icon('eye')+' 따라 쓰기','secondary',fb?'disabled':'')}</div><p class="self-note">필기 자동 채점 없이 정답과 비교하는 자가평가예요.</p>${s.revealed?`<div class="example"><strong lang="ja">${w.word}(${w.reading})</strong><div class="ko">${w.meaning}</div></div>`:''}`;
  if(fb && !['read','handwriting'].includes(t.skill))content+=`<div class="example"><strong lang="ja">${w.word}(${w.reading})</strong> · ${w.meaning}<div class="ko">${w.example}<br>${w.translation}</div></div>`;
  return `<div class="lesson-shell"><div class="lesson-top"><button class="icon-btn" data-action="pause" aria-label="저장하고 학습 홈으로">${icon('close')}</button><div class="progress" role="progressbar" aria-label="학습 진행" aria-valuenow="${Math.round(count)}" aria-valuemin="0" aria-valuemax="100"><span style="width:${count}%"></span></div><span class="stat">${icon('bolt')}${s.earned}</span></div><div class="session-meta"><span>${esc(skillLabel)}${t.retry?' · 오답 다시 만나기':''}</span><span>${s.index+1} / ${s.queue.length}${s.combo>=3?` · ${s.combo}연속 정답!`:''}</span></div><main class="question">${content}</main></div>${lessonFooter(s,t,w)}`;
}
function example(w){return `<div class="example"><div lang="ja">${w.example}</div><div class="ko">${w.translation}</div></div>`;}
function options(t,s){return `<div class="answer-grid" role="group" aria-label="정답 선택">${t.options.map((choice,i)=>{const correct=choice===WORD_MAP[t.wordId].meaning;const selected=s.selected===choice;const cls=s.feedback?(correct?'correct':selected?'wrong':''):(selected?'selected':'');return `<button class="option ${cls}" data-action="option" data-index="${i}" aria-pressed="${selected}" ${s.feedback?'disabled':''}><span class="keycap">${i+1}</span>${esc(choice)}</button>`;}).join('')}</div>`;}
function canCheck(){const s=state.session,t=currentTask(s);if(!t||s.feedback)return false;if(t.skill==='writing')return !!s.draft?.trim();if(t.skill==='listening')return !!s.selected&&!!s.heard;return !!s.selected;}
function lessonFooter(s,t,w){const f=s.feedback;let cls='',body='';if(f){cls=f.skipped||f.assisted?'assisted':f.correct?'good':'bad';const title=f.skipped?'기록하지 않고 넘어갈게요.':f.assisted?'도움을 받아 한 번 더!':f.correct?(t.retry?'다시 떠올렸어요!':'잘했어요!'):'괜찮아요. 다시 만나면 돼요.';const sub=f.skipped?'듣기 성공·경험치·복습 일정에는 반영하지 않아요.':t.skill==='read'?'회독은 자가평가로 기록해요. 뜻 퀴즈와 별도 일정이에요.':f.correct&&!f.assisted?`${f.gained?`+${f.gained} XP · `:''}정답을 확인했어요. 복습 예정일은 기록에서 볼 수 있어요.`:'다른 문제 뒤에 다시 등장해요. 복습 일정은 10분 뒤예요.';body=`<div class="feedback-inner" role="status"><span class="feedback-icon">${icon(f.correct&&!f.assisted?'check':'refresh')}</span><div><strong>${title}</strong><p>${sub}</p></div></div>${button('next','계속하기','primary')}`;}else if(['read','handwriting'].includes(t.skill)){if(s.revealed)body=`<div class="footer-ratings">${button('rate-again','아직 헷갈려요','secondary')}${button('rate-good',t.skill==='handwriting'?'기억했어요 · 자가평가':'떠올렸어요','primary')}</div>`;else body=`<span class="footer-tip">${t.skill==='read'?'바로 넘기기 전에 뜻을 먼저 떠올려요.':'직접 쓴 뒤 정답과 비교해요.'}</span>${button('reveal',t.skill==='read'?'뜻 확인하기':'쓴 단어 확인하기','primary',t.skill==='handwriting'&&!s.strokes?.length?'disabled':'')}`;}else body=`<span class="footer-tip">실수해도 괜찮아요. 다시 만나면 기억나요.</span>${button('check','정답 확인','primary',canCheck()?'':'disabled')}`;return `<footer class="lesson-footer ${cls}"><div class="footer-inner">${body}</div></footer>`;}
function resultPage(s){const accuracy=Math.round(s.initialCorrect/s.total*100),review=s.config.review;const title=s.skipped?'오늘도 한 걸음 나아갔어요!':s.passed?'작은 기억이 자랐어요!':'조금만 더 연습해 볼까요?';return `<div class="lesson-shell"><main class="result">${mascot('happy')}<h1>${title}</h1><p>${s.config.lesson&&s.passed?'학습 단계가 저장됐어요. 다음 걸음도 함께해요.':s.skipped?'소리를 들을 수 없었던 문제는 기록에서 제외했어요.':!s.passed?'챌린지는 첫 시도 70% 이상에서 완료돼요. 오답부터 다시 다져요.':'복습 기록과 경험치가 저장됐어요.'}</p><div class="result-stats"><div class="result-stat">획득 경험치<strong>+${s.earned}</strong></div><div class="result-stat">첫 시도 정답률<strong>${accuracy}%</strong></div><div class="result-stat">최고 연속 정답<strong>${s.bestCombo}</strong></div></div><div class="notice">${s.failed.length?`헷갈린 ${s.failed.length}개 유형은 복습에서 다시 만날 수 있어요. `:'한 번의 정답이 완전한 암기를 뜻하지는 않아요. '}${s.rescues?`${s.rescues}번 다시 떠올린 기억도 있어요. `:''}${s.skipped?`${s.skipped}문제를 건너뛰었으므로 해당 학습 단계는 완료되지 않았어요.`:'일정에 맞춰 다시 확인해요.'}</div>${button('finish','학습 홈으로','primary wide')}${button('finish-review',icon('refresh')+' 복습 기록 보기','secondary wide')}</main></div>`;}
function render(){drawCleanup?.();drawCleanup=null;app.innerHTML=route()==='session'?lessonPage():shell(({learn:home,review:reviewPage,practice:practicePage,words:wordsPage,profile:profilePage}[route()]||home)());if(route()==='session'&&currentTask(state.session)?.skill==='handwriting'&&!state.session.finished){const canvas=document.querySelector('#writing-canvas');if(canvas){state.session.strokes||=[];drawCleanup=attachCanvas(canvas,state.session.strokes,()=>{save();const b=document.querySelector('[data-action="reveal"]');if(b)b.disabled=!state.session.strokes.length;});if(state.session.feedback)canvas.style.pointerEvents='none';}}}
function openModal(content){previousFocus=document.activeElement;modalRoot.innerHTML=`<div class="modal-overlay"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title">${content}</section></div>`;modalRoot.querySelector('button,input,select')?.focus();}
function closeModal(){modalRoot.innerHTML='';previousFocus?.focus?.();}
function modalHead(title){return `<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-btn" data-action="close-modal" aria-label="닫기">${icon('close')}</button></div>`;}
function wordDetail(id){const w=WORD_MAP[id];if(!w)return;openModal(`${modalHead('단어의 기억')}<div class="detail-word"><h1 lang="ja">${w.word}</h1><div class="reading" lang="ja">(${w.reading})</div><div class="meaning">${w.meaning}</div><div class="detail-audio">${button('speak-word',icon('sound')+' 듣기','secondary',`data-id="${id}"`)}${button('speak-slow','0.7× 천천히','secondary',`data-id="${id}"`)}</div></div>${example(w)}<div class="spacer"></div><h3>다음에 만날 때</h3>${Object.entries(SKILLS).map(([key,label])=>{const r=state.memory[recordKey(id,key)];return `<div class="memory-row"><strong>${label}</strong><span>${r?`${dueLabel(r.due)} · ${isWeak(r)?'재학습':`${r.stage+1}단계`}`:'아직 학습하지 않았어요'}</span></div>`;}).join('')}<div class="spacer"></div>${button('star',icon('star')+(state.starred.includes(id)?' 별표에서 빼기':' 별표 단어에 추가'),'secondary wide',`data-id="${id}" data-detail="true"`)}`);}
function settings(){openModal(`${modalHead('내 속도로 공부하기')}<div class="settings-row"><div><strong>하루 학습 목표</strong><small>단어·유형별 첫 학습을 셉니다</small></div><select data-setting="goal" aria-label="하루 학습 목표">${[10,20,30].map(n=>`<option value="${n}" ${n===state.settings.goal?'selected':''}>${n}번</option>`).join('')}</select></div><div class="settings-row"><div><strong>후리가나 표시</strong><small>단어(읽기) 형식 · 쓰기·듣기 정답은 숨김</small></div><input data-setting="furigana" type="checkbox" aria-label="후리가나 표시" ${state.settings.furigana?'checked':''}></div><div class="settings-row"><div><strong>기본 듣기 속도</strong><small>현재 일본어 음성 ${voices().length}개</small></div><select data-setting="rate" aria-label="기본 듣기 속도">${[0.7,0.9,1].map(n=>`<option value="${n}" ${n===state.settings.rate?'selected':''}>${n}×</option>`).join('')}</select></div><div class="spacer"></div><h3>기록을 안전하게 보관해요</h3><p>기록은 이 브라우저에만 저장됩니다. 백업 파일을 다른 기기에서 가져올 수 있어요. 가져오기는 기존 기록을 대체하므로 먼저 백업하세요.</p><div class="dialog-actions">${button('export',icon('download')+' 백업 내보내기','secondary')}${button('import',icon('upload')+' 백업 가져오기','secondary')}</div><input class="sr-only" id="import-file" type="file" accept="application/json,.json" aria-label="백업 JSON 파일">${rawBackup?button('export-raw','읽지 못한 원본 백업','secondary wide'):''}<div class="spacer"></div>${button('install',icon('sprout')+' 홈 화면에서 사용하기','secondary wide')}<div class="notice">기기 TTS를 사용하며 음질·발음과 오프라인 재생 가능 여부는 설치된 일본어 음성에 따라 달라요. 원어민 녹음과 발음 점수는 아직 없습니다.<br><br>N3 · N2 · N1 콘텐츠, 계정 동기화, 앱스토어 버전은 후속 개발 항목입니다.</div><div class="spacer"></div>${button('reset','이 기기의 학습 기록 초기화','ghost wide')}`);}
function start(config,replace=false){if(state.session&&!state.session.finished&&!replace){openModal(`${modalHead('진행 중인 학습이 있어요')}<p>새로 시작하면 현재 문제 묶음만 바뀝니다. 이미 답한 학습 기록과 복습 일정은 유지돼요.</p><div class="dialog-actions">${button('resume','이어서 학습','primary')}${button('replace-session','새 연습 시작','secondary')}</div>`);pendingConfig=config;return;}const s=createSession(state,config);if(!s){toast(config.starred?'별표 단어를 먼저 추가해 주세요.':'지금 해당하는 복습 문제가 없어요.');return;}state.session=s;closeModal();save();go('session');}
let pendingConfig=null;
async function playWord(id,rate){const w=WORD_MAP[id];if(!w)return;try{await speak(w.reading,rate??state.settings.rate);}catch(e){toast(e.message);}}
async function playQuestion(slow=false){const s=state.session,t=currentTask(s);if(!t||t.skill!=='listening')return;const request=++audioRequest;const status=document.querySelector('#audio-status');if(status)status.textContent='일본어 음성을 준비하고 있어요…';try{await speak(WORD_MAP[t.wordId].reading,slow?0.7:state.settings.rate);if(request!==audioRequest||state.session!==s||currentTask(s)?.id!==t.id||route()!=='session')return;s.heard=true;save();document.querySelector('#audio-status').textContent='소리를 듣고 뜻을 골라 주세요.';document.querySelector('#audio-error').innerHTML='';syncCheck();}catch(e){if(request!==audioRequest||currentTask(state.session)?.id!==t.id||route()!=='session')return;document.querySelector('#audio-status').textContent='음성 재생을 확인하지 못했어요.';document.querySelector('#audio-error').innerHTML=`<p class="audio-error">${esc(e.message)}</p>`;}}
function syncCheck(){const b=document.querySelector('[data-action="check"]');if(b)b.disabled=!canCheck();}
function doAnswer(correct){const s=state.session;if(!s||s.feedback)return;answerTask(state,correct,{assisted:!!s.assisted});save();stopAudio();render();document.querySelector('[data-action="next"]')?.focus({preventScroll:true});}
function next(){const s=state.session;advance(state);Object.assign(s,{draft:'',selected:null,heard:false,strokes:[],trace:false});audioRequest++;stopAudio();save();render();scrollTo(0,0);}
function downloadJson(value,name){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',async e=>{
  const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,s=state.session,t=currentTask(s);
  if(a==='settings')settings();else if(a==='close-modal')closeModal();
  else if(a==='unit'){selectedUnit=el.dataset.id;render();}
  else if(a==='lesson'){const unit=el.dataset.unit,skill=el.dataset.skill;if(!unitUnlocked(state,unit))return;start({unit,skill,lesson:true});}
  else if(a==='practice')start({skill:el.dataset.skill});
  else if(a==='star-practice')start({skill:'writing',starred:true});
  else if(a==='due-review')start({review:'due'});
  else if(a==='weak-review')start({review:'weak'});
  else if(a==='quick-review'){if(reviews(state).length)start({review:'due'});else go('review');}
  else if(a==='go-learn')go('learn');
  else if(a==='review-filter'){reviewFilter=el.dataset.id;render();}
  else if(a==='word-filter'){wordFilter=el.dataset.id;render();}
  else if(a==='word')wordDetail(el.dataset.id);
  else if(a==='star'){const id=el.dataset.id;state.starred=state.starred.includes(id)?state.starred.filter(x=>x!==id):[...state.starred,id];save();if(el.dataset.detail)wordDetail(id);else render();}
  else if(a==='resume'){closeModal();go('session');}
  else if(a==='replace-session'&&pendingConfig){start(pendingConfig,true);pendingConfig=null;}
  else if(a==='pause'){audioRequest++;stopAudio();save();go('learn');}
  else if(a==='speak-word')playWord(el.dataset.id);
  else if(a==='speak-slow')playWord(el.dataset.id,0.7);
  else if(a==='listen')playQuestion();else if(a==='listen-slow')playQuestion(true);
  else if(a==='option'&&t&&!s.feedback){s.selected=t.options[Number(el.dataset.index)];save();document.querySelectorAll('.option').forEach(b=>{const chosen=b===el;b.classList.toggle('selected',chosen);b.setAttribute('aria-pressed',String(chosen));});syncCheck();}
  else if(a==='check'&&canCheck()){doAnswer(t.skill==='writing'?isCorrect(WORD_MAP[t.wordId],s.draft):s.selected===WORD_MAP[t.wordId].meaning);}
  else if(a==='reveal'&&s&&!s.feedback){s.revealed=true;save();render();}
  else if(a==='rate-good'&&s?.revealed)doAnswer(true);else if(a==='rate-again'&&s?.revealed)doAnswer(false);
  else if(a==='next')next();
  else if(a==='skip-audio'&&t?.skill==='listening'){audioRequest++;stopAudio();skipTask(state);save();render();}
  else if(a==='kana-help'&&t?.skill==='writing'&&!s.feedback){s.assisted=true;save();render();document.querySelector('#word-answer')?.focus({preventScroll:true});}
  else if((a==='kana'||a==='backspace')&&t?.skill==='writing'&&!s.feedback){s.draft=a==='kana'?(s.draft||'')+el.dataset.char:[...(s.draft||'')].slice(0,-1).join('');document.querySelector('#word-answer').value=s.draft;save();syncCheck();}
  else if(a.startsWith('draw-')&&t?.skill==='handwriting'&&!s.feedback){s.strokes||=[];if(a==='draw-clear')s.strokes=[];if(a==='draw-undo')s.strokes.pop();if(a==='draw-guide'){s.trace=!s.trace;s.assisted=true;}save();render();}
  else if(a==='finish'||a==='finish-review'){state.session=null;save();go(a==='finish'?'learn':'review');}
  else if(a==='export'){downloadJson(state,`kotoba-backup-${dayKey()}.json`);toast('백업 파일을 내려받았어요.');}
  else if(a==='export-raw')downloadJson(rawBackup,`kotoba-original-${dayKey()}.json`);
  else if(a==='import')document.querySelector('#import-file')?.click();
  else if(a==='install'){if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;}else openModal(`${modalHead('홈 화면에 두고 공부해요')}<p><strong>iPhone · iPad</strong><br>Safari에서 이 앱을 연 뒤 공유 메뉴 → ‘홈 화면에 추가’를 선택하세요.<br><br><strong>Android</strong><br>Chrome 메뉴 → ‘홈 화면에 추가’ 또는 ‘앱 설치’를 선택하세요.<br><br>설치 메뉴가 없는 브라우저에서는 웹페이지로 이용할 수 있어요. 처음 방문 이후 앱 화면을 캐시하며, 듣기 오프라인 지원은 기기의 일본어 음성에 따라 달라요.</p>`);}
  else if(a==='reset'){openModal(`${modalHead('학습 기록을 초기화할까요?')}<p>이 브라우저의 진도, 경험치, 복습 일정이 삭제됩니다. 복구하려면 먼저 백업을 내보내 주세요.</p><div class="dialog-actions">${button('export','먼저 백업하기','secondary')}${button('confirm-reset','기록 삭제','danger')}</div>`);}
  else if(a==='confirm-reset'){state=defaults();storageWritable=true;rawBackup=null;storageWarning='';selectedUnit=null;save();closeModal();go('learn');}
});
document.addEventListener('input',e=>{if(e.target.id==='word-answer'&&state.session&&!state.session.feedback){state.session.draft=e.target.value.slice(0,200);save();syncCheck();}if(e.target.id==='word-search'){searchTerm=e.target.value;document.querySelector('#word-results').innerHTML=wordMatches().map(wordRow).join('')||'<div class="empty">해당하는 단어가 없어요.</div>';}});
document.addEventListener('change',async e=>{
  if(e.target.id==='level-select'){if(state.session&&!state.session.finished){toast('진행 중인 학습을 먼저 마쳐 주세요.');e.target.value=state.settings.level;return;}state.settings.level=e.target.value;selectedUnit=null;save();render();}
  const setting=e.target.dataset.setting;if(setting){state.settings[setting]=setting==='furigana'?e.target.checked:Number(e.target.value);save();render();}
  if(e.target.id==='import-file'){const f=e.target.files[0];if(!f)return;if(f.size>4*1024*1024){toast('백업은 4MB 이하의 JSON 파일만 가져올 수 있어요.');return;}try{const imported=validateState(JSON.parse(await f.text()));openModal(`${modalHead('백업으로 기록을 바꿀까요?')}<p>현재 기록은 가져온 백업으로 대체됩니다. 현재 기록을 먼저 내보내는 것을 권장합니다.</p><div class="dialog-actions">${button('export','현재 기록 백업','secondary')}<button type="button" class="btn primary" id="confirm-import">백업으로 교체</button></div>`);document.querySelector('#confirm-import').onclick=()=>{stopAudio();state=imported;selectedUnit=null;storageWritable=true;rawBackup=null;storageWarning='';save();closeModal();go('learn');toast('백업을 가져왔어요.');};}catch(err){toast(err.message||'백업을 읽을 수 없어요.');}}
});
document.addEventListener('keydown',e=>{
  if(modalRoot.firstChild){if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const focusable=[...modalRoot.querySelectorAll('button:not(:disabled),input:not(.sr-only),select,a[href]')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}return;}
  if(route()==='session'&&e.target.id==='word-answer'&&e.key==='Enter'&&!e.isComposing&&e.keyCode!==229&&canCheck()){e.preventDefault();document.querySelector('[data-action="check"]').click();}
});
window.addEventListener('hashchange',()=>{audioRequest++;stopAudio();closeModal();render();scrollTo(0,0);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;});
window.addEventListener('storage',e=>{if(e.key!==STORAGE_KEY||!e.newValue)return;try{const updated=validateState(JSON.parse(e.newValue));if(updated.revision>=state.revision){state=updated;audioRequest++;stopAudio();render();toast('다른 탭의 최신 기록을 반영했어요.');}}catch{toast('다른 탭의 기록을 읽지 못했어요. 현재 학습은 유지됩니다.');}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){audioRequest++;stopAudio();}else if(['review','learn'].includes(route()))render();});
render();
if('serviceWorker'in navigator && ['https:','http:'].includes(location.protocol))navigator.serviceWorker.register(new URL('../sw.js',import.meta.url),{scope:new URL('../',import.meta.url).pathname}).catch(()=>{});
