import {kanaLessons,kanaCurrent,startKana,advanceKana,scriptName,ALL_KANA} from './kana-engine.js';
import {btn,esc,icon,heading} from './view.js';
import {characterStrokes} from './stroke-bank.js';
import {attachStrokePad} from './stroke-pad.js';
import {validPrefix} from './stroke-match.js';
import {speak,stopAudio} from './audio.js';
import {offerReviewPermission} from './reminders.js';
function spokenKana(c){return ({'ぁ':'あ','ぃ':'い','ぅ':'う','ぇ':'え','ぉ':'お','ゃ':'や','ゅ':'ゆ','ょ':'よ','っ':'ちいさいつ','ゔ':'ヴ','を':'お'})[c]||c;}
const count=k=>Object.keys(k.progress||{}).length;
export function kanaEntry(state){return `<section class="panel kana-entry"><span class="kana-entry-mark" lang="ja">あ<span>ア</span></span><div><small>N5 전 · 문자 입문</small><h2>히라가나 · 가타카나</h2><p>소리를 듣고, 한 획씩. ${count(state.kana)} / ${ALL_KANA.length}자</p></div>${btn('kana-open',icon('next'),'soft','aria-label="가나 입문 열기"')}</section>`;}
export function kanaHome(state){const k=state.kana,ls=kanaLessons(k.script),done=ls.flatMap(l=>l.letters).filter(x=>k.progress[x.id]).length,due=ls.flatMap(l=>l.letters).filter(x=>k.progress[x.id]?.due<=Date.now()).length;return `${heading('일본어의 첫 글자부터.','히라가나와 가타카나를 익힌 뒤 N5로 이어가세요.')}<div class="level-tabs kana-tabs" role="group" aria-label="가나 종류">${['h','k'].map(s=>`<button data-action="kana-script" data-script="${s}" aria-pressed="${s===k.script}" class="${s===k.script?'active':''}">${scriptName(s)}</button>`).join('')}</div><section class="panel kana-summary"><b>${done} / 81자</b><span>기억해서 쓰기 완료${due?` · 복습할 글자 ${due}자`:''}</span><div class="line-progress"><i style="width:${done/81*100}%"></i></div></section>${k.session&&!k.session.finished?`<section class="resume"><div><b>쓰던 글자를 이어서</b><p>${scriptName(k.script)} · ${k.session.index+1}번째 글자</p></div><div class="resume-actions">${btn('kana-resume','이어서','soft')}${btn('kana-restart-request','이 줄을 처음부터','text')}</div></section>`:''}<p class="fine kana-note">기본 46자 → 탁음·반탁음 25자 → 작은 글자·확장 10자. 한글 표기는 발음의 참고일 뿐, 일본어 소리를 그대로 나타내지는 못해요.</p><div class="kana-grid">${ls.map(l=>{const learned=l.letters.filter(x=>k.progress[x.id]).length,review=l.letters.some(x=>k.progress[x.id]?.due<=Date.now());return `<button class="panel kana-lesson ${learned===l.letters.length?'complete':''}" data-action="kana-start" data-id="${l.id}"><small>${l.basic?'기본':l.index<15?'탁음·반탁음':'작은 글자·확장'} ${l.index+1}</small><div class="kana-letterline"><strong lang="ja" data-fit-word data-max-font="23">${l.title}</strong></div><span>${learned}/${l.letters.length}자 · ${review?'복습하기':learned===l.letters.length?'다시 쓰기':'시작하기'}</span></button>`;}).join('')}</div><div class="spaced">${btn('kana-n5','N5 단어 학습으로','primary')}</div>`;}
function foot(k){const s=k.session,letter=kanaCurrent(k),total=letter?characterStrokes(letter.char).length:0;return `<footer class="lesson-footer"><div class="lesson-footer-inner"><span class="footer-hint">${s.strokes.length} / ${total}획</span>${btn('kana-next',s.stage===2?(s.hinted?'힌트 없이 다시 쓰기':'기억했어요'):'다음 연습','primary',s.strokes.length===total&&total?'':'disabled')}</div></footer>`;}
export function kanaPractice(state){const k=state.kana,s=k.session,letter=kanaCurrent(k);if(!s)return `<main class="focus-shell">${heading('연습할 글자를 골라 주세요.')}${btn('kana-open','가나 입문으로','primary')}</main>`;if(s.finished)return `<main class="focus-shell"><section class="result"><div class="result-emblem">${icon('check')}</div><h1>한 줄을 기억했어요.</h1><p>다음 복습 때 다시 꺼내 써 보세요.</p>${btn('kana-open','다른 글자 연습하기','primary wide')}${btn('kana-n5','N5 단어 학습으로','soft wide')}</section></main>`;const l=kanaLessons(k.script).find(x=>x.id===s.lessonId),guide=s.stage<2||s.hinted;return `<div class="focus-shell kana-focus"><header class="focus-top"><button class="icon-btn" data-action="kana-pause" aria-label="문자 수업 중단 메뉴">${icon('close')}</button><div class="session-progress"><div class="line-progress"><i style="width:${(s.index*3+s.stage)/(l.letters.length*3)*100}%"></i></div></div><span>${s.index+1} / ${l.letters.length}자</span></header><div class="session-label"><span>문자 입문 · ${scriptName(k.script)}</span><span>연습 ${s.stage+1}/3</span></div><main class="question" id="main">${heading(s.stage<2?'소리와 모양을 함께.':'이제, 기억해서 써 보세요.',s.stage<2?'획 끝의 작은 꺾임보다 전체 방향을 봐요.':'힌트를 보면 한 번 더, 가리고 연습해요.')}<div class="kana-prompt"><strong lang="ja">${guide?esc(letter.char):'?'}</strong><div><b>${esc(letter.hint)}</b><small>${letter.reading==='っ'?'촉음 · 단독 소리가 없어 이름을 들려드려요.':letter.small?'작은 글자 · 기본 소리를 들어요.':'한글은 발음 참고용이에요.'}</small></div><button class="audio-main" data-action="kana-listen" aria-label="가나 발음 듣기">${icon('sound')}</button></div><div class="ink-pad snap-pad"><div class="cross-lines"></div><canvas id="kana-canvas" aria-label="${scriptName(k.script)} 필기장"></canvas></div><p class="grader-status" id="kana-grade-status" role="status">한 획씩 쓰고 손을 떼 주세요.</p><div class="ink-toolbar">${btn('kana-undo',icon('undo')+' 한 획 취소','text')}${btn('kana-clear',icon('trash')+' 다시 쓰기','text')}${btn('kana-hint','힌트 보기','text')}${btn('kana-answer','정답 보기','text')}</div></main></div>${foot(k)}`;}
export function mountKana(state,{save,toast}){const k=state.kana,s=k.session,letter=kanaCurrent(k),canvas=document.querySelector('#kana-canvas');if(!letter||!canvas)return null;const paths=characterStrokes(letter.char);if(!paths.length){toast('이 글자의 획 데이터가 누락됐어요.');return null;}s.strokes=validPrefix(s.strokes,paths,{character:letter.char});let dead=false;
const pad=attachStrokePad(canvas,paths,s.strokes,{guide:s.stage<2||s.hinted,motion:state.settings.motion,width:state.settings.penWidth,character:letter.char,onAttempt(r,n,total){const status=document.querySelector('#kana-grade-status');if(status){status.textContent=r.accepted?(n===total?'글자를 완성했어요.':`${n}획 완성. 다음 획을 이어 주세요.`):r.reason;status.dataset.verdict=r.accepted?'correct':'retry';}const footer=document.querySelector('.lesson-footer');if(footer)footer.outerHTML=foot(k);save();}});
if(!s.autoPlayed){s.autoPlayed=true;save();setTimeout(()=>{if(!dead)speak(letter.id,state.settings.rate,{text:spokenKana(letter.reading)}).catch(e=>{if(!dead)toast(e.message);});},100);}
return {replay:()=>pad.replay(),destroy(){dead=true;pad.destroy();}};}
export async function handleKanaAction(action,data,state,{save,render,toast,go}){const k=state.kana,s=k.session,letter=kanaCurrent(k);
if(action==='kana-open'){stopAudio();await save();go('kana');}
else if(action==='kana-restart-confirm'&&s&&!s.finished){stopAudio();startKana(k,s.lessonId);await save();go('kana-practice');}
else if(action==='kana-resume'){go('kana-practice');}
else if(action==='kana-script'){if(k.session&&!k.session.finished&&data.script!==k.script){toast('쓰던 글자를 마친 뒤 다른 문자로 바꿔 주세요.');return;}k.script=data.script==='k'?'k':'h';await save();render();}
else if(action==='kana-start'){if(s&&!s.finished&&s.lessonId!==data.id){toast('진행 중인 가나 연습을 먼저 마쳐 주세요.');go('kana-practice');return;}if(s?.lessonId===data.id&&!s.finished){go('kana-practice');return;}if(startKana(k,data.id)){await save();go('kana-practice');}}
else if(action==='kana-next'&&letter){if(advanceKana(k,characterStrokes(letter.char).length)){stopAudio();await save();render();offerReviewPermission(state).catch(()=>{});scrollTo(0,0);}}
else if(action==='kana-undo'&&letter){s.strokes.pop();await save();render();}
else if(action==='kana-clear'&&letter){s.strokes=[];await save();render();}
else if((action==='kana-hint'||action==='kana-answer')&&letter){s.hinted=true;await save();render();if(action==='kana-answer')toast(`정답은 ${letter.char} (${letter.reading})예요. 정답 획을 보며 연습해 보세요.`);}
else if(action==='kana-listen'&&letter){await speak(letter.id,state.settings.rate,{text:spokenKana(letter.reading)}).catch(e=>toast(e.message));}
else if(action==='kana-n5'){if(state.session&&!state.session.finished){toast('진행 중인 단어 수업을 이어서 열었어요.');go('lesson');return;}state.settings.level='N5';await save();go('course');}
}
