import {statistics} from './statistics.js';
import {LEVELS} from './catalog.js';
import {btn,esc,icon,heading} from './view.js';
const labels={meaning:'뜻',listening:'듣기',writing:'쓰기'};
const nf=n=>n.toLocaleString();
export function statisticsView(state,words,view={}){
 const s=statistics(state,words,view),max=Math.max(1,...s.activity.map(d=>d.questions)),maxForecast=Math.max(1,...s.forecast.map(d=>d.count));
 const bars=s.activity.map((d,i)=>`<button class="activity-bar" data-action="stat-day" data-date="${d.date}" title="${d.date} · ${d.questions}문제" aria-label="${d.date} ${d.questions}문제"><span style="--bar:${Math.max(2,d.questions/max*100)}%" class="${d.questions?'filled':''}"></span><small>${s.days===7?['일','월','화','수','목','금','토'][new Date(d.date+'T12:00:00').getDay()]:i===0||i===s.activity.length-1?d.date.slice(5):''}</small></button>`).join('');
 const selected=s.activity.find(d=>d.date===view.date)||s.today;
 const categories=[['known','아는 단어'],['learned','수업 완료'],['learning','학습 중'],['unseen','미학습']];
 const marked=s.totals.known+s.totals.learned,progress=s.total?marked/s.total*100:0;
 const milestones=[['첫 100문제',s.allQuestions,100],['500문제',s.allQuestions,500],['아는 단어 100개',s.totals.known,100],['10회독',s.laps,10]];
 return `${heading('학습 기록')}<div class="stats-scope" role="group" aria-label="통계 급수">${['all',...LEVELS].map(l=>btn('stats-level',l==='all'?'전체':l,'text'+(s.level===l?' selected':''),`data-level="${l}" aria-pressed="${s.level===l}"`)).join('')}</div>
 <section class="stats-hero"><div><span class="stats-label">누적 XP · 전체 급수</span><strong>${nf(s.xp)}<small> XP</small></strong><p>${s.streak}일 연속 문제 풀이</p></div><div class="progress-orbit" style="--progress:${progress}%" role="img" aria-label="선택 급수 아는 단어와 수업 완료 ${marked}개, 전체 ${s.total}개"><div><b>${Math.round(progress)}<small>%</small></b><span>${s.level==='all'?'전체':s.level} 진행</span></div></div><footer><span>오늘 ${s.today.questions}문제</span><span>${s.chapters}개 챕터 완료</span><span>${s.laps}회독</span></footer></section>
 <section class="stats-panel"><div class="stats-section-title"><h2>학습량</h2><div class="stats-range" role="group" aria-label="통계 기간">${[7,30,90].map(n=>btn('stats-range',n===7?'7일':n===30?'30일':'90일','text'+(s.days===n?' selected':''),`data-days="${n}" aria-pressed="${s.days===n}"`)).join('')}</div></div><div class="stats-inline"><div><b>${nf(s.periodQuestions)}</b><span>문제</span></div><div><b>${nf(s.periodWords)}</b><span>단어</span></div><div><b>${s.activeDays}</b><span>학습일</span></div></div><div class="activity-chart" style="--columns:${s.days}" aria-label="일별 학습 문제 수">${bars}</div><p class="stats-day-readout" aria-live="polite">${selected.date.replaceAll('-','.')} · ${selected.questions}문제 · ${selected.words}단어${selected.practice?' · 단어장 쓰기 '+selected.practice+'회':''}</p><p class="stats-note">같은 날 같은 단어·유형은 한 문제로 집계합니다.</p></section>
 <section class="stats-panel"><div class="stats-section-title"><h2>단어 현황</h2><span>${nf(s.total)}단어</span></div><div class="status-stack" role="img" aria-label="단어 상태 비율">${categories.map(([key])=>`<span class="status-${key}" style="width:${s.total?s.totals[key]/s.total*100:0}%"></span>`).join('')}</div><div class="status-legend">${categories.map(([key,label])=>`<div><i class="status-${key}"></i><span>${label}</span><b>${nf(s.totals[key])}</b></div>`).join('')}</div><p class="stats-note">아는 단어는 직접 표시한 기록입니다. 유형별 시험 결과와 구분합니다.</p></section>
 <section class="stats-panel"><div class="stats-section-title"><h2>유형별 복습</h2><span>7일 이상 간격</span></div><div class="skill-stats">${s.skills.map(k=>`<div><div><b>${labels[k.skill]}</b><span>${nf(k.long)} / ${nf(k.total)}문제</span></div><div class="skill-track ${k.skill}"><i style="width:${k.total?k.long/k.total*100:0}%"></i></div><small>지금 복습 ${k.due}문제</small></div>`).join('')}</div><div class="mastery-total"><b>${nf(s.totals.mastered)}</b><span>뜻·듣기·쓰기 모두 7일 이상 간격인 단어</span></div></section>
 <section class="stats-panel"><div class="stats-section-title"><h2>복습 일정</h2><span>앞으로 7일</span></div><div class="forecast-chart">${s.forecast.map((d,i)=>`<div><b>${d.count}</b><span style="height:${Math.max(4,d.count/maxForecast*64)}px"></span><small>${i===0?'오늘':d.date.slice(5).replace('-','/')}</small></div>`).join('')}</div><p class="stats-note">오늘에는 기한이 지난 복습도 포함합니다.</p></section>
 <section class="stats-panel"><div class="stats-section-title"><h2>학습 배지</h2><span>${s.level==='all'?'전체 급수':s.level}</span></div><div class="milestone-grid">${milestones.map(([label,value,target])=>`<div class="milestone ${value>=target?'earned':''}"><span>${icon(value>=target?'check':'star')}</span><b>${label}</b><small>${Math.min(value,target)} / ${target}</small></div>`).join('')}</div></section>
 <div class="settings-quick spaced">${btn('settings',icon('settings')+' 설정','soft')}${btn('export',icon('download')+' 기록 백업','soft')}</div>`;
}
