import {fresh,validateState} from './course-engine.js';
const DB_NAME='kotoba-learning-v3';let db;
export class ConflictError extends Error{constructor(){super('다른 탭에서 기록이 바뀌었습니다. 최신 기록을 다시 불러왔어요.');this.name='ConflictError';}}
export async function openStore(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{req.result.createObjectStore('state');req.result.createObjectStore('packs');};req.onsuccess=()=>{db=req.result;db.onversionchange=()=>db.close();resolve();};req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('다른 창의 저장소를 닫고 다시 열어 주세요.'));});}
function read(store,key){return new Promise((resolve,reject)=>{if(!db)return reject(new Error('저장소를 사용할 수 없습니다.'));const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function loadState(){const data=await read('state','current');if(data)return validateState(data);const s=fresh();try{const old=JSON.parse(localStorage.getItem('kotoba-quest:v1')||'null');if(old){s.legacy={version:old.version,xp:old.xp||0};s.xp=old.xp||0;s.settings.furigana=old.settings?.furigana!==false;if(['N1','N2','N3','N4','N5'].includes(old.settings?.level))s.settings.level=old.settings.level;}}catch{}return s;}
export function commit(state,expected=state.revision){return new Promise((resolve,reject)=>{if(!db)return reject(new Error('저장소가 연결되지 않았습니다. 기록이 저장되지 않아요.'));const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),get=store.get('current');let result,conflict=false;
 get.onsuccess=()=>{if((get.result?.revision||0)!==expected){conflict=true;tx.abort();return;}result=structuredClone(state);result.revision=expected+1;store.put(result,'current');};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||new Error('저장 실패'));tx.onabort=()=>reject(conflict?new ConflictError():tx.error||new Error('저장 취소'));});}
export const loadPack=level=>read('packs',level);
export function savePack(pack){return new Promise((resolve,reject)=>{const tx=db.transaction('packs','readwrite');tx.objectStore('packs').put(pack,pack.level);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
export function rawState(){return read('state','current');}
export function replaceBackup(state,packs,expected){return new Promise((resolve,reject)=>{if(!db)return reject(new Error('저장소가 없습니다.'));const tx=db.transaction(['state','packs'],'readwrite'),store=tx.objectStore('state');const get=store.get('current');let output,conflict=false;get.onsuccess=()=>{if((get.result?.revision||0)!==expected){conflict=true;tx.abort();return;}output=structuredClone(state);output.revision=expected+1;store.put(output,'current');for(const p of packs)tx.objectStore('packs').put(p,p.level);};tx.oncomplete=()=>resolve(output);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(conflict?new ConflictError():tx.error||new Error('가져오기가 취소됐습니다.'));});}
